### ISSUE TITLE
 use much memory in my Linux system when I open my computer 

### ISSUE THREAD

**Issue by ajinwu** [kiteco/issue-tracker#156]
my system environment is kubuntu19.10, when I open my system, it will use much memory and it not stop if I did not kill this process, please help me, I send a mail on your website but not any response

there are two photos, please check it, thanks
![image1](https://imgse.com/i/QMYPfA)
![image2](https://imgse.com/i/QMYklt)

**Comment by ajinwu** [comment]
sorry, please look in this
https://imgse.com/i/QMYPfA
https://imgse.com/i/QMYklt

**Comment by metalogical** [comment]
this should now be fixed

Typical active memory usage: 800-1,200MB (depending on project size)
Typical idle memory usage: 300M
