### ISSUE TITLE
Kite always show "Kite: Not installed"

### ISSUE THREAD

**Issue by wang-zifu** [kiteco/issue-tracker#190]
But I did install kite engine following these steps:
![image](https://user-images.githubusercontent.com/30012352/80096756-eb373b80-851e-11ea-8ebf-52ae62e2b892.png)

![image](https://user-images.githubusercontent.com/30012352/80096889-32bdc780-851f-11ea-898d-27e715f7638f.png)

![image](https://user-images.githubusercontent.com/30012352/80097112-98aa4f00-851f-11ea-86ca-22ce5491d50c.png)

But restarting VSC does not fix the issue

**Comment by its-dhung** [comment]
Hi @wang-zifu, are you by chance using WSL? Kite currently does not support WSL.

**Comment by its-dhung** [comment]
@wang-zifu have you by chance disabled Spotlight from indexing your hard drive?

If not, what is the output of the terminal command:
```
mdfind kMDItemCFBundleIdentifier="com.kite.Kite"
```

**Comment by stompieman** [comment]
I have the same issue, but on windows.
Kite is installed. The vs code plugin is installed. I have reinstalled vs code and kite. The file type I'm using is .py.

On startup I get the: "Kite requires the Kite Engine backend to provide completions and documentation. Please install it to use Kite." message.
![image](https://user-images.githubusercontent.com/69766621/90731367-e6667680-e2c9-11ea-9555-6957731a362d.png)

**Comment by AndrewLaganaro** [comment]
Same issue on windows 10 with Vscode . I have reinstalled kite and kiteplugin. Nothing changed

**Comment by its-dhung** [comment]
@stompieman @AndrewLaganaro can you confirm that Kite is installed in `C:\Program Files\Kite`?

Also, what is the output of the command

```
reg query "HKEY_LOCAL_MACHINE\Software\Kite\AppData" /v InstallPath /s /reg:64
```

**Comment by AndrewLaganaro** [comment]
Kite is actually installed on B:\ because of space issues on disk C:, I installed on B:\ to save disk space.

I didn't know it would cause issues about the proper functioning of the plugin... I still have some space left on C:\ so I'll just reinstall kite on disk C:\ then and see what happens!

**Comment by AndrewLaganaro** [comment]
Just reinstalled Kite this time on disk C:\, the notification for installing kite was disappeared. Thanks!

**Comment by its-dhung** [comment]
Thanks for the info @AndrewLaganaro. Going to close this issue and track the issue of Kite being installed outside of the C:\ drive in #482.
