### ISSUE TITLE
Pycharm Kite is showing all the time same error "Please close all running instances of PyCharm before uninstalling" 

### ISSUE THREAD

**Issue by orikahmadov** [kiteco/issue-tracker#194]
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/b1bb6d0d-5e88-46eb-813a-e5ce95fe2663/kite_local/client.log.2020-04-27_09-01-45-PM.bak.gz

**Comment by its-dhung** [comment]
Hi @orikahmadov, the content at the bottom of [this help article](https://help.kite.com/article/112-issues-installing-editor-plugins) should be relevant. Please re-open if you still need help.
