### ISSUE TITLE
It says 'you have to be online to use search' when i search sth since several days ago

### ISSUE THREAD

**Issue by yz7zzxj1994** [kiteco/issue-tracker#195]
i kept my pc online when i use Kite
but i still say that

**Comment by yz7zzxj1994** [comment]
have raised applycation logs  and rsource usage in kite  yet -.-

**Comment by metalogical** [comment]
We recently released a new build which should not have this problem. Please ensure you're updated to the latest build (v20200504.1) and verify that the issue is fixed for you.

Let us know if you're still experiencing issues.

**Comment by yz7zzxj1994** [comment]
have solved yet since updated. Thank u 👍
