### ISSUE TITLE
"Set your Copilot to always be your top window" not available

### ISSUE THREAD

**Issue by Aekschen** [kiteco/issue-tracker#201]
For some reason I have on two PC (windows) this option not available:

> Set your Copilot to always be your top window

Version 1.2020.423.1
Windows 10

**Comment by takos22** [comment]
This option disapeared for me too. It was very usefull but I can't find it anymore.

Version: 1.2020.416.0
Windows 10

**Comment by lukeanavarro** [comment]
Same issue on a new install. 

Mac OS 10.15.4

**Comment by its-dhung** [comment]
Hi guys, we recently changed the always-on-top setting to instead enable/disable a feature where the Copilot would focus itself automatically when new documentation is rendered. So the Copilot would only be forced on top when new documentation was displayed.

I'm curious if the main issue here is that either:

1. The focus on docs feature doesn't work at all?
2. Or the feature does work, but you prefer having the Copilot always on top at all times?

**Comment by gahaalt** [comment]
Same issue, and new feature doesn't work at all for me. I hope you fix it, but still I'd like to have a choice if I want it to stay on top all the time or only when new documentation is shown. I am worried that it will flash too much, when switching between top and bottom.

VS Code, Windows 10
Kite version: 1.2020.423.1

**Comment by gahaalt** [comment]
Update:
New feature works with PyCharm, but not with VS Code.
Please fix it with VS Code.

Also, it works well there and does not flash as I thought. :)

**Comment by Aekschen** [comment]
I have seen the intended behavior in VS Code once but that was a one time thing. Seems to be buggy. Otherwise the set focus feature could be good.
(remember to update docs - https://help.kite.com/article/63-using-the-copilot)

**Comment by its-dhung** [comment]
Thanks for the input guys. We'll be fixing this in the next couple of weeks.

**Comment by ruslaniv** [comment]
Any update on this, it's been more than 2 weeks? 
I still would like to have it always be the top window, no matter if it is rendering anything or not.

**Comment by Triple-ROCK** [comment]
> Hi guys, we recently changed the always-on-top setting to instead enable/disable a feature where the Copilot would focus itself automatically when new documentation is rendered. So the Copilot would only be forced on top when new documentation was displayed.
> 
> I'm curious if the main issue here is that either:
> 
> 1. The focus on docs feature doesn't work at all?
> 2. Or the feature does work, but you prefer having the Copilot always on top at all times?

It really drives me crazy to lose the feature of always-on-top setting, because in mac it doesn't work at all !!! and I have to spare some space on my screen for it, which is really inconvenient, please fix it, thank you !

**Comment by lukeanavarro** [comment]
I am on a Mac and it never autofocuses. I've set up a desktop so that my windows are side by side. Good enough I guess. 


 > Hi guys, we recently changed the always-on-top setting to instead enable/disable a feature where the Copilot would focus itself automatically when new documentation is rendered. So the Copilot would only be forced on top when new documentation was displayed.
> > I'm curious if the main issue here is that either:
> > 
> > 1. The focus on docs feature doesn't work at all?
> > 2. Or the feature does work, but you prefer having the Copilot always on top at all times?
> 
> It really drives me crazy to lose the feature of always-on-top setting, because in mac it doesn't work at all !!! and I have to spare some space on my screen for it, which is really inconvenient, please fix it, thank you !

**Comment by ydguala** [comment]
Same for me on Windows 10 - v 1909
The copilot is not getting on top of VS Code 1.45.1
Kite v 1.2020.605.0

**Comment by its-dhung** [comment]
This should be released soon. Look for the new window management icon:

![image](https://user-images.githubusercontent.com/3752225/85605899-7a3bff00-b607-11ea-9add-39f102fdf6e3.png)
