### ISSUE TITLE
can't use search and it said that I should be online,but I am online.

### ISSUE THREAD

**Issue by EugeniaWEI** [kiteco/issue-tracker#202]
I can use any other softwares online. But I can't use kite online. By the way, I can enter kite's website online. I accidentally blocked the firewall when I first loaded Kite. I then whitelist the files kited.exe in the firewall. This still won't work. I then whitelist all exe files under Kite, but that didn't work.
How I can solve this problem? 
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/59decd5b-2a2d-4c86-8576-ac564048b2ea/kite_local/client.log.2020-05-02_12-13-49-AM.bak.gz
https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/59decd5b-2a2d-4c86-8576-ac564048b2ea/kite_local/1588349921777556200/capture.gz
![image](https://user-images.githubusercontent.com/62751541/80821726-df790280-8c0b-11ea-89cc-212334841c4e.png)
![image](https://user-images.githubusercontent.com/62751541/80821757-ef90e200-8c0b-11ea-8aa9-5432db29bed2.png)

**Comment by EugeniaWEI** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/62751541/80821800-06cfcf80-8c0c-11ea-90b1-1e39bea8247c.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/62751541/80821882-2cf56f80-8c0c-11ea-8332-d8f1117d5fc6.jpg)

**Comment by its-dhung** [comment]
Tracking this issue in #195.
