### ISSUE TITLE
the reset password process is a loop

### ISSUE THREAD

**Issue by fergusmeiklejohn** [kiteco/issue-tracker#208]
I enter my email address to reset my password.
I get an email with a link that takes me to a form with one input asking for my password.
I get the same email again that takes me to a form with one input asking for my password.
And so on. The url in the email is to `/reset-password...` so I imagine the problem with that page. The url in the email has params with my email address and token but it returns 301 and redirects to `reset-password` without the params

**Comment by its-dhung** [comment]
This issue should be resolved now.
