### ISSUE TITLE
Pycharm 2020.1.1 Plugin Error

### ISSUE THREAD

**Issue by tysun** [kiteco/issue-tracker#209]
PyCharm Plugin Error:
Plugin "Kite" is incompatible (until build 193.SNAPSHOT PY-201.7223.92).

PyCharm 2020.1.1 (Professional Edition)
Build #PY-201.7223.92, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8

**Comment by its-dhung** [comment]
This should be fixed now in the latest version of Kite.

**Comment by TangentIan** [comment]
@its-dhung when is this error release happening? I am getting the same error as above.

Plugin Error: Plugin "Kite" is incompatible (until build 193.SNAPSHOT < PY-201.7223.92).

I have the latest version of Kite.

![image](https://user-images.githubusercontent.com/1432548/81932800-a158e700-95ec-11ea-8f9d-3cafda50c79f.png)

Thanks,

**Comment by tysun** [comment]
not fixed.

**Comment by drasgo** [comment]
Same error recurred again for PyCharm 2020.2.1 

Plugin Error: Plugin "Kite" is incompatible (until build 201.SNAPSHOT < PY-202.6948.78).

**Comment by isolationism** [comment]
I am seeing the same, different version number:

> Plugin Error: Plugin "Kite" is incompatible (until build 201.SNAPSHOT < PY-202.7319.64).

I have used the Kite co-pilot app to uninstall and reinstall the plugin, and also to "reset" the installation, and tried manually disabling and re-enabling the plugin in PyCharm; no joy.

**Comment by jansorg** [comment]
@isolationism Could you post the installed version of Kite? You can see that at the end of the home tab at `Copilot > Settings (gear icon)`.

**Comment by isolationism** [comment]
Happily! It reports:

Version: 2.20200510.1

**Comment by jansorg** [comment]
@isolationism Thanks! Although the PyCharm plugin bundled with Kite is support 2020.2 for quite a while now, your installed version of Kite is most likely too old. Could you update kite and then reinstall the plugin via Copilot?
The current version of Kite is 2.20200916.3 (i.e. 2020-09-16).

**Comment by isolationism** [comment]
Spot on suggestion @jansorg — that was the problem; I didn't realize I was out of date. Updating, then disabling/re-enabling the plugin worked.

Hopefully the update contains a new-release notification, or one is planned for the future. Loving Kite so far, thank you for the support.
