### ISSUE TITLE
Kite won't auto start in neovim

### ISSUE THREAD

**Issue by kelvinmyli17** [kiteco/issue-tracker#211]
Every time I boot up my laptop, I use `neovim` to code python script and Kite doesn't start at all, I need to Uninstalling and re-Installing in Kite copilot app to trigger Kite activates in `neovim`. 

Do you guys know what cause this problem?

**Comment by its-dhung** [comment]
Hi @kelvinmyli17 to clarify: When you reboot, Kite thinks the plugin is installed for Neovim but when you start Neovim nothing happens. Then after you uninstall and reinstall the plugin, everything works?

@airblade any ideas on what might be causing this?

**Comment by airblade** [comment]
You could try `:KiteEnableAutoStart` inside Neovim.  This will launch Kite and also make sure that Kite is launched whenever Neovim is.

**Comment by kelvinmyli17** [comment]
@its-dhung yeah exactly, every time I want to use kite for neovim, I need to uninstalling it first and re-installing it to trigger kite

**Comment by kelvinmyli17** [comment]
@airblade I did this before, and nothing happens. kite still doesn't give any suggestion in my neovim

**Comment by airblade** [comment]
@kelvinmyli17 When it's not working, do you get any output with this?

```vim
:filter /kite/ scriptnames
```

**Comment by kelvinmyli17** [comment]
@airblade  yeah, like these : 
73: ~/.config/nvim/pack/kite/start/vim-plugin/plugin/kite.vim
109: ~/.config/nvim/pack/kite/start/vim-plugin/autoload/kite.vim
110: ~/.config/nvim/pack/kite/start/vim-plugin/autoload/kite/utils.vim
111: ~/.config/nvim/pack/kite/start/vim-plugin/autoload/kite/languages.vim
112: ~/.config/nvim/pack/kite/start/vim-plugin/autoload/kite/async.vim
113: ~/.config/nvim/pack/kite/start/vim-plugin/autoload/kite/client.vim
114: ~/.config/nvim/pack/kite/start/vim-plugin/autoload/kite/onboarding.vim

**Comment by airblade** [comment]
Ok, well at least the plugin is being loaded.  What version of neovim are you using?

Please can you turn on logging with `:let g:kite_log=1`, edit a Python file a bit, then post the log in `kite-vim.log` in neovim's current working directory.

**Comment by kelvinmyli17** [comment]
File: kite-vim.log
   1
   2   > /home/griffin/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http --
       timeout 120ms 'http://127.0.0.1:46624/clientapi/languages'
   3   < zsh:1: permission denied: /home/griffin/.config/nvim/pack/kite/start/vim-plu
       gin/lib/linux/kite-http
   4   <

neovim version: 

> NVIM v0.4.3

**Comment by airblade** [comment]
>  permission denied: /home/griffin/.config/nvim/pack/kite/start/vim-plu
gin/lib/linux/kite-http

Aha, there's the problem.  I wonder if that's because the script is not executable...please could you do `ls -l /home/griffin/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http` and see whether it's executable?

If not, `chmod +x /home/griffin/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http` should hopefully get it all working.

FYI the source of `kite-http` is here: https://github.com/kiteco/vim-plugin-helper/blob/master/kite-http.go.  We need it to be able to talk HTTP from neovim to the Kite process.

**Comment by kelvinmyli17** [comment]
@airblade yeah that's the main problem haha, and now it works smoothly after I chmod +x that file.
Thanks for your guidance, appreciate it so much...

and do you know how to change Ctrl + n for select next suggestion to TAB in kite?

**Comment by airblade** [comment]
Glad it's working!

You could try this to get TAB to move to the next completion option:

```viml
imap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
```

@jansorg It's strange that the binary wasn't executable because its permissions are 755 in the repo.  Is it worth adding a check for this to the kite installer?

**Comment by kelvinmyli17** [comment]
Thanks !

Andy Stewart <notifications@github.com> 于 2020年5月22日周五 15:08写道：

**Comment by jansorg** [comment]
@airblade Good point! I'll track this in the internal repo to add this change.

**Comment by hixan** [comment]
I had the same issue and originally decided that it was going to be work to get kite to work reliably and decided against using it. (I have obviously now found the issue on a second try) - maybe this could be fixed in the installer?

**Comment by airblade** [comment]
@naman Is it possible the Kite installer doesn't set `kite-http`'s executable bit when updating it?
