### ISSUE TITLE
ubuntu 18.04 server fail to install 

### ISSUE THREAD

**Issue by boydream123** [kiteco/issue-tracker#212]
[installer] error installing kite protocol handler. exec: "xdg-mime": executable file not found in $PATH, output:
[installer] Rolling back installed data...
[installer] terminating kite processes
[installer] removing kite-updater systemd service
[installer] removed ~/.config/autostart/kite-autostart.desktop
[installer] removed ~/.config/systemd/user/kite-updater.service
[installer] removed ~/.config/systemd/user/kite-updater.timer
[installer] removed ~/.local/share/applications/kite-copilot.desktop
[installer] removed ~/.local/share/applications/kite.desktop
[installer] removed ~/.local/share/icons/hicolor/128x128/apps/kite.png
[installer] removed ~/.local/share/kite/kited
[installer] removed ~/.local/share/kite/uninstall
[installer] removed ~/.local/share/kite/update
[installer] removed ~/.local/share/kite

**Comment by cmoog** [comment]
This can be worked around by running
```
sudo apt-get update -y
sudo apt-get install -y xdg-utils
```

**Comment by its-dhung** [comment]
Thanks for the assist @cmoog! I've updated our [help docs](https://help.kite.com/article/106-linux-install-issues) with this information.

**Comment by boydream123** [comment]
I have installed it successfully. Thank you very much.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Charles Moog <notifications@github.com>
发送时间: Wednesday, May 13, 2020 11:18:23 PM
收件人: kiteco/issue-tracker <issue-tracker@noreply.github.com>
抄送: boydream123 <boydream123@outlook.com>; Author <author@noreply.github.com>
主题: Re: [kiteco/issue-tracker] ubuntu 18.04 server fail to install (#212)


This can be worked around by running

sudo apt-get update -y
sudo apt-get install -y xdg-utils


―
