### ISSUE TITLE
Broken link to reset password.

### ISSUE THREAD

**Issue by maxchehab** [kiteco/issue-tracker#214]
When attempting to reset my password, after selecting the link the email I was redirected to `https://kite.com/reset-password`. However this page returned a 404.

I also noticed this link was mentioned in your [Account Guide](https://help.kite.com/article/64-managing-your-user-account).

**Comment by metalogical** [comment]
Sorry about this! We've been experiencing some CDN-related issues.

Things should be rewired now and working, but you may have to clear your cache, as the DNS entry has changed.

**Comment by adamsmith** [comment]
(The DNS cache TTL is 5 minutes so it's _possible_ you may not need to clear your cache.)
