### ISSUE TITLE
404 error when trying to activate pro trial

### ISSUE THREAD

**Issue by jparkrr** [kiteco/issue-tracker#215]
https://alpha.kite.com/web/account/start-trial?cta-source=copilot_notif

This happens from the website or the app.

Thanks! Can't wait to try it out.

**Comment by darioromero** [comment]
It happen to me the same. It seems the website isn't ready. Looking forward to try it. Thanks.

**Comment by adamsmith** [comment]
Sorry about the downtime. It should be resolved now. Thanks!
