### ISSUE TITLE
Kite is ready but not working in ST3

### ISSUE THREAD

**Issue by minhsiro** [kiteco/issue-tracker#218]
Kite's autocompletion doesn't work in Sublime Text 3 but it still works in VS code.

**Comment by its-dhung** [comment]
1. Do other Kite features in Sublime work?
2. Are there any errors shown in Sublime's console?

**Comment by jgburet** [comment]
Same problem here
Downloaded Kite yesterday
Tried today to follow the JS tutorial but none of the auto-completion exercises are working.

- [x] read https://help.kite.com/article/121-troubleshooting-the-sublime-text-plugin
- [x] read https://help.kite.com/article/96-contact-us-with-logs


- Kite status in ST is "Ready"
- I have a screen recording: what's your email address?
- my Kite logs https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/4cedf617-d594-428b-abef-489dad4973e9/kite_local/client.log.2020-05-15_03-23-17-PM.bak.gz
- No errors in ST console

```
reloading plugin KiteSublime.KiteSublime
...
[Kite] 05/15/20 15:14:51.824 | Kite v0.4.3 activated
```

**Comment by erikverheij** [comment]
I was thrilled to see that Kite was available for JS. However, I also can't get it working in Sublime. 

"Kite: Ready" is displayed in the status bar.

My first attempt was to disable SublimeCodeIntel. After I did that, Kite did work for some very simple scripts but not for the more complex one and also not for the tutorial.

These were some errors I caught in the console in verbose logging mode:
```
[Kite] caught expected ExpectedError: (timeout('timed out',), 'timed out')
[Kite] completions location mismatch: 19 != 2660
[Kite] caught expected ExpectedError: (CannotSendRequest('Request-sent',), 'Request-sent')
[Kite] forcing defer because queue is full
indexing [job 5]: no files were indexed out of the 4096 queued, abandoning crawl
[Kite] completions location mismatch: 2653 != 2654
[Kite] possible matched completions: []
[Kite] no matching completion
``` 

Looking forward to see it working!

**Comment by its-dhung** [comment]
@erikverheij can you also send us your Kite logs? You can access them by visiting kite://settings/logs in your browser.

To help us reproduce your issue, could you please share an example code snippet that Kite fails to suggest completions for?

**Comment by MinhSiRo** [comment]
My problem is solved, somehow the Sublime Text 3's user setting " auto_complete " is set to "False".

**Comment by erikverheij** [comment]
> My problem is solved, somehow the Sublime Text 3's user setting " auto_complete " is set to "False".

Unfortunately, that wasn't the issue in my case.

I'm trying the js tutorial. For other JS files it sometimes works but it stops working at unpredictable intervals.

I guess this will show you my logs?:

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/37027/kite_local/client.log.2020-06-13_11-55-35-AM.bak.gz

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/37027/kite_local/client.log.2020-06-13_11-59-54-AM.bak.gz
