### ISSUE TITLE
Honor lifetime Pro license from 2017

### ISSUE THREAD

**Issue by ekoepplin** [kiteco/issue-tracker#223]
Hi,
I have a message popping up recently "Kite Pro trial will end in 42 days. Subscribe now!" That must be a technical issue since I have purchased a Kite Pro lifetime licence in 2017. Could you help to understand that?
Best

**Comment by metalogical** [comment]
Hi, thanks for letting us know. We recently released an updated Kite Pro product, and we just need to grandfather old users in.

I'll let you know when this is done (later today), but in the meantime, using the trial should hold you over.

**Comment by smeggingsmegger** [comment]
Yes, same here please.

**Comment by metalogical** [comment]
Hi @ekoepplin ,

I've issued you a recurring license for our new Kite Pro product. Kite should automatically register the license from our server if you are online (it may take a short amount of time to refresh).

Let us know if things aren't working for you.

**Comment by metalogical** [comment]
@smeggingsmegger and any future people:

Please shoot an email over to feedback@kite.com with the email associated with your Kite account, and we'll issue you a license. Thanks!
