### ISSUE TITLE
Plugin install doesn't work with pycharm professional 2020.1.1

### ISSUE THREAD

**Issue by ramannanda9** [kiteco/issue-tracker#225]
The plugin won't work even though install is succesfull.

**Comment by its-dhung** [comment]
Can you share a screenshot of the error you're seeing?

**Comment by Allaye** [comment]
@its-dhung for kite installs successfully, but the kite icon won't show on pycharm and copilot wont stick and does not work

**Comment by Allaye** [comment]
> The plugin won't work even though install is succesfull.

Have you found a solution

**Comment by ramannanda9** [comment]
nope, even autocomplete suggestions don't show up for me. After restarting pycharm, tells me to restart again for installing kite plugin, which obviously doesn't work.

**Comment by monkeyonagazeboo** [comment]
Same here, Pycharm 2020.1.2 Professional. Kite Copilot app shows plugin installed, but I dont see the icon in pycharm neither there are any kite related settings. Obviously the kite autocomplete does not work at that point. Plugin installed in MSCode works fine.

**Comment by ramannanda9** [comment]
pro user here, the support is really bad.

**Comment by ramannanda9** [comment]
![Screen Shot 2020-07-10 at 10 07 54 AM](https://user-images.githubusercontent.com/883240/87180354-457da800-c295-11ea-8284-9ca690ba85c5.png)
![Screen Shot 2020-07-10 at 10 08 36 AM](https://user-images.githubusercontent.com/883240/87180409-5a5a3b80-c295-11ea-83f3-7d822291fe00.png)

**Comment by its-dhung** [comment]
@jansorg is there any additional info we can get to debug? Possibly logs from PyCharm?

**Comment by jansorg** [comment]
@ramannanda9 This setup (PyCharm Pro + Kite) is definitely supposed to work. There's two things you could check:
1. making sure that the plugin is properly installed (PyCharm>Preferences>Plugins>Installed Plugin>search for Kite). Please make sure that it's enabled. If it was disabled at some point, PyCharm is keeping it that way, even when it's updated.
2. open a .py file and make sure that the Kite icon shows up in the status bar

If it doesn't, then these logs would help us to debug:
1. the file `$HOME/.kite/logs/client.log`
2. the PyCharm log files, obtained via `Help>Collect Logs and Diagnostic Data`

Feel free to send these files to support@kite.com if you don't want to make them public here.

**Comment by ramannanda9** [comment]
the plugin works fine with pycharm 2020.1.3, so fine with closing this issue for now.
