### ISSUE TITLE
Application size almost 1Gb

### ISSUE THREAD

**Issue by EthanSbbn** [kiteco/issue-tracker#229]
Is that normal to get almost 1Gb of application size, when unpacked?
Seems quite a lot for that kind of app...

<img width="706" alt="image" src="https://user-images.githubusercontent.com/3668056/82044892-75059f00-96ae-11ea-8cef-124b8fe802b3.png">

**Comment by its-dhung** [comment]
This is normal. The datasets and models that power Kite take up quite a lot of space unfortunately.
