### ISSUE TITLE
Kite autocompletion problem in sublime

### ISSUE THREAD

**Issue by pritul2** [kiteco/issue-tracker#231]
The problem is arising from today only earlier there is no such problem

Here I write get .... and it shows options
![image](https://user-images.githubusercontent.com/41751718/82143998-171ab800-9864-11ea-98a3-a57e7a1bdf2d.png)

Then I press tab
and it replaces with this
![image](https://user-images.githubusercontent.com/41751718/82144032-1eda5c80-9864-11ea-85f8-fca184d140b0.png)

It has removed the first two characters
It is happening with all the autocompletion

**Comment by its-dhung** [comment]
This was fixed by https://github.com/kiteco/KiteSublime/pull/79 and should be in the next release of Kite. You may need to reinstall the Sublime plugin to get the update.
