### ISSUE TITLE
not finding on documentation for kivy in the copilot app

### ISSUE THREAD

**Issue by bechara-rizk** [kiteco/issue-tracker#232]
When i search anything related to the kivy model for python i get 'No results found for "kivy". Try searching for an identifier starting with its package name.'

Is there any fix for this?

**Comment by its-dhung** [comment]
Hi @bechara-rizk, the search bar only works with packages that we have publicly indexed. Kivy unfortunately is not in our list of packages. You should, however, be able to get docs in the Copilot using the docs following cursor feature.
