### ISSUE TITLE
Kite won't autocomplete variables into functions

### ISSUE THREAD

**Issue by Destaq** [kiteco/issue-tracker#234]
When I was looking at https://kite.com/python/answers/how-to-sort-a-list-based-on-another-list-in-python, I saw the little video on the right that demonstrates how Kite worked. I typed in the exact same things into my kite, however it was not completing it or showing the same options.

Supposed Kite Image:
![image](https://user-images.githubusercontent.com/61620873/82310427-a9d26880-99c4-11ea-8bf8-05329881cdeb.png)

My Image:
![image](https://user-images.githubusercontent.com/61620873/82310373-97f0c580-99c4-11ea-9392-d9b65f7ea683.png)

I'm using Atom to program with. Is there anyway to get Kite running as it did in the video?

**Comment by its-dhung** [comment]
Hi @Destaq, those advanced completions are a paid feature now. You can try Kite Pro for free by visiting https://kite.com/pro and then clicking on "Try for free".
