### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by asamolion** [kiteco/issue-tracker#235]
The `kited` processes consistently uses about 1.2 GB of RAM when I run it with Sublime Text.

Is this normal?

**Comment by nhardy01** [comment]
same for me with both VSCode and Atom

**Comment by Natetronn** [comment]
kited is running at 1.4GB. Mostly using it in VS Code but, it's installed for Sublime as well.

Note: logs are after I killed kited. I can do it again after it hits high:

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/50231/kite_local/client.log.2020-05-27_06-40-26-PM.bak.gz

https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/50231/kite_local/1590630038862292534/capture.gz

**Comment by its-dhung** [comment]
Hi @asamolion, @nhardy01 please provide your performance logs, which you can access by visiting kite://settings/logs in your browser.

**Comment by Natetronn** [comment]
@its-dhung another note on this, if I may. I just started up VS Code and kited starts running at about 100,000kb, which puts it in the 4th most memory intensive app that I currently have open, behind Firefox (crazy memory use, but we knew that), Electron (140k and 135k kb) and Latte-Dock (slightly more memory use at 115k kb.)

**Comment by nhardy01** [comment]
@its-dhung logs here, generated using the copilot logs tab

Application logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/317531/kite_local/client.log.2020-06-01_12-17-31-PM.bak.gz

Resource usage: https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/317531/kite_local/1591039122496885812/capture.gz

Screencap of system resources after logs were generated, forted by percent memory usage. Kite is by far the largest memory hog, more than VSCode itself.

![image](https://user-images.githubusercontent.com/27230982/83445739-60413f00-a402-11ea-850a-8afe3672ac46.png)

**Comment by metalogical** [comment]
this should now be fixed with memory usage similar to MacOS and Windows.

Typical active memory usage: 800-1,200MB (depending on project size)
Typical idle memory usage: 300M

Let us know if you're still experiencing poor performance.

**Comment by asamolion** [comment]
Ah, I see. so this takes a gig of memory in normal usage. Cool to know.

**Comment by Natetronn** [comment]
@metalogical what was the version bump on this? It appears I'm running Version: 2.20200619.1 and just wanted to make sure I've been updated or not.

**Comment by metalogical** [comment]
2.20200619.1 is the latest version, which includes the Linux memory fix

**Comment by Natetronn** [comment]
Thank you!

**Comment by SanjeevSolanki** [comment]
![KiteRamUsageIssue](https://user-images.githubusercontent.com/7089006/86194035-09a15f00-bb80-11ea-8e20-00774b988046.png)

Still an issue. not resolved.

**Comment by metalogical** [comment]
@SanjeevSolanki if you're seeing performance problems, please open a new issue with appropriate logs attached.
