### ISSUE TITLE
RAM usgae 

### ISSUE THREAD

**Issue by Nishit-Dua** [kiteco/issue-tracker#237]
Hi I absolutely love kite and i have been using it for almost 5 months now but recently after the launch of Js autocomplete the kited process have been hoging up almost 700 mb of RAM even when i am not using any editor, i have disabled js and go auto-complete. But the kited process still eats up a lot of memory also i would like to configure it such it only runs when  i am using an editor in which i have kite installed. is there any setting for that as i looked and didn't find anything

**Comment by its-dhung** [comment]
Please provide your memory logs which you can access by visiting kite://settings/logs in your browser.

**Comment by Nishit-Dua** [comment]
Resource Usage logs: https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/7d69858b-93fc-4e90-b00b-4afcdf50f2c4/kite_local/1591274485630097231/capture.gz

BTW i fixed the memory hogging issue by removing kite from auto-start and writing a script which kills kite's services when i am not using any editor and then restarts kite after i open the editor, but i would love if this could be integrated in kite as a feature for devices with limited resources.

**Comment by metalogical** [comment]
this should now be fixed with memory usage similar to MacOS and Windows.

Typical active memory usage: 800-1,200MB (depending on project size)
Typical idle memory usage: 300M

Let us know if you're still experiencing poor performance.
