### ISSUE TITLE
Overhead Resource Usage - load all free memory on Linux Mint 19.3

### ISSUE THREAD

**Issue by ofisser86** [kiteco/issue-tracker#244]
Kite Load all free memory (swap including) on Linux Mint 19.3 when I use PyCharm or VS Code, after few hours of using IDE

[APPLICATION LOGS](https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/150157/kite_local/client.log.2020-06-01_01-47-56-PM.bak.gz)

[RESOURCE USAGE](https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/150157/kite_local/1591008473886886554/capture.gz)

**Comment by metalogical** [comment]
merging into #235
