### ISSUE TITLE
vscode kite is not running..

### ISSUE THREAD

**Issue by fdq09eca** [kiteco/issue-tracker#247]
I still had it working a few days ago but now it shows kite engine is not running, any idea why?

![image](https://user-images.githubusercontent.com/51902242/83466671-62f76f00-a4aa-11ea-92db-55573622c249.png)

here is my vscode preference setting:
```json
{
  "kite.showWelcomeNotificationOnStartup": false,
  "workbench.activityBar.visible": false,
  "explorer.confirmDelete": false,
  "workbench.colorTheme": "Expressive Theme",
  "workbench.iconTheme": "vscode-icons",
  "css.remoteStyleSheets": [
    "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
  ],
  "git.confirmSync": false,
  "python.jediEnabled": false,
  "markdown-preview-enhanced.liveUpdate": true,
  "window.zoomLevel": 1,
  "C_Cpp.updateChannel": "Insiders",
  "files.associations": {
    "*.rmd": "rmd"
    // "*.html": "jinja-html"
  },
  "files.autoSave": "afterDelay",
  "explorer.confirmDragAndDrop": false,
  "editor.formatOnSave": true,
  "liveServer.settings.donotVerifyTags": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "python.dataScience.sendSelectionToInteractiveWindow": false
}

```

in addition, when i click on the kite app (MacOS)
this happens
![image](https://user-images.githubusercontent.com/51902242/83467154-ae5e4d00-a4ab-11ea-997b-ebdecc33651d.png)

Thank you

**Comment by its-dhung** [comment]
Kite may have been corrupted when it updated itself. Does downloading and reinstalling Kite from https://kite.com/download fix this issue for you?

**Comment by fdq09eca** [comment]
> Kite may have been corrupted when it updated itself. Does downloading and reinstalling Kite from https://kite.com/download fix this issue for you?

it works, Thank you! but.. why?

![image](https://user-images.githubusercontent.com/51902242/83470377-9f2fcd00-a4b4-11ea-98e3-6c9303701d16.png)

**Comment by its-dhung** [comment]
We had an issue with our CA certificate that was preventing some users from downloading Kite. I'm guessing it may have affected updates as well. This was fixed today.
