### ISSUE TITLE
Kite was unable to listen on port 46624.

### ISSUE THREAD

**Issue by rickdee88** [kiteco/issue-tracker#253]
Hi,
This error (shown in attachment) started to appear more frequently when I try to open the Epson Scanner software in my laptop. My Epson printer model is L210.
Please help. Thanks
![kite](https://user-images.githubusercontent.com/9567283/83826866-91c24f00-a70f-11ea-8fa5-cd6498f90927.jpg)

**Comment by its-dhung** [comment]
To clarify, does this only happen when you open your printer software?

**Comment by rickdee88** [comment]
Daniel,

Sorry for my late reply.
Answer is no. Recently I found out that everytime I reboot my laptop it will come up.

Thanks
Regards

**Comment by its-dhung** [comment]
Closing this and tracking in #448
