### ISSUE TITLE
[https://help.kite.com/] Sorting selector issue

### ISSUE THREAD

**Issue by duyphanz** [kiteco/issue-tracker#254]
Hi, I've installed Kite and found this bug when reading how to use.

**Describe the bug**
Enter https://help.kite.com/category/46-vs-code-integration

Chrome browser, macOs

**Screenshots**

![image](https://user-images.githubusercontent.com/13731780/83987668-3c827980-a96b-11ea-8021-eeb66cdb5e0c.png)

**Comment by its-dhung** [comment]
Thanks for the heads up! This has been fixed.
