### ISSUE TITLE
Problems with starting "KiteSetupSplashScreen.exe" 

### ISSUE THREAD

**Issue by Far00K** [kiteco/issue-tracker#263]
I've tried running it on admin, restarted the computer and so on. 

All I get is the same picture:
![kiteProblem](https://user-images.githubusercontent.com/27159994/84694628-cae99300-af49-11ea-8506-1a6ed812506d.PNG)

**Comment by its-dhung** [comment]
Hi @Far00K, we're tracking this issue in #158. Please feel free to chime in there. [This comment](https://github.com/kiteco/issue-tracker/issues/158#issuecomment-619214452) in particular explains what info you could provide to us to help us debug.

**Comment by Far00K** [comment]
I mean I have dowloaded kite from ur page "https://kite.com/download/". After I've run it I open the "KiteSetupSplashScreen" in C:\Program Files\Kite . Its here I get the window after it loads a minute or so.

**Comment by adamsmith** [comment]
Hi, if you are open to trying this we would like to know if it happens on the latest version of Kite. See https://github.com/kiteco/issue-tracker/issues/158#issuecomment-656320133  Thanks!
