### ISSUE TITLE
Vscode autocomplete is duplicated

### ISSUE THREAD

**Issue by Megachell0** [kiteco/issue-tracker#272]
How can I disable default auto-complete?
![image](https://user-images.githubusercontent.com/42599314/85445068-69aa6b00-b5ac-11ea-8149-166ccdb3abf9.png)

if i change "editor.quickSuggestions" to false then all suggestions are disabled.

**Comment by its-dhung** [comment]
It appears that you can't do this without uninstalling Microsoft's Python extension completely.
