### ISSUE TITLE
look - your your .exe file is being sent out kited.exe... i paid 200 bucks today and cant get in touch with anyone. What an i suppose to do ? have someone call me today  ‪(910) 889-0276‬

### ISSUE THREAD

**Issue by HollywoodQ** [kiteco/issue-tracker#275]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

**Screenshots**

**Comment by its-dhung** [comment]
Hi @HollywoodQ, for issues related to Kite Pro please contact support@kite.com. Please contain in your email the problem you're having and we'd be happy to help you debug. If possible, include screenshots of the errors/problem you're experience.
