### ISSUE TITLE
Copilot is hidden behind other windows

### ISSUE THREAD

**Issue by Tomipapa** [kiteco/issue-tracker#278]
Hi,

I am new to Kite/Copilot. 

As per user manual I try to get Copilot in front of other windows but the "Set your Copilot to always be your top window" checkbox is not visible in my Settings screen.

I am running Kite/Copilot on MBP macOS Catalina 10.15.5 and just installed the latest version 0.20200629.0 of your package.

Could you please advise how to fix this inconvenience?

Thank you

**Comment by its-dhung** [comment]
See #201. This has been fixed but not released yet.
