### ISSUE TITLE
Kite with JupyterLab 

### ISSUE THREAD

**Issue by Jacques2101** [kiteco/issue-tracker#281]
Hi I tried to installl kite for jupyterlab so I follow the download instructions ie I did : 
- pip install jupyter-kite
- then install the kite extension with :  jupyter labextension install @kiteco/jupyterlab-kite

but nothing happened...
First time I had in the bar a message with kite but something like 'not working' 
I tried then to desinstall the extension and then nothing happens. I even don't see the previous message (that's why I can't send you a screenshot)

Thanks for your help.

**Comment by metalogical** [comment]
Kite for JupyterLab is currently under development and not yet supported for general use. We will release a non-alpha version once it is officially supported: https://pypi.org/project/jupyter-kite/#history
