### ISSUE TITLE
Kite can't work and is stuck in "indexing"

### ISSUE THREAD

**Issue by MasterTsai** [kiteco/issue-tracker#282]
Here is my APPLICATION LOGS : https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/195221/kite_local/client.log.2020-07-09_02-25-36-PM.bak.gz
I use Spyder 4.1.2. My kite always keeps on indexing and can't work right.
![image](https://user-images.githubusercontent.com/60482450/87005103-131a6f00-c1f1-11ea-8417-46a4e3d55663.png)

**Comment by metalogical** [comment]
Hi @MasterTsai 

When you say that Kite doesn't work, could you be a bit more precise? Do Kite completions work at all for Python files? At least some single-file completions should work regardless of whether Kite was able to build an index (indexes are only necessary for multi-file projects).

Based on the logs it looks like some indexes did build successfully. Could you share the file path for the file where Kite never finished indexing.

Thanks

**Comment by MasterTsai** [comment]
Hello!
I am glad to receive you email.&nbsp; I think that I have solved the problem! My spyder's version is 4.1.3. I find that LSP keep cycling like restarting....restarting...ready....restarting....restarting.... I think that maybe LSP influence Kite? I don't know how to uninstall or close the LSP, so I decide to downgrade the version of Spyder to 4.0.1, where the LSP can't work at all and can't restart because of lack of some packages. Surprisingly, Kite can work. I guess that LSP and Kite are somewhat&nbsp;interdependent. I hope that LSP can be more stable in the next version or let users be able to close LSP.
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Naman"<notifications@github.com&gt;; 
发送时间: 2020年7月11日(星期六) 凌晨1:37
收件人: "kiteco/issue-tracker"<issue-tracker@noreply.github.com&gt;; 
抄送: "9769ic_abcd"<1509786338@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [kiteco/issue-tracker] Kite can&#39;t work and is stuck in &quot;indexing&quot; (#282)





 
Hi @MasterTsai
 
When you say that Kite doesn't work, could you be a bit more precise? Do Kite completions work at all for Python files? At least some single-file completions should work regardless of whether Kite was able to build an index (indexes are only necessary for multi-file projects).
 
Based on the logs it looks like some indexes did build successfully. Could you share the file path for the file where Kite never finished indexing.
 
Thanks

**Comment by MasterTsai** [comment]
Kite is already successfully installed. The issue is caused by LSP.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Naman"<notifications@github.com&gt;; 
发送时间: 2020年7月11日(星期六) 凌晨1:37
收件人: "kiteco/issue-tracker"<issue-tracker@noreply.github.com&gt;; 
抄送: "9769ic_abcd"<1509786338@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [kiteco/issue-tracker] Kite can&#39;t work and is stuck in &quot;indexing&quot; (#282)





 
Hi @MasterTsai
 
When you say that Kite doesn't work, could you be a bit more precise? Do Kite completions work at all for Python files? At least some single-file completions should work regardless of whether Kite was able to build an index (indexes are only necessary for multi-file projects).
 
Based on the logs it looks like some indexes did build successfully. Could you share the file path for the file where Kite never finished indexing.
 
Thanks

**Comment by metalogical** [comment]
Great. You may want to open an issue in [Spyder issue tracker](https://github.com/spyder-ide/spyder/issues) regarding the trouble with Spyder LSP support.
