### ISSUE TITLE
Unable to install in dell n5040 2010 bought laptop

### ISSUE THREAD

**Issue by Raji42** [kiteco/issue-tracker#283]
Hi,
im unable to install kite in windows 10  dell5040(2010 model laptop),please help me friends?
![kitCapture](https://user-images.githubusercontent.com/64631828/87246328-5af7fb00-c46a-11ea-96ee-00fa6becd52e.PNG)

**Comment by Raji42** [comment]
Please help?

**Comment by its-dhung** [comment]
Kite doesn't support machines without AVX.
