### ISSUE TITLE
Is it possible use Kite Pro on different computers with one account?

### ISSUE THREAD

**Issue by KonstantinAlxVlasenko** [kiteco/issue-tracker#284]
Hello!

Is it possible use Kite Pro on different computers with one account?
On the first computer Kite shows PRO logo but
If I login Kite on another computer with the same account Kite doesn't show PRO logo even if I logout on the first computer.

**Comment by its-dhung** [comment]
This should be possible. Please send us your logs from the computer that's not working if you're still experiencing this problem.

**Comment by KonstantinAlxVlasenko** [comment]
Hello Daniel,

Yes I still have the issue.
Logs have been generated.

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/235926/kite_local/client.log.2020-07-29_01-37-59-AM.bak.gz

best regards,
Konstantin

пн, 27 июл. 2020 г. в 22:11, Daniel Hung <notifications@github.com>:

**Comment by KonstantinAlxVlasenko** [comment]
Hello Daniel,

Have u found any issues in the log file?

best regards,
Konstantin Vlasenko

ср, 29 июл. 2020 г. в 01:40, Konstantin Vlasenko <kvl2014@gmail.com>:
