### ISSUE TITLE
Facing problem to install kite on Ubuntu 20.04

### ISSUE THREAD

**Issue by The-Pacman** [kiteco/issue-tracker#287]
***I tried to use the following command to install kite in the terminal*** 
`bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"`
But it shows the following error:

![Screenshot from 2020-07-18 00-34-02](https://user-images.githubusercontent.com/68441629/87820343-bde4fa00-c88f-11ea-9e41-c9a03aea1aff.png)

**Comment by sveiaam** [comment]
I get the exact same message on Ubuntu 18.04, after I first installed the corresponding package in the atom editor. I fixed it by uninstalling the failed install like this:
```
sveiaam@thinkpad: ~$ ./kite-installer uninstall
sveiaam@thinkpad: ~$ rm -rf kite-installer
```
I re-installed the atom package afterwards without a hitch.

**Comment by The-Pacman** [comment]
Thanks @sveiaam . It works perfectly.
