### ISSUE TITLE
I have also face this problem. Please help me to get rid of this.

### ISSUE THREAD

**Issue by ramy-hue** [kiteco/issue-tracker#288]
I have also face this problem. Please help me to get rid of this.
![Capture](https://user-images.githubusercontent.com/28803635/86494109-ccaeb580-bd95-11ea-9c49-63d6a44d2536.PNG)

_Originally posted by @reshma-ahmed58 in https://github.com/kiteco/issue-tracker/issues/118#issuecomment-653659302_

**Comment by its-dhung** [comment]
Duplicate of #118
