### ISSUE TITLE
Reset Password flow is stuck in a loop

### ISSUE THREAD

**Issue by zhoffm** [kiteco/issue-tracker#290]
I've been sent a link to reset my password (which includes my email and a token) but when I click on it, I'm redirected back to https://www.kite.com/reset-password rather than letting me set a new password. I've tried several different browsers, networks, and have cleared both my browser cache and DNS cache. This seems to be the same issue as #208, for reference. Any help would be appreciated!

**Comment by its-dhung** [comment]
This should be fixed now.
