### ISSUE TITLE
Vim crash whenever open python files

### ISSUE THREAD

**Issue by thanhph111** [kiteco/issue-tracker#291]
**Description**
Vim application crash when open a `.py` file, only after install Vim plugin from Kite. I did:

- [x] Reinstall Kite
- [x] Reinstall Vim plugin
- [x] Reinstall Vim

I also tried reduce settings in `_vimrc` file to identify the error.
My Atom on same computer and my Vim on another computer work fine with these configuration.

**Required infomation**
[Application logs](https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/195459/kite_local/client.log.2020-07-25_11-52-53-AM.bak.gz)
[Resource usage](https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/195459/kite_local/1595652816411966900/capture.gz)

**Screenshots**
![Open a new file](https://user-images.githubusercontent.com/60842560/88448808-8d8ef400-ce6b-11ea-9b92-c6c723a333cf.png)
![Open an existing file](https://user-images.githubusercontent.com/60842560/88448816-9a134c80-ce6b-11ea-966f-ea1d7d84f22f.png)

**Other information**
[`kite-vim.log`](https://gist.github.com/thanhph111/65b9f2b0eef7788ef1dec6ea2bc7b719)
[`_vimrc`](https://gist.github.com/thanhph111/df59ae4591157d889c0298ef8905d6d0)

**Comment by its-dhung** [comment]
@airblade it looks like there's any error parsing the Vim version of this specific machine. Mind taking a look?

**Comment by airblade** [comment]
@thanhph111 What are the first 5 or 6 lines of your `:version`?  I.e. up to but excluding the list of features.

**Comment by thanhph111** [comment]
@airblade Thank you for your response. Here is the output:

``` (shell)
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:19:27)
MS-Windows 32-bit console version
Compiled by mool@tororo
Huge version without GUI...
```

**Comment by airblade** [comment]
@thanhph111 Thanks for the info.  I hadn't seen a version string without a patches lines before.  Anyway, it's fixed now.
