### ISSUE TITLE
A small error occurred using PyCharm

### ISSUE THREAD

**Issue by lzkgbld** [kiteco/issue-tracker#292]
After I updated the version of PyCharm, Kited kept sending me an error:
Please close all running instances of PyCharm before uninstalling. Try again
He asked me to restart PyCharm. After I restarted PyCharm in accordance with his request, I clicked on the repair, and the software did not remind me of the error later. However, after I reopened PyCharm, the error was still shown by Kited.

**Comment by lzkgbld** [comment]
This is also true when using Visual Studio Code. No matter how you uninstall or reinstall it, an error will still be reported. Besides, when opening Visual Studio Code, you cannot see the kite icon...
You may need to restart Visual Studio Code after uninstalling for the changes to take effect.

**Comment by jansorg** [comment]
@lzkgbld Thanks for reporting this! 
Can you tell where this error was shown? A screenshot would help to understands what's going on here.
Did you try to uninstall the plugin?

**Comment by lzkgbld** [comment]
> @lzkgbld感谢您举报！
> 您能知道在哪里显示此错误吗？屏幕截图有助于了解此处发生的情况。
> 您是否尝试卸载了插件？

Thank you for your reply, I found the PyCharm right does not show a sign of kite, but the Code prompt functions or everything is normal, I can't see the kite in the Visual Studio Code the bottom right, but the Code prompt function is normal, but they do not like the docs if you kite running will leave you in the right software kite mark, but I didn't see.

**Comment by its-dhung** [comment]
@lzkgbld to help us understand your issue, please send us a screenshot of Kite's plugin manager. You can access it by opening kite://settings/plugins in your browser.

**Comment by lzkgbld** [comment]
After trying to uninstall the two software and reinstall it, I installed Kite again. Then I opened the two software again, opened Kite and installed the plugin. After installing, I rebooted the computer once and found no errors.

**Comment by lzkgbld** [comment]
Not open the software may be too long, which I developed these days when open the updated the two software, by the way, lead to kite plug-in failure, finally I try kite unload the plugin is invalid, finally I choose is to reinstall the software, and then put the kite again after installation, open again development tools, and then let the kite after installing plug-ins, make sure the installation is complete to restart the computer again and again to open the tools and kite found plug-in running all normal!
