### ISSUE TITLE
Kite Plugin Incompatible with Pycharm 2020.2

### ISSUE THREAD

**Issue by matquant14** [kiteco/issue-tracker#295]
The Kite Plugin is not compatible with the updated version of Pycharm 2020.2
![Untitled](https://user-images.githubusercontent.com/43152300/88876887-e05d0880-d1e9-11ea-8e93-6302b8102930.png)

**Comment by metalogical** [comment]
please update to the latest version of Kite, and uninstall/reinstall the PyCharm plugin

**Comment by matquant14** [comment]
i have the latest version and the plugin can no longer be found in the marketplace
![Untitled](https://user-images.githubusercontent.com/43152300/88879916-09cd6280-d1f1-11ea-8145-7d560b9587a3.png)

**Comment by metalogical** [comment]
The Kite plugin has never been published in the marketplace. You must uninstall/install it via the Kite app.

**Comment by matquant14** [comment]
I uninstalled/reinstalled it, just as you say and still does not to work.  There was a plugin available for previous versions of pycharm in the marketplace.

**Comment by metalogical** [comment]
1. What version of Kite are you running?
  * In the copilot, click the gear icon and scroll to the bottom to see the version.
  * You should be on 20200728.0, released two days ago (the version number looks slightly different depending on your OS).
2. What version of the Kite plugin for PyCharm is installed after you uninstalled/reinstalled via the Kite plugin manager?
  * Previously, it looks like you were on 1.5.7 (based on the screenshot).
  * If the Kite version is 20200728.0, it should upgrade you to Kite for PyCharm version 1.6.7.

**Comment by matquant14** [comment]
got it working now
