### ISSUE TITLE
Access denied when sending log file, please delete the file if you can

### ISSUE THREAD

**Issue by niloct** [kiteco/issue-tracker#296]
Sorry for the naive question, but I've been experiencing `Kite: indexing` for the last 40min and in eagerness I've created a log file clicking on the interface blue button.

Then, it's here https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/31936/kite_local/client.log.2020-07-30_09-29-59-PM.bak.gz but I can't access it (Error: access denied) ? Even though I've posted with my AWS account ?

I didn't understand why I can't access my file.

Anyway, please delete the file if you can. Kite is still indexing but in some files it started working (neovim editor).

Thanks.

**Comment by metalogical** [comment]
log files are automatically deleted from our server after 60 days, but I deleted this manually for you
