### ISSUE TITLE
Kite android app turns completely black

### ISSUE THREAD

**Issue by utkarshchauha619** [kiteco/issue-tracker#297]
Found an issue where the whole interface turns completely black,

Consistent, screen recording attached.

Steps to repro:
1. Select any stock.
2. Scroll to the bottom.
3. Scroll up in order to close it and immediately press the back button.

![KiteBlack](https://user-images.githubusercontent.com/69034018/89016611-9f263f00-d336-11ea-8dcf-b7c9a864a945.gif)

**Comment by its-dhung** [comment]
This is the wrong Kite.

**Comment by utkarshchauha619** [comment]
Oh my god I'm such an idiot.. my apologies.
