### ISSUE TITLE
Kite is ready but no index

### ISSUE THREAD

**Issue by Caixiaomeng** [kiteco/issue-tracker#298]
What does this mean?How can i change the state to "indexing"?

**Comment by its-dhung** [comment]
There are [some directories that Kite ignores](https://help.kite.com/article/97-adding-libraries-from-pythonpath-to-the-kite-index) for privacy reasons. It's likely you are coding in one those directories.

If this isn't the case, please re-open this issue with:
1. The full path of the directory you are coding in.
2. Your Kite logs.

**Comment by gi3265** [comment]
I have the same problem too and my working directory doesn't include 'Appdata/'. Also i don't know how to print out 'Kite logs'...
Right now I'm working the ipynb file which is currently located at my other laptop. I'm reaching the file via OneDrive.
Would that be a reason for this problem?
