### ISSUE TITLE
JupyterLab plugin installation issue

### ISSUE THREAD

**Issue by grodriguece** [kiteco/issue-tracker#299]
**Describe the bug**
After trying to install the following message is displayed:

(base) PS C:\WINDOWS\system32> pip install jupyter-kite && jupyter labextension install @kiteco/jupyterlab-kite

At line:1 char:26
+ pip install jupyter-kite && jupyter labextension install @kiteco/jupy ...
+                          ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

**Comment by its-dhung** [comment]
Try running 2 commands:

```
pip install jupyter-kite
```

When that's done,

```
jupyter labextension install @kiteco/jupyterlab-kite
```

**Comment by its-dhung** [comment]
Edit: Make sure you've included `""` around `@kiteco/jupyterlab-kite` if you're using Windows PowerShell.

**Comment by grodriguece** [comment]
thanks
