### ISSUE TITLE
Kite: not running (on jupyterLab)

### ISSUE THREAD

**Issue by Jacques2101** [kiteco/issue-tracker#301]
<img width="693" alt="Capture d’écran 2020-08-04 à 19 11 56" src="https://user-images.githubusercontent.com/49912455/89324026-e427d980-d686-11ea-9fcd-1cdea65cfae2.png">

Hi I installed Kite for jupyterlab and nothing happens inside jupyterlab except the message (cf. screenshot) in the bottom bar. 
I am on macOS 

**pip list :** 
Package                   Version
------------------------- -------------------
appnope                   0.1.0
astroid                   2.4.2
attrs                     19.3.0
autopep8                  1.5.3
backcall                  0.2.0
beautifulsoup4            4.9.1
bleach                    3.1.5
brotlipy                  0.7.0
certifi                   2020.6.20
cffi                      1.14.0
chardet                   3.0.4
click                     7.1.2
cryptography              2.9.2
cycler                    0.10.0
DBnomics                  1.2.0
decorator                 4.4.2
defusedxml                0.6.0
entrypoints               0.3
ffn                       0.3.4
flake8                    3.8.3
future                    0.18.2
hmmlearn                  0.2.3
hmmviz                    0.0.7
idna                      2.10
importlib-metadata        1.7.0
inflection                0.3.1
ipykernel                 5.3.4
ipython                   7.16.1
ipython-genutils          0.2.0
isort                     4.3.21
jedi                      0.17.2
Jinja2                    2.11.2
joblib                    0.16.0
json5                     0.9.5
jsonschema                3.2.0
jupyter-client            6.1.6
jupyter-core              4.6.3
jupyter-kite              1.0.0
jupyter-lsp               0.9.0
jupyterlab                2.2.2
jupyterlab-code-formatter 1.3.5
jupyterlab-server         1.2.0
kiwisolver                1.2.0
lazy-object-proxy         1.4.3
lxml                      4.5.2
MarkupSafe                1.1.1
matplotlib                3.2.2
mccabe                    0.6.1
mistune                   0.8.4
mkl-fft                   1.1.0
mkl-random                1.1.1
mkl-service               2.3.0
more-itertools            8.4.0
multitasking              0.0.9
nbconvert                 5.6.1
nbformat                  5.0.7
nltk                      3.5
notebook                  6.0.3
numpy                     1.19.1
packaging                 20.4
pandas                    1.0.5
pandas-datareader         0.9.0
pandas-profiling          1.4.1
pandaSDMX                 1.0.1
pandocfilters             1.4.2
parso                     0.7.0
patsy                     0.5.1
pexpect                   4.8.0
pickleshare               0.7.5
pip                       20.1.1
plotly                    4.9.0
pluggy                    0.13.1
prometheus-client         0.8.0
prompt-toolkit            3.0.5
ptyprocess                0.6.0
pyarrow                   0.15.1
pycodestyle               2.6.0
pycparser                 2.20
pydantic                  1.5.1
pydocstyle                5.0.2
pyflakes                  2.2.0
Pygments                  2.6.1
pylint                    2.5.3
pyOpenSSL                 19.1.0
pyparsing                 2.4.7
pyrsistent                0.16.0
PySocks                   1.7.1
python-dateutil           2.8.1
python-jsonrpc-server     0.3.4
python-language-server    0.34.1
pytz                      2020.1
pyzmq                     19.0.1
Quandl                    3.5.0
regex                     2020.7.14
requests                  2.24.0
requests-cache            0.5.2
retrying                  1.3.3
rope                      0.17.0
scikit-learn              0.23.1
scipy                     1.5.0
seaborn                   0.10.1
Send2Trash                1.5.0
setuptools                49.2.0.post20200714
six                       1.15.0
snowballstemmer           2.0.0
soupsieve                 2.0.1
statsmodels               0.11.1
tabulate                  0.8.7
terminado                 0.8.3
testpath                  0.4.4
threadpoolctl             2.1.0
toml                      0.10.1
tornado                   6.0.4
tqdm                      4.48.0
traitlets                 4.3.3
ujson                     1.35
urllib3                   1.25.9
wcwidth                   0.2.5
webencodings              0.5.1
wheel                     0.34.2
wrapt                     1.11.2
xlrd                      1.2.0
yapf                      0.30.0
yfinance                  0.1.54
zipp                      3.1.0

**Comment by its-dhung** [comment]
Hi @Jacques2101 can you confirm that you have the Kite Engine desktop application installed? If you don't, please download and install it from https://kite.com/download.

**Comment by Jacques2101** [comment]
<img width="638" alt="Capture d’écran 2020-08-04 à 19 29 07" src="https://user-images.githubusercontent.com/49912455/89325314-e723c980-d688-11ea-99a8-50103450ba49.png">


Yes I did !

**Comment by its-dhung** [comment]
This may be caused by a conflict with the `jupyterlab-lsp` plugin. Can you try disabling that extension for the time being and see if the Kite plugin works?

**Comment by Jacques2101** [comment]
yes. It works. 
Thanks for your help

**Comment by phuang07** [comment]
I have the jupter desktop installed.
I don't have the `jupyterlab-lsp` plugin installed, but I am still not able to get kite working with jupyterLab. 


Package                           Version
--------------------------------- ---------
argon2-cffi                       20.1.0
attrs                             19.3.0
backcall                          0.2.0
beautifulsoup4                    4.9.1
bleach                            3.1.5
certifi                           2020.6.20
cffi                              1.14.1
chardet                           3.0.4
cobble                            0.1.3
cycler                            0.10.0
DateTime                          4.3
decorator                         4.4.2
defusedxml                        0.6.0
entrypoints                       0.3
gmpy2                             2.0.8
htmlmin                           0.1.12
idna                              2.10
ipykernel                         5.3.4
ipython                           7.17.0
ipython-genutils                  0.2.0
jedi                              0.17.2
Jinja2                            2.11.2
json5                             0.9.5
jsonschema                        3.2.0
jupyter-client                    6.1.6
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.6.3
jupyter-highlight-selected-word   0.2.0
jupyter-kite                      1.0.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        2.2.2
jupyterlab-server                 1.2.0
kiwisolver                        1.2.0
lxml                              4.5.2
mammoth                           1.4.10
MarkupSafe                        1.1.1
matplotlib                        3.3.0
mistune                           0.8.4
nbconvert                         5.6.1
nbformat                          5.0.7
networkx                          2.4
notebook                          6.1.1
numpy                             1.19.1
packaging                         20.4
pandocfilters                     1.4.2
parso                             0.7.1
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            7.2.0
pip                               20.2.1
prometheus-client                 0.8.0
prompt-toolkit                    3.0.5
ptyprocess                        0.6.0
pycparser                         2.20
Pygments                          2.6.1
pyparsing                         2.4.7
pyrsistent                        0.16.0
python-dateutil                   2.8.1
python-slugify                    4.0.1
pytz                              2020.1
PyYAML                            5.3.1
pyzmq                             19.0.2
requests                          2.24.0
Send2Trash                        1.5.0
setuptools                        47.1.1
six                               1.15.0
soupsieve                         2.0.1
termcolor                         1.1.0
terminado                         0.8.3
testpath                          0.4.4
text-unidecode                    1.3
tornado                           6.0.4
traitlets                         4.3.3
urllib3                           1.25.10
wcwidth                           0.2.5
webencodings                      0.5.1
wheel                             0.34.2
zope.interface                    5.1.0

**Comment by adamsmith** [comment]
@phuang07 Please open a separate issue and include details about whether you have the Kite desktop app installed, and what version of JupyterLab you have.
