### ISSUE TITLE
Kite not showing up in Jupyterlab

### ISSUE THREAD

**Issue by KrishnanS2006** [kiteco/issue-tracker#302]
I am trying out the new Kite for JupyterLab. I am using Windows 10 Version 1909. I received no errors when installing jupyterlab 2.2.2 or the kite extensions from [Kite Link](https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin?utm_campaign=203&utm_content=2067&utm_medium=email&utm_source=customerio). Here is my pip list:
```
Package           Version
----------------- ---------
appdirs           1.4.4
attrs             19.3.0
backcall          0.2.0
bleach            3.1.5
bottle            0.12.18
certifi           2020.6.20
cffi              1.14.0
chardet           3.0.4
click             7.1.2
colorama          0.4.3
decorator         4.4.2
defusedxml        0.6.0
distlib           0.3.0
entrypoints       0.3
filelock          3.0.12
Flask             1.1.2
Flask-SQLAlchemy  2.4.4
greenlet          0.4.16
idna              2.10
ipykernel         5.3.1
ipython           7.16.1
ipython-genutils  0.2.0
itsdangerous      1.1.0
jedi              0.17.1
Jinja2            2.11.2
json5             0.9.5
jsonschema        3.2.0
jupyter-client    6.1.5
jupyter-core      4.6.3
jupyter-kite      1.0.0
jupyterlab        2.2.2
jupyterlab-server 1.2.0
MarkupSafe        1.1.1
mistune           0.8.4
nbconvert         5.6.1
nbformat          5.0.7
notebook          6.0.3
numpy             1.19.1
packaging         20.4
pandocfilters     1.4.2
parso             0.7.0
pickleshare       0.7.5
pip               20.1.1
prometheus-client 0.8.0
prompt-toolkit    3.0.5
py2exe            0.9.2.2
pycparser         2.20
Pygments          2.6.1
pyparsing         2.4.7
pyrsistent        0.16.0
python-dateutil   2.8.1
pywin32           228
pywinpty          0.5.7
pyzmq             19.0.1
requests          2.24.0
Send2Trash        1.5.0
setuptools        47.1.0
six               1.15.0
SQLAlchemy        1.3.18
terminado         0.8.3
testpath          0.4.4
tornado           6.0.4
traitlets         4.3.3
urllib3           1.25.9
virtualenv        20.0.25
wcwidth           0.2.5
webencodings      0.5.1
Werkzeug          1.0.1
zope.event        4.4
zope.interface    5.1.0
WARNING: You are using pip version 20.1.1; however, version 20.2 is available.
You should consider upgrading via the 'C:\Users\krish\AppData\Local\Programs\Python\Python38-32\python.exe -m pip install --upgrade pip' command.
```

**Comment by its-dhung** [comment]
Can you ensure that you have the Kite Engine desktop app installed and that it's running? If you don't have it installed, you can download it from https://kite.com/download.

**Comment by KrishnanS2006** [comment]
I also have Kite Desktop Installed: 
![Image](https://user-images.githubusercontent.com/62958782/89325438-c8a4da80-d656-11ea-9612-15f79a85ab02.png)

**Comment by KrishnanS2006** [comment]
Another question, after I have installed Kite for JupyterLab, will there be a Kite icon on the bottom-right (like other editors)? That is an easy way to check if Kite is working or not. Here is my jupyterlab: 
![Image](https://user-images.githubusercontent.com/62958782/89325717-2fc28f00-d657-11ea-9d35-7d43ab15f402.png). As you can see, there is no icon. There are also no completions showing up when I type code.

**Comment by its-dhung** [comment]
Can you share the contents of your browser's JavaScript console in developer tools? When you refresh the page, do you see any lines that look like this?

![image](https://user-images.githubusercontent.com/3752225/89325782-27aa2580-d63e-11ea-8a05-83e51f454a73.png)

**Comment by KrishnanS2006** [comment]
I don't see any lines like you mentioned, but I do see some errors. 
![My Entire Screen](https://user-images.githubusercontent.com/62958782/89325951-8cbe4500-d657-11ea-8356-22993e337e4f.png)

**Comment by phuang07** [comment]
Also not able to get kite working with Jupyterlab. I don't see any of the LSP in the console.

**Comment by its-dhung** [comment]
Can you confirm that after you installed Kite, you restarted the `jupyter lab` process?

**Comment by phuang07** [comment]
Just restart, but still not working.

**Comment by its-dhung** [comment]
@phuang07 @KrishnanS2006 if it still doesn't work after restarting, please share the output of `jupyter labextension list`.

**Comment by KrishnanS2006** [comment]
Same, I restarted jupyter lab. I had the Kite Desktop App for over 3 months now.
![Kite App Open While Restarting JupyterLab](https://user-images.githubusercontent.com/62958782/89328273-22a79f00-d65b-11ea-8b58-6862997510c5.png)

**Comment by phuang07** [comment]
root@c50f6c2d544f:/src# jupyter labextension list
JupyterLab v2.2.2
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.0.0  enabled  OK
root@c50f6c2d544f:/src#



![image](https://user-images.githubusercontent.com/353542/89328253-16bbdd00-d65b-11ea-9e30-926e0e72b92c.png)

**Comment by KrishnanS2006** [comment]
![image](https://user-images.githubusercontent.com/62958782/89328380-4f5bb680-d65b-11ea-8e5f-a7e49e9d5421.png)

**Comment by phuang07** [comment]
Ok. I think I get some more details here after a complete restart.

![image](https://user-images.githubusercontent.com/353542/89331790-55a06180-d660-11ea-8a8c-3a5160281448.png)

**Comment by ryantberg** [comment]
@phuang07 It looks like you may be running JupyterLab as root, but have Kite Desktop installed as another user. If that's the case, could you run JupyterLab as the user that installed Kite Desktop and see if that fixes the issue?

**Comment by phuang07** [comment]
@ryantberg I cann't. I am running JupyterLab in a docker container.

**Comment by ryantberg** [comment]
@phuang07 Unfortunately, running Kite for JupyterLab in a container separately from Kite Desktop is not supported.

**Comment by its-dhung** [comment]
@KrishnanS2006 are you running JupyterLab from a Docker container as well?

**Comment by ryantberg** [comment]
@KrishnanS2006 can you share the output of `jupyter kernelspec list`? I think this might be an issue related to having multiple kernels installed

**Comment by KrishnanS2006** [comment]
I am not running JupyterLab from a docker. And yes, I do have 2 kernels, Python and Julia. Do I need to remove Julia from jupyterlab for Kite to work?

**Comment by its-dhung** [comment]
@KrishnanS2006 @phuang07 see #315 and #316

**Comment by KrishnanS2006** [comment]
Can you help me with one more thing? How do you remove a kernel from jupyterlab?

**Comment by ryantberg** [comment]
@KrishnanS2006 you should be able to remove kernels with the command `jupyter kernelspec remove <kernel_name>`, where `<kernel_name>` is the name of the kernel you wish to remove, as shown by `jupyter kernelspec list`
