### ISSUE TITLE
Cannot Install Jupyterkab-Kite

### ISSUE THREAD

**Issue by JoshuaYoungYang** [kiteco/issue-tracker#303]
**Required Information**
Cannot Install Jupyterkab-Kite
Running Anaconda, JupyterLab 2.2.2, Jupyter Notebook 6.1.1
Kite Desktop App is installed and running

**Describe the bug**
Your OS: Windows 10

The error you received when trying to install the plugin from the command line

- Cannot open C:\tools\Anaconda3\Scripts\jupyter-labextension-script.py

(This file doesn't appear to exist in the file location specified although I don't know how to restore it)

The output of pip list
Package                       Version
----------------------------- -------------------
anaconda-client               1.7.2
anaconda-navigator            1.9.12
argon2-cffi                   20.1.0
attrs                         19.3.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.1
backports.tempfile            1.0
backports.weakref             1.0.post1
beautifulsoup4                4.9.1
bleach                        3.1.5
brotlipy                      0.7.0
certifi                       2020.6.20
cffi                          1.14.0
chardet                       3.0.4
click                         7.1.2
clyent                        1.2.2
colorama                      0.4.3
conda                         4.8.3
conda-build                   3.18.11
conda-package-handling        1.7.0
conda-verify                  3.4.2
configparser                  5.0.0
cryptography                  2.9.2
decorator                     4.4.2
defusedxml                    0.6.0
entrypoints                   0.3
filelock                      3.0.12
future                        0.18.2
glob2                         0.7
idna                          2.10
importlib-metadata            1.7.0
ipykernel                     5.3.4
ipython                       7.17.0
ipython-genutils              0.2.0
jedi                          0.17.2
Jinja2                        2.11.2
joblib                        0.16.0
json5                         0.9.4
jsonschema                    3.2.0
jupyter-client                6.1.6
jupyter-core                  4.6.3
jupyter-kite                  1.0.0
jupyterlab                    2.2.2
jupyterlab-server             1.2.0
libarchive-c                  2.9
MarkupSafe                    1.1.1
menuinst                      1.4.16
mistune                       0.8.4
mkl-fft                       1.1.0
mkl-random                    1.1.1
mkl-service                   2.3.0
navigator-updater             0.2.1
nbconvert                     5.6.1
nbformat                      5.0.7
notebook                      6.1.1
numpy                         1.18.1
olefile                       0.46
packaging                     20.4
pandas                        1.0.1
pandocfilters                 1.4.2
parso                         0.7.1
pickleshare                   0.7.5
Pillow                        7.2.0
pip                           20.1.1
pkginfo                       1.5.0.1
prometheus-client             0.8.0
prompt-toolkit                3.0.5
psutil                        5.7.0
pycosat                       0.6.3
pycparser                     2.20
Pygments                      2.6.1
pyodbc                        4.0.0-unsupported
pyOpenSSL                     19.1.0
pyparsing                     2.4.7
pyrsistent                    0.16.0
PySocks                       1.7.1
python-dateutil               2.8.1
pytz                          2020.1
pywin32                       227
pywinpty                      0.5.7
PyYAML                        5.3.1
pyzmq                         19.0.2
QtPy                          1.9.0
requests                      2.24.0
ruamel-yaml                   0.15.87
scikit-learn                  0.22.1
scipy                         1.5.0
Send2Trash                    1.5.0
setuptools                    49.2.0.post20200714
six                           1.15.0
soupsieve                     2.0.1
terminado                     0.8.3
testpath                      0.4.4
tornado                       6.0.4
tqdm                          4.47.0
traitlets                     4.3.3
urllib3                       1.25.9
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.34.2
win-inet-pton                 1.1.0
wincertstore                  0.2
xmltodict                     0.12.0
zipp                          3.1.0

**Comment by adamsmith** [comment]
Hi there, it looks like something may be amiss with your JLab environment. Could you try installing another JLab extension ([list here](https://github.com/topics/jupyterlab-extension)) to see if this is a Kite-specific issue?

I just did a Google search or two and came across [this potential solution](https://github.com/topics/jupyterlab-extension) but I'm not sure it that would resolve your issue or not.

**Comment by jaklaassen** [comment]
Hi Joshua, sorry you're having trouble. It looks like you might be having some package management issues, possibly related to the `jupyter` command-line program. I have a few more things you can try to debug. I'm not super familiar with the Windows setup so YMMV, but there are some things you can do to dig into potential install issues.

You can look at the command that runs when you run `jupyter`. The actual command depends on whether you're using CMD or PowerShell. See: https://www.shellhacks.com/windows-which-equivalent-cmd-powershell/.

On my setup, when I run `jupyter labextension install ...`, the `jupyter` command runs a new command `jupyter-labextension`. Yours should do the same, and you can find the file that runs for that command.

My file looks like this:
```
#!/opt/anaconda3/bin/python
# -*- coding: utf-8 -*-
import re
import sys

from jupyterlab.labextensions import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Yours will be different because of Windows, but I'd expect the body to look about the same.

**Comment by JoshuaYoungYang** [comment]
Thanks! I uninstalled JupyterLab through the command line instead of through Anaconda and reinstalled. It works now!
