### ISSUE TITLE
Kite not working in Jupyterlab notebook

### ISSUE THREAD

**Issue by FuriousGeorge19** [kiteco/issue-tracker#305]
Hi. Kite won't autocomplete in my jupyterlab notebook. I start typing and nothing happens. I have a Kite pro account, if that matters. email address is mirza2020@berkeley.edu

Kite says 'ready' at the bottom. I'll include a picture.

![Screen Shot 2020-08-04 at 3 37 58 PM](https://user-images.githubusercontent.com/58865121/89352222-7a98d280-d668-11ea-89e0-b7fe54f16c5e.png)

logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/288601/kite_local/client.log.2020-08-04_03-38-31-PM.bak.gz

OS: Catalina 10.15.5

Jupyter info:

jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.1.5
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.7
traitlets        : 4.3.3

**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

**Screenshots**

**Comment by its-dhung** [comment]
Try updating your JupyterLab to v2.2+ and then try again. Re-open if you're still having this issue.
