### ISSUE TITLE
Unable to use kite with jupyterlab

### ISSUE THREAD

**Issue by arush1947** [kiteco/issue-tracker#308]
Firstly, thank you for coming out with the kite plug in for jupyterlab. I have been eagerly waiting for it.

I am unable to use kite plugin features in Jupyterlab. Autocompletion and documentation are both unavailable. It appears to still be using native auto complete.
1. Jupyterlab version 2.2.2
2. Kite windows application is installed and running.
3. jupyterlab-lsp extension is not installed
4. kite plugin is installed.
5. OS is windows 10 pro

Please see the attached outputs from
1. Kite application logs
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/398912/kite_local/client.log.2020-08-04_05-12-51-PM.bak.gz

2. pip list
Document attached
[pip_list.txt](https://github.com/kiteco/issue-tracker/files/5025417/pip_list.txt)

3. jupyter labextensions list
Document is attached
[labexntesion_list.txt](https://github.com/kiteco/issue-tracker/files/5025418/labexntesion_list.txt)

**Comment by its-dhung** [comment]
2 questions:

1. Are you using JupyterLab inside a Docker container?
2. Do you have multiple kernels for different languages?

**Comment by lx12633036** [comment]
> 2 questions:
> 
> 1. Are you using JupyterLab inside a Docker container?
> 2. Do you have multiple kernels for different languages?

I have same problem !
And i only have one kernel,and i can't see kite icon in the bottom

**Comment by arush1947** [comment]
Hi Daniel,
1. Im not using docker
2. I have multiple python kernels installed

Sent via the Samsung Galaxy S20+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by its-dhung** [comment]
@arush1947 see #315
