### ISSUE TITLE
Jupyter lab plugin auto-complete does not work

### ISSUE THREAD

**Issue by matthew-e-thomas** [kiteco/issue-tracker#313]
I have the desktop Kite application installed (works fine for VSCode), but the new jupyter lab extension is not working. Not only does it not auto-complete, but now the native auto-complete feature doesn't work. I have generated logs here: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/185258/kite_local/client.log.2020-08-05_08-28-57-AM.bak.gz

It says "Kite: ready" at the bottom of the notebook as it should. The copilot feature on the desktop seems to recognize the notebook and lists my functions and variables, but nothing happens in the notebooks itself. 

I have restarted the computer.

**Comment by its-dhung** [comment]
What is the output of `pip list` and `jupyter labextension list`?

**Comment by matthew-e-thomas** [comment]
Pip list:

Package            Version
------------------ -------------------
appnope            0.1.0
attrs              19.3.0
backcall           0.2.0
bleach             3.1.5
blis               0.4.1
brotlipy           0.7.0
catalogue          1.0.0
certifi            2020.6.20
cffi               1.14.0
chardet            3.0.4
cryptography       2.9.2
cymem              2.0.3
decorator          4.4.2
defusedxml         0.6.0
en-core-web-sm     2.3.0
entrypoints        0.3
et-xmlfile         1.0.1
idna               2.10
importlib-metadata 1.7.0
ipykernel          5.3.4
ipython            7.16.1
ipython-genutils   0.2.0
jdcal              1.4.1
jedi               0.17.2
Jinja2             2.11.2
joblib             0.16.0
json5              0.9.5
jsonschema         3.2.0
jupyter-client     6.1.6
jupyter-core       4.6.3
jupyter-kite       1.0.0
jupyterlab         2.1.5
jupyterlab-server  1.2.0
MarkupSafe         1.1.1
mistune            0.8.4
mkl-fft            1.1.0
mkl-random         1.1.1
mkl-service        2.3.0
murmurhash         1.0.2
nbconvert          5.6.1
nbformat           5.0.7
notebook           6.0.3
numpy              1.19.1
openpyxl           3.0.3
packaging          20.4
pandas             1.0.3
pandocfilters      1.4.2
parso              0.7.0
pexpect            4.8.0
pickleshare        0.7.5
pip                20.1.1
plac               0.9.6
preshed            3.0.2
prometheus-client  0.8.0
prompt-toolkit     3.0.5
ptyprocess         0.6.0
pycparser          2.20
Pygments           2.6.1
pyOpenSSL          19.1.0
pyparsing          2.4.7
pyrsistent         0.16.0
PySocks            1.7.1
python-dateutil    2.8.1
pytz               2020.1
pyzmq              19.0.1
requests           2.24.0
scikit-learn       0.23.1
scipy              1.5.0
Send2Trash         1.5.0
setuptools         49.2.0.post20200714
six                1.15.0
spacy              2.3.0
spacy-lookups-data 0.3.0
srsly              1.0.2
terminado          0.8.3
testpath           0.4.4
thinc              7.4.1
threadpoolctl      2.1.0
tornado            6.0.4
tqdm               4.47.0
traitlets          4.3.3
urllib3            1.25.9
wasabi             0.6.0
wcwidth            0.2.5
webencodings       0.5.1
wheel              0.34.2
xlrd               1.2.0
zipp               3.1.0


jupyter labextension list:
JupyterLab v2.1.5
Known labextensions:
   app dir: /opt/anaconda3/envs/Ligilo/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.0.0  enabled  OK

**Comment by wiseyoungbuck** [comment]
You must use Jupyterlab 2.2.0 or above for the plugin to work.
You are currently on 2.1.5
