### ISSUE TITLE
WSL 2 Jupyter lab kite

### ISSUE THREAD

**Issue by Saketh-Chandra** [kiteco/issue-tracker#325]
Can we use Kite from wsl 2 jupyter lab **[@kiteco/jupyterlab-kite](https://github.com/kiteco/jupyterlab-kite)** ?

I install Jupyter lab, Node.js on WSL2- Ubuntu 20.04.1, jupyterlab-kite Extension and kite copilot on Windows 10 2004

**Comment by Saketh-Chandra** [comment]
**Sorry**, already the issue has opened #323

**Comment by lilyhappily** [comment]
I have the same problem, but I solved it as follows:
Install kite: https://github.com/kiteco/jupyterlab-kite. And then start the kite: `nohup ~/.local/share/kite/kited &`
In jupyter lab, kite intializing appears but not kite ready. When you write your code, the kite completion works in my jupyter lab.
![image](https://user-images.githubusercontent.com/39702814/99613522-aa6eb900-2a52-11eb-9bf2-35b294ad4d16.png)
