### ISSUE TITLE
unable to execute "jupyter labextension install "@kiteco/jupyterlab-kite""

### ISSUE THREAD

**Issue by JawwadSabir** [kiteco/issue-tracker#335]
I am running Jupyter notebook on Linux. I have kite running on Spyder. 
I followed the instructions on the website about installing Kite on Jupyter. I successfully installed Jupyter-Kite using:

_pip install jupyter-kite_

Then I ran the following command on terminal:

_jupyter labextension install "@kiteco/jupyterlab-kite_

I got the following error:

_An error occured.
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /tmp/jupyterlab-debug-k38qdpxb.log_

I then installed nodejs and tried it again and the following error popped up:

_Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-kpdkckzj.log_

when I run _jupyter labextension list_ I get:

_JupyterLab v1.2.6
Known labextensions:
   app dir: /home/jawwad/anaconda3/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.0.0  enabled  OK
Build recommended, please run `jupyter lab build`:
    @kiteco/jupyterlab-kite needs to be included in build_

and pip list shows following versions:

_jupyter                            1.0.0              
jupyter-client                     5.3.4              
jupyter-console                    6.1.0              
jupyter-core                       4.6.1              
jupyter-kite                       1.0.0              
jupyterlab                         1.2.6              
jupyterlab-server                  1.0.6_       

**Any clues to what I am doing wrong here?**

**Comment by its-dhung** [comment]
You need to install nodejs (and npm). You also need to upgrade your JupyterLab to v2.2 or later.

**Comment by alik604** [comment]
@its-dhung ok, whats the next step after that? 

ive had this issue for a few weeks...
