### ISSUE TITLE
Kite Plugin for JupyterLab: No Autocomplete Suggestions

### ISSUE THREAD

**Issue by uzair-suria** [kiteco/issue-tracker#337]
***Problem Description***
Bottom status bar shows "Kite: ready", but there are no suggestions from kite and the default <kbd>Tab</kbd> toggle of Jupyter for autocomplete suggestion no longer works.

---

***System Info***:
OS: Windows 10 (64-bit)
Browser: Firefox v79.0
Conda Version: 4.8.3
Number of Kernels in the Conda Environment: 1
Jupyter Version Info (running `jupyter --version`):
```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.15.0
ipykernel        : 5.3.0
jupyter client   : 6.1.3
jupyter lab      : 2.1.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```

***Logs***
[Applications Log](https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/fc913f30-22d0-4370-a477-8c015c43b4f6/kite_local/client.log.2020-08-08_06-45-01-PM.bak.gz)
***Screenshots***
![image](https://user-images.githubusercontent.com/65369471/89712025-93c2bb80-d9a7-11ea-92a6-6540171a1465.png)

Any help will be highly appreciated

Regards,
Uzair

**Comment by joshuajaharwood** [comment]
Exact same issue. External documentation window works but no autocompletion, as documented by OP.

OS: Arch Linux, kernel 5.7.12-arch1-1
conda list: https://pastebin.com/CC2twJ70

```
jupyter --version:
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.16.1
ipykernel        : 5.3.2
jupyter client   : 6.1.6
jupyter lab      : 2.1.5
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```

Logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/376824/kite_local/client.log.2020-08-09_08-24-42-PM.bak.gz

Let me know if there's any more information I can provide.
Thank you!

**Comment by its-dhung** [comment]
Please upgrade JupyterLab to v2.2 or later and try again.

**Comment by uzair-suria** [comment]
> 
> 
> Please upgrade JupyterLab to v2.2 or later and try again.

That solved the issue. Thanks!
