### ISSUE TITLE
Kite for JupyterLab install issue

### ISSUE THREAD

**Issue by elcee12** [kiteco/issue-tracker#341]
When I try to install Kite for Jupyter Notebook I face an issue.

Here kite states that I should leave the following information when I get trouble:
https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin

**Your OS:**
macOS Mojave
version 10.14.6 (18G6020)

**Whether or not you have the Kite desktop app installed**
Yes I have the Kite desktop app installed

**The error you received when trying to install the plugin from the command line**
An error occured.
ValueError: Please install nodejs >=10.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /var/folders/h7/crlb51fj7vs35hqnkth_r85w0000gp/T/jupyterlab-debug-0bohamt_.log

**The output of pip list**
Package                            Version
---------------------------------- -------------------
absl-py                            0.9.0
aiohttp                            3.6.2
alabaster                          0.7.12
alpha-vantage                      2.2.0
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
appnope                            0.1.0
appscript                          1.1.1
archspec                           0.1.1
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astor                              0.8.1
astroid                            2.3.3
astropy                            4.0.1.post1
astunparse                         1.6.3
async-timeout                      3.0.1
atomicwrites                       1.4.0
attrs                              19.3.0
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bayesian-optimization              1.2.0
beautifulsoup4                     4.9.1
bitarray                           1.4.2
bkcharts                           0.2
bleach                             3.1.5
bokeh                              2.1.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
cachetools                         4.0.0
certifi                            2020.6.20
cffi                               1.14.1
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.5.0
clyent                             1.2.2
colorama                           0.4.3
conda                              4.8.4
conda-build                        3.18.11
conda-package-handling             1.7.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       2.9.2
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.10.1
dask                               2.11.0
decorator                          4.4.2
defusedxml                         0.6.0
dill                               0.3.2
distributed                        2.20.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
Flask                              1.1.2
fsspec                             0.7.4
future                             0.18.2
gast                               0.3.3
geographiclib                      1.50
geopy                              2.0.0
gevent                             20.6.2
glob2                              0.7
gmpy2                              2.0.8
google-auth                        1.11.2
google-auth-oauthlib               0.4.1
google-pasta                       0.1.8
googleapis-common-protos           1.52.0
greenlet                           0.4.16
grpcio                             1.27.2
gym                                0.17.0
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
hypothesis                         5.20.3
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 1.7.0
iniconfig                          0.0.0
ipykernel                          5.3.4
ipython                            7.16.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.16.0
Jinja2                             2.11.2
joblib                             0.16.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.6
jupyter-console                    6.1.0
jupyter-core                       4.6.3
jupyter-kite                       1.0.0
jupyterlab                         2.2.4
jupyterlab-server                  1.2.0
Keras                              2.4.3
Keras-Applications                 1.0.8
Keras-Preprocessing                1.1.0
keyring                            21.2.1
kiwisolver                         1.2.0
lazy-object-proxy                  1.5.0
libarchive-c                       2.9
llvmlite                           0.33.0+1.g022ab0f
locket                             0.2.0
lxml                               4.5.2
Markdown                           3.2.1
MarkupSafe                         1.1.1
matplotlib                         3.2.2
mccabe                             0.6.1
mistune                            0.8.4
mitdeeplearning                    0.1.2
mkl-fft                            1.1.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.4.0
mpmath                             1.1.0
msgpack                            1.0.0
multidict                          4.7.6
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.7
networkx                           2.4
nltk                               3.5
nose                               1.3.7
notebook                           6.1.1
numba                              0.50.1
numexpr                            2.7.1
numpy                              1.19.1
numpydoc                           1.1.0
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           3.0.4
opt-einsum                         3.2.0
packaging                          20.4
pandas                             1.1.0
pandocfilters                      1.4.2
parso                              0.8.0
partd                              1.1.0
path                               13.1.0
pathlib2                           2.3.5
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.2.1
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
promise                            2.3
prompt-toolkit                     3.0.5
protobuf                           3.11.3
psutil                             5.7.0
ptyprocess                         0.6.0
py                                 1.9.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycrypto                           2.6.1
pycurl                             7.43.0.5
pyflakes                           2.2.0
pyglet                             1.5.0
Pygments                           2.6.1
pylint                             2.4.4
pynput                             1.6.8
pyobjc-core                        6.2.2
pyobjc-framework-Cocoa             6.2.2
pyobjc-framework-Quartz            6.2.2
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyrsistent                         0.16.0
PySocks                            1.7.1
pytest                             6.0.1
pytest-arraydiff                   0.3
pytest-astropy                     0.8.0
pytest-astropy-header              0.1.2
pytest-doctestplus                 0.7.0
pytest-openfiles                   0.5.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.1
pytz                               2020.1
PyWavelets                         1.1.1
PyYAML                             5.3.1
pyzmq                              19.0.1
QtAwesome                          0.7.2
qtconsole                          4.7.5
QtPy                               1.9.0
regex                              2020.7.14
requests                           2.24.0
requests-oauthlib                  1.3.0
rope                               0.17.0
rsa                                4.0
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.23.1
scipy                              1.5.0
seaborn                            0.10.1
Send2Trash                         1.5.0
setuptools                         49.2.1.post20200807
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.0
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.3
spyder                             3.3.6
spyder-kernels                     0.5.2
SQLAlchemy                         1.3.18
statsmodels                        0.11.1
sympy                              1.6.1
tables                             3.6.1
tblib                              1.6.0
tensorboard                        2.2.2
tensorboard-plugin-wit             1.7.0
tensorflow                         2.2.0
tensorflow-datasets                3.2.1
tensorflow-estimator               2.2.0
tensorflow-metadata                0.22.2
termcolor                          1.1.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
toml                               0.10.1
toolz                              0.10.0
torch                              1.5.1
tornado                            6.0.4
tqdm                               4.48.2
traitlets                          4.3.3
typing-extensions                  3.7.4.2
unicodecsv                         0.14.1
urllib3                            1.25.9
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.34.2
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          2.0.1
xlrd                               1.2.0
XlsxWriter                         1.2.9
xlwings                            0.19.5
xlwt                               1.3.0
xmltodict                          0.12.0
yarl                               1.5.0
zict                               2.0.0
zipp                               3.1.0
zope.event                         4.4
zope.interface                     4.7.1

**The output of jupyter labextension list**
JupyterLab v2.2.4
No installed extensions

**Comment by its-dhung** [comment]
You need nodejs to install JupyterLab extensions.

**Comment by elcee12** [comment]
> You need nodejs to install JupyterLab extensions.

How do I do that?
