### ISSUE TITLE
Kite not working on pycharm 2020.2 

### ISSUE THREAD

**Issue by bartbv** [kiteco/issue-tracker#342]
Just at the startup of pycharm 2020.2 professional edition, the following message is displayed:
Plugin Error: Plugin "Kite" is incompatible (until build 201.SNAPSHOT < PY-202.6397.98).

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/369860/kite_local/client.log.2020-08-11_02-28-39-PM.bak.gz

**Comment by metalogical** [comment]
Please update to the latest version of Kite, and then uninstall/reinstall the PyCharm plugin via the Kite copilot. If you're still having issues, let us know.
