### ISSUE TITLE
Kite is not recognized by jupyterlab

### ISSUE THREAD

**Issue by erweiler** [kiteco/issue-tracker#343]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

**Screenshots**

**Comment by erweiler** [comment]
1. Windows 10
2. Kite desktop installed
3. No error during installation
4. PIP list is attached
5. Jupyterlab extension list is attached
[jupyter_labextension_list.txt](https://github.com/kiteco/issue-tracker/files/5057970/jupyter_labextension_list.txt)
[Pip_List.txt](https://github.com/kiteco/issue-tracker/files/5057971/Pip_List.txt)

)

**Comment by its-dhung** [comment]
You need to update JupyterLab to v2.2
