### ISSUE TITLE
Kite is incompatible with my Pycharm build?

### ISSUE THREAD

**Issue by CloneHub94** [kiteco/issue-tracker#347]
**Describe the bug**
When I try to install the kite plugin for Python on my version of Pycharm (Pycharm Community Edition 2019.2.1 x64
it doesn't work. I keep getting the error message trough the Plugin window:
"Incompatible: build must be 193.0 or higher (found 192.7142)"

Does anyone also have this issue or know how to solve it. Similar issues from the past seem to indicate that they were only solved with later updates from Pycharm?

**Screenshots**
![image](https://user-images.githubusercontent.com/37849398/90168081-e7187d80-dd9c-11ea-8954-a60624277072.png)

**Comment by pcamateur** [comment]
My PyCharm Community Edition 2020.2 Build #PC-202.63973.98
Error info: incompatible (until build 201.SNAPSHOT < PC-202.6397.98
![1](https://user-images.githubusercontent.com/40568878/91006599-6400ee00-e60c-11ea-86c2-7d14a9e2561f.png)
![2](https://user-images.githubusercontent.com/40568878/91006605-695e3880-e60c-11ea-8a4f-7a735e191da0.png)

**Comment by erezhazan1** [comment]
I have exactly the same issue! since the last update, it stopped being compatible

**Comment by jansorg** [comment]
The message `incompatible (until build 201.SNAPSHOT < PC-202.6397.98` says that the Kite plugin is too old. It seems that the automatic update did not work on the machine. Please terminate PyCharm, open Kite Copilot and reinstall the current version via `Settings > Plugins > PyCharm >` and clicking `Uninstall` and then `Install` again.
