### ISSUE TITLE
Cannot get Kite to run in JupyterLab

### ISSUE THREAD

**Issue by tensorway** [kiteco/issue-tracker#353]
I have tried to follow the tutorial and did

<code>  pip install jupyter-kite </code>
Which produces the following error:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable

Collecting jupyter-kite
  Using cached jupyter-kite-1.0.0.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7G4r7g/jupyter-kite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7G4r7g/jupyter-kite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z0mP5R
         cwd: /tmp/pip-install-7G4r7g/jupyter-kite/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7G4r7g/jupyter-kite/setup.py", line 10, in <module>
        (Path(__file__).parent / "py_src" / "jupyter_kite" / "_version.py").read_text(),
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

<code> pip3 install jupyter-kite </code> 
Solved the problem, but after I have enabled extensions in JupyterLab and enabled the kite extension it stil sayes 
"Kite: not running"

I have installed the desktop app.
I am using JupyterLab, Ubuntu 20.04, Firefox

<code> 
pip list
Package                       Version
----------------------------- ---------
absl-py                       0.9.0
astor                         0.8.1
backports.functools-lru-cache 1.5
backports.weakref             1.0.post1
beautifulsoup4                4.8.2
bleach                        1.5.0
cffi                          1.14.0
chardet                       3.0.4
enum34                        1.1.10
funcsigs                      1.0.2
futures                       3.3.0
gast                          0.3.3
grpcio                        1.30.0
html5lib                      0.9999999
lxml                          4.5.0
Markdown                      3.1.1
mock                          3.0.5
numpy                         1.16.6
pathlib                       1.0.1
pip                           20.2.2
protobuf                      3.12.2
pycparser                     2.20
setuptools                    44.1.1
six                           1.15.0
soupsieve                     1.9.5
tensorboard                   1.7.0
tensorflow                    1.7.1
termcolor                     1.1.0
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.34.2
</code>

and 

<code> jupyter labextension list </code>
JupyterLab v2.2.0
Known labextensions:
   app dir: /home/darijan/.local/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.0.0  enabled  OK

Uninstalled core extensions:
    @kiteco/jupyterlab-kite

I have tried to uninstall and install again, but nothing, relaunch JupyterLab and restart computer.

logs:
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/f6161a5c-0f08-475f-a1b2-4d1971dfeb8f/kite_local/client.log.2020-08-17_03-57-28-PM.bak.gz

**Comment by its-dhung** [comment]
It looks like JupyterLab thinks the Kite plugin is both installed and uninstalled. You may need to manually change your `build_config.json` for this to work. [This thread](https://discourse.jupyter.org/t/extension-shows-up-as-both-installed-and-uninstalled-and-doesnt-work/2688) may be relevant for you.
