### ISSUE TITLE
Free Student Pro Access Not Recognized

### ISSUE THREAD

**Issue by bbal20** [kiteco/issue-tracker#354]
**Required Information**
I am using PyCharm Pro 2020.2

**Describe the bug**
I initially created an account under my personal email address (kitopatterson@yahoo.com) and eventually lost my Kite Pro access. I was told by Brendan in Sales that I needed to create another account under my school email (kitop@mail.smu.edu) to take advantage of free student Pro access so I did. I've since logged out of co-pilot and logged in under my new "student" account but it doesn't seem to recognize me as a current student. There is still a message in co-pilot asking me to upgrade to Kite Pro. Please advise.

**Comment by juliukvi** [comment]
I clicked Activate License Now on this page, https://www.kite.com/pro/student/
Nothing happens, it just starts the Kite app, I am using a Kite account that is connected to my university. The bottom left badge still says Pro: Trialing.

**Comment by mdsung** [comment]
I have also the same issue. I have started trial with university account. I checked that there was university domain in https://github.com/kiteco/swot. However, Kite Pro didn't activate automatically.

**Comment by yangzehao** [comment]
I have the same issue. The name of my university is the University of Calgary. The email address is: username@ucalgary.ca.
The website is shown as: https://www.ucalgary.ca.
I used my university email address, Kite Pro didn't activate automatically. Any suggestion is appreciated. Thanks.

![Issue](https://user-images.githubusercontent.com/12593292/92624261-89386200-f284-11ea-897d-dcc333ebea79.jpg)

**Comment by loicfracheboud** [comment]
Hi guys,

As a member of a domain existing in https://github.com/kiteco/swot (@hes-so.ch) I couldn't log. My mail was refused and I had to use another one, hence getting only access to 30 days of pro

**Comment by TianzeWang** [comment]
Same issue here. I am using my university of Michigan email, and it doesn't work... Hoping someone could fix this issue, or they simply want us to pay money for the pro?

**Comment by shmkane** [comment]
Having the same issue

**Comment by TianzeWang** [comment]
Alright, folks I finally figured this out. @shmkane @yangzehao @loicfracheboud @bbal20 

1. Go to this link and enter your credential: https://alpha.kite.com/web/account/start-trial (I found this link under their doc websites (https://help.kite.com/article/135-free-university-licenses-for-kite-pro) 

2. Click on the huge "Active License Now" and you're all set.

God, why don't these people make life easier.

**Comment by shmkane** [comment]
> Alright, folks I finally figured this out. @shmkane @yangzehao @loicfracheboud @bbal20
> 
>     1. Go to this link and enter your credential: https://alpha.kite.com/web/account/start-trial (I found this link under their doc websites (https://help.kite.com/article/135-free-university-licenses-for-kite-pro)
> 
>     2. Click on the huge "Active License Now" and you're all set.
> 
> 
> God, why don't these people make life easier.

This worked for me! For some reason, https://www.kite.com/pro/student/ did NOT work but https://alpha.kite.com/web/account/start-trial worked.

**Comment by TianzeWang** [comment]
I guess the reason is there must be a way to enter your credential, but simply go to kite.com/pro/student/ you cannot find a place to do this.

**Comment by yangzehao** [comment]
Thanks @shmkane . It works for me now. However, when I posted my issue, this method didn't work.

**Comment by mdsung** [comment]
Thanks @shmkane. It works for me, too!!!

**Comment by iamcar** [comment]
@TianzeWang thank you so much!

**Comment by juliukvi** [comment]
@TianzeWang Thank you it worked! For others, if you don't get the option to write in your credentials, make sure to clear your cookies.

**Comment by alikasimoglu** [comment]
> Alright, folks I finally figured this out. @shmkane @yangzehao @loicfracheboud @bbal20
> 
> 1. Go to this link and enter your credential: https://alpha.kite.com/web/account/start-trial (I found this link under their doc websites (https://help.kite.com/article/135-free-university-licenses-for-kite-pro)
> 2. Click on the huge "Active License Now" and you're all set.
> 
> God, why don't these people make life easier.

Thank you.

**Comment by shmkane** [comment]
Is this resolved @bbal20 ? If so maybe it can be closed.

**Comment by brendanmcd96** [comment]
Hi all, thank you for reporting this issue and for finding a temporary fix! Our engineering team is actively working on a true "auto-start" of Kite Pro for education accounts.

**Comment by Reid00** [comment]
> > Alright, folks I finally figured this out. @shmkane @yangzehao @loicfracheboud @bbal20
> > ```
> > 1. Go to this link and enter your credential: https://alpha.kite.com/web/account/start-trial (I found this link under their doc websites (https://help.kite.com/article/135-free-university-licenses-for-kite-pro)
> > 
> > 2. Click on the huge "Active License Now" and you're all set.
> > ```
> > 
> > 
> > God, why don't these people make life easier.
> 
> This worked for me! For some reason, https://www.kite.com/pro/student/ did NOT work but https://alpha.kite.com/web/account/start-trial worked.

God, have no idea why this not work for me, when i click the link https://alpha.kite.com/web/account/start-trial it redirect to https://www.kite.com/pro/?source=trial_expired to tell me has expired, it's terrible. I want to know is this ONLY ME redirected?

**Comment by henrycoding** [comment]
the same problem!

my email domain is  tju.edu.cn

and it tell me I'm in free plan now

thx!

**Comment by metalogical** [comment]
This issue was fixed. If you're still experiencing problems, please contact us directly at support@kite.com with your email address so that we can investigate your account specifically.

**Comment by codeC0DE** [comment]
> Alright, folks I finally figured this out. @shmkane @yangzehao @loicfracheboud @bbal20
> 
> 1. Go to this link and enter your credential: https://alpha.kite.com/web/account/start-trial (I found this link under their doc websites (https://help.kite.com/article/135-free-university-licenses-for-kite-pro)
> 2. Click on the huge "Active License Now" and you're all set.
> 
> God, why don't these people make life easier.

Still not working for me
