### ISSUE TITLE
stack trace in json package

### ISSUE THREAD

**Issue by mraad** [kiteco/issue-tracker#356]
region= release=] 2020/08/18 05:16:46.125292 jsonrpc2.go:57: offset overflows buffer
character offset out of bounds of line
github.com/kiteco/kiteco/kite-go/lsp/jsonrpc2.(*Request).Reply
	/tmp/build/140ee389/gopath/src/github.com/kiteco/kiteco/kite-go/lsp/jsonrpc2/jsonrpc2.go:57
github.com/kiteco/kiteco/kite-go/lsp.Server.Handle
	/tmp/build/140ee389/gopath/src/github.com/kiteco/kiteco/kite-go/lsp/server.go:141
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by its-dhung** [comment]
This has been fixed in a newer version.
