### ISSUE TITLE
kite status is not appeared

### ISSUE THREAD

**Issue by takaya0** [kiteco/issue-tracker#358]
My problem(Python 3.8.5, from pyenv)
Kite and Jupyter-kite are installed in my computer.
However kite "status"(such as Kite: indexing) is not appearing in my status bar.
<img width="1438" alt="スクリーンショット 2020-08-21 1 54 21" src="https://user-images.githubusercontent.com/33962896/90801813-579d3c80-e351-11ea-8c21-f6fe704b4a5c.png">

OS: Mac OS 10.15.6
Whether or not you have the Kite desktop app installed:
installed
pip list:
Package                Version
---------------------- ---------
aiohttp                3.6.2
alembic                1.4.2
amply                  0.1.2
appdirs                1.4.4
appnope                0.1.0
argon2-cffi            20.1.0
astroid                2.4.2
async-timeout          3.0.1
attrs                  19.3.0
autopep8               1.5.4
backcall               0.2.0
beautifulsoup4         4.9.1
bleach                 3.1.5
blessed                1.17.6
blessings              1.7
branca                 0.4.1
bs4                    0.0.1
cached-property        1.5.1
certifi                2020.6.20
cffi                   1.14.2
chainer                7.7.0
chainerrl              0.8.0
chardet                3.0.4
cliff                  3.4.0
cloudpickle            1.3.0
cmaes                  0.6.0
cmd2                   1.3.3
colorama               0.4.3
colorlog               4.2.1
cPython                0.0.6
cryptography           3.0
cycler                 0.10.0
Cython                 0.29.21
decorator              4.4.2
defusedxml             0.6.0
distlib                0.3.1
docutils               0.16
entrypoints            0.3
et-xmlfile             1.0.1
filelock               3.0.12
flake8                 3.8.3
folium                 0.11.0
future                 0.18.2
google-images-download 2.8.0
graphviz               0.14.1
greenlet               0.4.16
gym                    0.17.2
hopcroftkarp           1.2.5
idna                   2.10
inquirer               2.7.0
ipykernel              5.3.4
ipython                7.17.0
ipython-genutils       0.2.0
ipywidgets             7.5.1
isort                  5.4.2
japanize-matplotlib    1.1.2
jdcal                  1.4.1
jedi                   0.17.2
Jinja2                 2.11.2
joblib                 0.16.0
json5                  0.9.5
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.6
jupyter-console        6.1.0
jupyter-core           4.6.3
jupyter-kite           1.0.0
jupyter-lsp            0.9.1
jupyterlab             2.2.5
jupyterlab-server      1.2.0
kiwisolver             1.2.0
kmapper                1.4.0
lazy-object-proxy      1.4.3
llvmlite               0.34.0
Mako                   1.1.3
MarkupSafe             1.1.1
matplotlib             3.3.1
mccabe                 0.6.1
mecab-python3          1.0.1
mistune                0.8.4
mpmath                 1.1.0
msgpack                1.0.0
multidict              4.7.6
mypy                   0.782
mypy-extensions        0.4.3
nbconvert              5.6.1
nbformat               5.0.7
neovim                 0.3.1
networkx               2.4
notebook               6.1.3
numba                  0.51.0
numpy                  1.19.1
oauthlib               3.1.0
opencv-contrib-python  4.4.0.42
opencv-python          4.4.0.42
openpyxl               3.0.4
optuna                 2.0.0
packaging              20.4
pandas                 1.1.0
pandocfilters          1.4.2
parso                  0.7.1
pbr                    5.4.5
pconst                 1.0.0
pdfminer.six           20200726
persim                 0.1.3
pexpect                4.8.0
pfrl                   0.1.0
pickleshare            0.7.5
Pillow                 7.2.0
pip                    20.2.2
pip-review             1.1.0
pluggy                 0.13.1
prettytable            0.7.2
prometheus-client      0.8.0
prompt-toolkit         3.0.6
protobuf               3.13.0
ptyprocess             0.6.0
PuLP                   2.3
pycodestyle            2.6.0
pycparser              2.20
pycryptodome           3.9.8
pydocstyle             5.0.2
pydotplus              2.0.2
pyflakes               2.2.0
pyglet                 1.5.0
Pygments               2.6.1
pylint                 2.5.3
pyls-mypy              0.1.8
pymongo                3.11.0
pynvim                 0.4.1
pyocr                  0.7.2
pyparsing              2.4.7
PyPDF2                 1.26.0
pyperclip              1.8.0
pyrsistent             0.16.0
PySocks                1.7.1
python-dateutil        2.8.1
python-editor          1.0.4
python-jsonrpc-server  0.3.4
python-language-server 0.34.1
pytz                   2020.1
PyYAML                 5.3.1
pyzmq                  19.0.2
qtconsole              4.7.6
QtPy                   1.9.0
readchar               2.0.1
requests               2.24.0
requests-oauthlib      1.3.0
ripser                 0.5.3
rope                   0.17.0
scikit-learn           0.23.2
scikit-tda             0.0.3
scipy                  1.5.2
seaborn                0.10.1
selenium               3.141.0
Send2Trash             1.5.0
setuptools             49.6.0
six                    1.15.0
slackclient            2.8.0
snowballstemmer        2.0.0
sortedcontainers       2.2.2
soupsieve              2.0.1
SQLAlchemy             1.3.19
stevedore              3.2.0
sympy                  1.6.2
tadasets               0.0.4
tbb                    2019.0
termcolor              1.1.0
terminado              0.8.3
testpath               0.4.4
threadpoolctl          2.1.0
toml                   0.10.1
torch                  1.6.0
torchvision            0.7.0
torchviz               0.0.1
tornado                6.0.4
tqdm                   4.48.2
traitlets              4.3.3
tweepy                 3.9.0
typed-ast              1.4.1
typing-extensions      3.7.4.2
ujson                  1.35
umap-learn             0.4.6
urllib3                1.25.10
virtualenv             20.0.31
wcwidth                0.2.5
webencodings           0.5.1
widgetsnbextension     3.5.1
wordcloud              1.8.0
wrapt                  1.12.1
yapf                   0.30.0
yarl                   1.5.1
The output of jupyter labextension list:
JupyterLab v2.2.5
Known labextensions:
   app dir: /Users/takaya/.pyenv/versions/3.8.5/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.0.0  enabled  OK
        @krassowski/jupyterlab-lsp v1.1.0 disabled OK

Uninstalled core extensions:
    @kiteco/jupyterlab-kite
    @krassowski/jupyterlab-lsp

**Comment by its-dhung** [comment]
Hi @takaya0, this is the same as #346. Can you please follow the instructions in that thread to see if they help?

https://github.com/kiteco/issue-tracker/issues/346#issuecomment-674991069
https://github.com/kiteco/issue-tracker/issues/346#issuecomment-677955297
