### ISSUE TITLE
Sublime Text 3 freezes while typing Python code or comments

### ISSUE THREAD

**Issue by emenendez** [kiteco/issue-tracker#361]
From time to time, when typing Python code in Sublime Text 3 (latest version: build 3211), the entire editor freezes -- the UI does not respond, the cursor shows the spinning beach ball, and I have to force-quite Sublime Text.

I do not know what causes this, as it is intermittent, but when it starts happening, it happens very frequently. I don't even have a reason to suspect the KiteSublime plugin, except that once I uninstalled the plugin the issue stopped happening.

I ran into this once a number of months ago, and had to uninstall the KiteSublime plugin as it was too disruptive to my development. Eventually, I saw some changes to the plugin that suggested the issue was fixed, so I reinstalled the plugin and used it again for some time without issue.

I reproduced this yesterday using a fresh install of the plugin from the Copilot (version 0.5.6) and also with a fresh clone of the latest git repo (version 0.6.1). The freeze happened about 5 times in a row, while editing the same file, within a span of 10 minutes -- after that, I uninstalled the plugin again and haven't had a problem since.

Unfortunately, I did not capture logs at the time this happened.

I really enjoy using Kite -- it's a major productivity boost! Thanks for all the work you do on this!

**Comment by emenendez** [comment]
Thanks so much @its-dhung!

OS: Mac OS X 10.14.6
Kite copilot version: 0.20200813.0
Kite plugin version: reproduced on 0.5.6 and 0.6.1
Other sublime packages:
- Advanced CSV
- CodeMap
- DocBlockr 2020 (DoxyDoxygen powered)
- GenerateUUID
- Git
- GitGutter
- GotoDocumentation
- HexViewer
- Indent XML
- INI
- Jinja2
- Jira
- LSP
- MagicPython
- Package Control
- Pretty JSON
- Puppet
- PyCover
- PyDOC
- Pytest Snippets
- Python Breakpoints
- Sass
- SideBarEnhancements
- SQLTools
- StringEncode
- SublimeLinter
- SublimeLinter-flake8
- SublimeREPL
- Sublimerge 3
- SyncedSideBar
- TodoTxt Syntax
- Vagrant
- Worksheet

Unfortunately, I could not figure out any pattern which caused the freeze, and I've made significant changes to the file in question since then. However, I'll install the plugin again and follow up here with the file contents if the issue recurs.

Really appreciate your help!

**Comment by its-dhung** [comment]
My guess is that the combination of Kite and LSP may be causing the freezing. What happens if you disable your LSP plugin?

**Comment by emenendez** [comment]
Thanks @its-dhung! If this happens again I will try with and without the LSP plugin. Confirmed I got the auto-update to 20200825.

**Comment by its-dhung** [comment]
Closing this for now. @emenendez please re-open if you're experiencing the same issue.

**Comment by michaelsheidaei** [comment]
I am using windows 10 with sublime text 3.2.2 build 3211 and Kite Cloud and it keeps crashing, 3 times since last night

**Comment by its-dhung** [comment]
@michaelsheidaei:

1. What version of Kite were you using?
2. What other Sublime packages do you have installed?
