### ISSUE TITLE
 "Kite: not running" status shown even though Kite is running

### ISSUE THREAD

**Issue by shan3lei** [kiteco/issue-tracker#363]
kite works well on spyder.
but the jupterlab cann't work, on the bottom left showing "Kite: not running" (even though it does) .
browser's JavaScript console shows "Kite Status could not be fetched"
![image](https://user-images.githubusercontent.com/32256286/91319259-c31e5880-e7ee-11ea-9736-db980e686259.png)
how to solve it

**Comment by its-dhung** [comment]
Please update Kite's JupyterLab plugin with these 2 commands and try again:

```
pip install --upgrade jupyter-kite
jupyter labextension update @kiteco/jupyterlab-kite
```
