### ISSUE TITLE
Reset password: Broken link

### ISSUE THREAD

**Issue by rahuliyerkumar** [kiteco/issue-tracker#365]
After reinstallation of Kite, attempting to login to my pro account (based on institution) leads to kite sending a reset link to my password.
![Kite1](https://user-images.githubusercontent.com/65895061/91549892-f6b0ce00-e927-11ea-91e2-9e3797de216f.png)

The link directs me to a 404 page. 
![Kite2](https://user-images.githubusercontent.com/65895061/91549972-13e59c80-e928-11ea-99bb-1bb82e194886.png)

**Comment by jaklaassen** [comment]
Hi @rahuliyerkumar,

Sorry about that. Try resetting your password again, the link should work now. Thanks for the report!
