### ISSUE TITLE
Issue Regarding Kite Pro Trial and Clarification for Jupyter Notebooks

### ISSUE THREAD

**Issue by shibanib** [kiteco/issue-tracker#366]
## 1. I don't know how the trial has been activated for me, 

I don't know enough to be able to assess the pro features yet, I'd ideally like to take up the trial in a month or so. 
Anyway you can cancel my trial and resume it later Please?

## 2. Clarification : Does Kite only work with Jupyter Lab and not Jupyter Notebook? Or does it work with both?

Installed Jypter etc using Anaconda so 
Had to update Jupyter Lab via pip to get Kite extension to work. 
Works on Lab doesn't work on Notebook. 
I mean speicifcally the external instance of the notebook localhost/tree , outside of localhost/lab 

## 3. Spyder IDE  says kite not supported while its working in JupyterLab
First it said unsupported now it says Kite is ready ( no index) 
and doesn't work in the python console. works in .py file.

logs 

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/290011/kite_local/client.log.2020-08-29_12-56-04-PM.bak.gz

**Comment by its-dhung** [comment]
1. The easiest way to restart your trial is to create a new account with Kite. You can do so by logging out via Copilot settings, and then creating a new account in the login page.
2. Kite only works with JupyterLab.
3. Kite does not work in Spyder's console. It only works in the file editor.
