### ISSUE TITLE
failed to create lock file when installing  kite in Linux

### ISSUE THREAD

**Issue by zhihao-pku** [kiteco/issue-tracker#368]
(base) aaa@aaa-System-Product-Name:~/桌面$ bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"

This script will install Kite!

We hope you enjoy! If you run into any issues, please report them at https://github.com/kiteco/issue-tracker.

- The Kite Team

Press enter to continue...

Checking to see if all dependencies are installed....

Downloading /home/aaa/桌面/kite-installer binary using wget...
Running /home/aaa/桌面/kite-installer install 
[installer] failed to create lock file /home/aaa/.local/share/kite/kite-update.lock
ROLLBAR error failed to create kite-update lock file [install open /home/aaa/.local/share/kite/kite-update.lock: file exists Linux aaa-System-Product-Name 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
]
dropping rollbar event due to filtering

**Comment by jansorg** [comment]
@zhihao-pku This seems to be a stale lock file left from a previous install attempt.
Could you run this to remove it and to restart the installed?
```
rm -f /home/aaa/.local/share/kite/kite-update.lock
bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
```

**Comment by amm98d** [comment]
> @zhihao-pku This seems to be a stale lock file left from a previous install attempt.
> Could you run this to remove it and to restart the installed?
> 
> ```
> rm -f /home/aaa/.local/share/kite/kite-update.lock
> bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
> ```

Hi @jansorg !
I had the same issue, tried what you wrote up here, but didn't work, same error.

**Comment by jansorg** [comment]
@amm98d 
It's unclear what might be causing this. 
It might be permission problem. Are you able to manually create the file?
```
```

**Comment by amm98d** [comment]
Actually, my bad. I hadn't noticed at all and didn't replace the 'aaa' in the path with my own username :facepalm:. The command runs and it's downloading now. No errors.

You can close the issue.

Thanks a lot!

**Comment by jansorg** [comment]
Glad that it's working!
