### ISSUE TITLE
Kite package is not giving autocomplete in .py in Sublime Text 3

### ISSUE THREAD

**Issue by t3chbO1** [kiteco/issue-tracker#371]
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/459861/kite_local/client.log.2020-09-01_03-44-59-PM.bak.gz

I am using Sublime Text 3 
console logs -https://pastebin.pl/view/acc391d4

Basically, I installed the kite application from the website, installed the sublime plugin from the application, restarted sublime, and I'm still not getting auto complete like it shows in the example video. I have disabled anaconda's autocomplete. 

![image](https://user-images.githubusercontent.com/69769425/91899377-0eab8900-ec6b-11ea-9645-9f83e13357cb.png)

**Comment by its-dhung** [comment]
The Sublime console logs you provided don't seem to be loading. Please re-open this issue and provide your Sublime logs again if you're still experiencing this issue.
