### ISSUE TITLE
Kite status not running in jupyterlab while running in vscode

### ISSUE THREAD

**Issue by amirkaveh** [kiteco/issue-tracker#372]
I correctly installed the Kite engine and plugin for JupyterLab, but its status says "kite: not running" and it does not work. At the same time, Kite in VS Code works fine. 
I have provided application logs and screenshot of jupyterlab. Thanks for your time. 

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/124253/kite_local/client.log.2020-09-03_09-41-00-PM.bak.gz

![image](https://user-images.githubusercontent.com/20387401/92146163-8e358580-ee2e-11ea-89e7-e34fee2a9cb5.png)

**Comment by alexkowsik** [comment]
Same issue

**Comment by its-dhung** [comment]
Please update Kite's JupyterLab plugin with these 2 commands and try again:

```
pip install --upgrade jupyter-kite
jupyter labextension update @kiteco/jupyterlab-kite
```
