### ISSUE TITLE
Cannot install the extention

### ISSUE THREAD

**Issue by Dav1D1010** [kiteco/issue-tracker#379]
**Describe the bug**
Cannot install the extension for Jupyter Notebook
C:\WINDOWS\system32>jupyter labextension install "@kiteco/jupyterlab-kite"
Cannot open C:\ProgramData\Anaconda3\Scripts\jupyter-labextension-script.py

**Screenshots**
![cmd](https://user-images.githubusercontent.com/67216903/92323125-8158a200-f079-11ea-9496-b2c63675366c.png)

**Comment by vaish567** [comment]
Hey @Dav1D1010 ,
Can I resolve this issue?

**Comment by its-dhung** [comment]
This seems unrelated to Kite and appears to be something up with your installation/configuration of `conda` and JupyterLab. Since it's unrelated to Kite, I'm going to close this issue.
