### ISSUE TITLE
Kite: not running

### ISSUE THREAD

**Issue by marianafidalgo** [kiteco/issue-tracker#380]
Linux Mint Tara
Kite desktop app is installed
The output of pip list
![Screenshot from 2020-09-06 12-44-50](https://user-images.githubusercontent.com/32492467/92325017-112d2a80-f03f-11ea-8a08-01364a69f8a9.png)
![Screenshot from 2020-09-06 12-45-40](https://user-images.githubusercontent.com/32492467/92325018-125e5780-f03f-11ea-97f8-aae7b0db4586.png)
![Screenshot from 2020-09-06 12-45-52](https://user-images.githubusercontent.com/32492467/92325019-12f6ee00-f03f-11ea-93fe-b9149e37edfe.png)

The output of jupyter labextension list
![Screenshot from 2020-09-06 12-46-28](https://user-images.githubusercontent.com/32492467/92325020-15594800-f03f-11ea-866e-cad8853b1dc1.png)

**Describe the bug**
![Screenshot from 2020-09-06 12-43-53](https://user-images.githubusercontent.com/32492467/92325023-22763700-f03f-11ea-86f5-f67271d5cfec.png)
![image](https://user-images.githubusercontent.com/32492467/92325031-33bf4380-f03f-11ea-84bd-2f0fd6d0c7d7.png)

**Comment by RussellFeng** [comment]
we have same problem

**Comment by protea-ban** [comment]
we have same problem, my OS is windows 10.

**Comment by exorcisti** [comment]
we have same problem Mac os

**Comment by mparadis-crestron** [comment]
Same problem here 

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/477127/kite_local/client.log.2020-09-12_11-42-14-PM.bak.gz

**Comment by edzkite** [comment]
What's the output of `jupyter serverextension list`?

**Comment by Gavin-Hofer** [comment]
> What's the output of `jupyter serverextension list`?

I'm having the same issue.
The output for me is:

config dir: \<userpath\>\Anaconda3\etc\jupyter
    jupyter_kite enabled
    - Validating...
      jupyter_kite 1.1.0 ok
    jupyterlab enabled
    - Validating...
      jupyterlab 2.2.8 ok

**Comment by fhqjwyk** [comment]
I'm having the same problem.
OS win10
kite 1.2020.922.0
node 10.22.1
Python 3.8
jupyter-lab 2.2.8
nodejs 10.13.0
jupyter-kite 1.1.0
@kiteco/jupyterlab-kite 1.1.0
I install all dependencies and start jupyter lab, but the kite status is 'kite not running'.
In fact, the dependencies version is unimportant, it working when i try to reinstall kite.
Obviously there is an unknown problem between jupyter lab and installed kite.

**Comment by edzkite** [comment]
@Gavin-Hofer

Thanks. That looks fine. If you were to launch JupyterLab with `jupyter lab --debug`, and open a notebook file, what output does the terminal give you?

**Comment by edzkite** [comment]
@fhqjwyk 

Could you clarify what you mean by 

> In fact, the dependencies version is unimportant, it working when i try to reinstall kite.

**Comment by fhqjwyk** [comment]
> @fhqjwyk
> 
> Could you clarify what you mean by
> 
> > In fact, the dependencies version is unimportant, it working when i try to reinstall kite.

This ploblem need to uninstall kite engine and reinstall kite engine.

**Comment by Gavin-Hofer** [comment]
> @Gavin-Hofer
> 
> Thanks. That looks fine. If you were to launch JupyterLab with `jupyter lab --debug`, and open a notebook file, what output does the terminal give you?

I've attached the output of jupyter lab --debug to this text file
This is everything that shows up after enrtering the command,
Jupyterlab opens like normal, and it says "Kite: not running", like before.
[jupyterlab_debug.txt](https://github.com/kiteco/issue-tracker/files/5369346/jupyterlab_debug.txt)

**Comment by edzkite** [comment]
Thanks @Gavin-Hofer. I don't see anything immediately obvious from these logs. If you were to open up a notebook or Python file, and type, do you see any code completions? Does the status update at all?

**Comment by edzkite** [comment]
Hi all, I made an update that should fix some bugs in our status reporting, and make it easier to see potential errors. Please update with `jupyter labextension update @kiteco/jupyterlab-kite`.

**Comment by edzkite** [comment]
One of our users discovered that having an older version of the pip package `tornado` would cause the Kite extension to fail. Please try upgrading to the latest version (6.0.4).

**Comment by edzkite** [comment]
I'm pushed an update to `jupyter-kite` that will check for Tornado. Please upgrade to `jupyter-kite-1.2.0` when you have a chance.
