### ISSUE TITLE
Kite Plugin is not getting installed for Jupyter-lab

### ISSUE THREAD

**Issue by yyndsai** [kiteco/issue-tracker#381]
![image](https://user-images.githubusercontent.com/52864933/92411078-120bac80-f164-11ea-9c20-fa0e3d7efc60.png)
I have run the following commands in anaconda prompt:
1.)pip install jupyter-kite
2.)jupyter labextension install "@kiteco/jupyterlab-kite"
but the second command is not working.It's finishing the command like this:
(base) C:\Users\yynds>jupyter labextension install "@kiteco/jupyterlab-kite"
Building jupyterlab assets (build:prod:minimize)
|It's clearly shown in the photo attached

**Comment by its-dhung** [comment]
Do you mean that it just hangs and never prints more logs, including errors?
