### ISSUE TITLE
Problem in installing kite plugin for jupyter lab

### ISSUE THREAD

**Issue by yyndsai** [kiteco/issue-tracker#382]
1.)OS:WINDOWS10
2.)I have installed kite desktop version
3.)The error I received:
![image](https://user-images.githubusercontent.com/52864933/92411276-d2919000-f164-11ea-8b74-d08d8ba3fbbd.png)
It's just got stoped with this one line, I checked my jupyter also , it's not working
4.The output of jupyter labextension list:
JupyterLab v2.1.5
Known labextensions:
   app dir: C:\Users\yynds\anaconda3\share\jupyter\lab
        @kiteco/jupyterlab-kite v1.0.0 enabled  ok

**Comment by its-dhung** [comment]
You are using an old version of JupyterLab. Please upgrade to v2.2+ to use Kite.
