### ISSUE TITLE
"@kiteco/jupyterlab-kite" is not a valid NPM Package

### ISSUE THREAD

**Issue by johncaling40** [kiteco/issue-tracker#384]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [x] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.
I get error "@kiteco/jupyterlab-kite" is not a valid NPM Package

**Screenshots**

OS: Windows 10 
I have desktop app installed 
I get error `"@kiteco/jupyterlab-kite" is not a valid NPM Package`
pip list:
`altgraph                      0.17
appdirs                       1.4.4
argon2-cffi                   20.1.0
async-generator               1.10
attrs                         20.1.0
autopep8                      1.4.4
backcall                      0.2.0
beautifulsoup4                4.9.1
bleach                        3.1.5
bokeh                         2.2.1
bs4                           0.0.1
certifi                       2020.6.20
cffi                          1.14.2
chardet                       3.0.4
cloudmersive-virus-api-client 3.0.1
colorama                      0.4.3
cycler                        0.10.0
dearpygui                     0.1.1
decorator                     4.4.2
defusedxml                    0.6.0
distlib                       0.3.1
dj-database-url               0.5.0
Django                        2.2.14
django-allauth                0.39.1
django-countries              5.3.3
django-crispy-forms           1.7.2
django-debug-toolbar          1.10.1
django-heroku                 0.3.1
django-jazzmin                2.2.7
django-jobboard               0.1.0
entrypoints                   0.3
filelock                      3.0.12
fixit                         0.1.0
flake8                        3.8.3
future                        0.18.2
gitdb                         4.0.5
GitPython                     3.1.8
gunicorn                      20.0.4
idna                          2.8
importlib-metadata            1.7.0
ipykernel                     5.3.4
ipython                       7.18.1
ipython-genutils              0.2.0
ipywidgets                    7.5.1
jedi                          0.17.2
Jinja2                        2.11.2
json5                         0.9.5
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.7
jupyter-console               6.2.0
jupyter-core                  4.6.3
jupyter-kite                  1.0.0
jupyter-server                0.1.1
jupyterlab                    2.2.7
jupyterlab-pygments           0.1.1
jupyterlab-server             1.2.0
kiwisolver                    1.2.0
libcst                        0.3.10
MarkupSafe                    1.1.1
matplotlib                    3.3.1
mccabe                        0.6.1
mistune                       0.8.4
mypy-extensions               0.4.3
nbconvert                     5.6.1
nbformat                      5.0.7
notebook                      6.1.3
numpy                         1.19.1
oauthlib                      3.0.1
opencv-python                 4.4.0.42
packaging                     20.4
pandas                        1.1.1
pandocfilters                 1.4.2
parso                         0.7.1
pefile                        2019.4.18
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        7.2.0
pip                           20.2.2
pipenv                        2020.8.13
prometheus-client             0.8.0
prompt-toolkit                3.0.7
psycopg2                      2.8.5
ptyprocess                    0.6.0
pycodestyle                   2.6.0
pycparser                     2.20
pyflakes                      2.2.0
pygame                        1.9.6
Pygments                      2.6.1
pyinstaller                   4.0
pyinstaller-hooks-contrib     2020.7
pyparsing                     2.4.7
pyrsistent                    0.16.0
python-dateutil               2.8.1
python-decouple               3.1
python3-openid                3.1.0
pytz                          2018.5
pywin32                       228
pywin32-ctypes                0.2.0
pywinpty                      0.5.7
PyYAML                        5.3.1
pyzmq                         19.0.2
qtconsole                     4.7.7
QtPy                          1.9.0
requests                      2.21.0
requests-oauthlib             1.2.0
scipy                         1.5.2
seaborn                       0.11.0
Send2Trash                    1.5.0
setuptools                    47.1.0
six                           1.15.0
smmap                         3.0.4
soupsieve                     2.0.1
sqlparse                      0.2.4
stripe                        2.27.0
terminado                     0.8.3
testpath                      0.4.4
tornado                       6.0.4
traitlets                     5.0.2
typing-extensions             3.7.4.3
typing-inspect                0.6.0
urllib3                       1.24.2
virtualenv                    20.0.31
virtualenv-clone              0.5.4
virtualenvwrapper-win         1.2.6
voila                         0.1.23
wcwidth                       0.2.5
webencodings                  0.5.1
whitenoise                    5.2.0
widgetsnbextension            3.5.1
zipp                          3.1.0`
jupyter labextension list:
`JupyterLab v2.2.7
No installed extensions`

**Comment by HandleCoding** [comment]
I have exactly the same issue，maybe the version of npm or nodejs is incompatible

**Comment by its-dhung** [comment]
Can you share the full output of the error? Hard to tell without seeing your full error but [the dialog in this issue](https://github.com/jupyter-widgets/ipywidgets/issues/1982) may help.

**Comment by johncaling40** [comment]
I got it to work.
