### ISSUE TITLE
Kite not installing plug-ins for Jupyter Lab

### ISSUE THREAD

**Issue by AntonPietersen** [kiteco/issue-tracker#387]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

**Screenshots**

**pip install jupyter-kite** in conda cmd prompt install successfully.
**jupyter labextension install "@kiteco/jupyterlab-kite"**  in conda cmd prompt complains that the "The extension "@jupyter-widgets/jupyterlab-manager" is outdated."

I then did the following:
**conda install -c conda-forge ipywidgets** in conda cmd prompt which installed successfully.
**jupyter labextension install jupyterlab-drawio** in conda cmd prompt says "The extension "@jupyter-widgets/jupyterlab-manager" is outdated."

I have nodejs installed and I'm on Jupyter Lab version 2.2.6 and I'm running Windows10

pip list:

Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.1.post1
atomicwrites                       1.4.0
attrs                              20.1.0
autopep8                           1.5.4
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.9.1
bitarray                           1.5.3
bkcharts                           0.2
bleach                             3.1.5
bokeh                              2.2.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
certifi                            2020.6.20
cffi                               1.14.2
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.3
comtypes                           1.1.7
conda                              4.8.4
conda-build                        3.20.2
conda-package-handling             1.7.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
convertdate                        2.2.1
cryptography                       3.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.10.1
dask                               2.25.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.25.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.3
Flask                              1.1.2
fsspec                             0.8.0
future                             0.18.2
gevent                             20.6.2
glob2                              0.7
gmpy2                              2.0.8
greenlet                           0.4.16
h5py                               2.10.0
HeapDict                           1.0.1
holidays                           0.10.3
html5lib                           1.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 1.7.0
iniconfig                          0.0.0
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.18.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.4.2
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.14.1
Jinja2                             2.11.2
joblib                             0.16.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.6
jupyter-console                    6.2.0
jupyter-core                       4.6.3
jupyter-kite                       1.0.0
jupyterlab                         2.2.6
jupyterlab-server                  1.2.0
keyring                            21.4.0
kiwisolver                         1.2.0
korean-lunar-calendar              0.2.1
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.33.0+1.g022ab0f
locket                             0.2.0
lxml                               4.5.2
MarkupSafe                         1.1.1
matplotlib                         3.3.1
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.1.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.5.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.7
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.1
numba                              0.50.1
numexpr                            2.7.1
numpy                              1.19.1
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.5
packaging                          20.4
pandas                             1.1.1
pandocfilters                      1.4.2
paramiko                           2.7.2
parso                              0.5.2
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.2.2
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.7
psutil                             5.7.2
py                                 1.9.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycrypto                           2.6.1
pycurl                             7.43.0.5
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.6.1
pylint                             2.6.0
PyMeeus                            0.3.7
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyreadline                         2.1
pyrsistent                         0.16.0
PySocks                            1.7.1
pytest                             6.0.1
python-dateutil                    2.8.1
python-jsonrpc-server              0.3.4
python-language-server             0.31.7
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.1
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.6
QtPy                               1.9.0
QuantLib                           1.19
QuantLib-Python                    1.18
regex                              2020.7.14
requests                           2.24.0
rope                               0.17.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.23.2
scipy                              1.5.2
seaborn                            0.10.1
Send2Trash                         1.5.0
setuptools                         49.6.0.post20200814
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.0.1
spyder-kernels                     1.8.1
SQLAlchemy                         1.3.19
statsmodels                        0.11.1
sympy                              1.6.2
tables                             3.6.1
tblib                              1.7.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
toml                               0.10.1
toolz                              0.10.0
tornado                            6.0.4
tqdm                               4.48.2
traitlets                          4.3.3
typed-ast                          1.4.1
typing-extensions                  3.7.4.3
ujson                              3.1.0
unicodecsv                         0.14.1
urllib3                            1.25.10
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.3.3
xlwings                            0.20.5
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.1.0
zope.event                         4.4
zope.interface                     5.1.0

jupyter labextension list:

JupyterLab v2.2.6
Known labextensions:
   app dir: C:\Users\t115560\Anaconda3\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.1.0 enabled   X
        @kiteco/jupyterlab-kite v1.0.0 enabled  ok
        jupyterlab-drawio v0.7.0 enabled  ok

   The following extension are outdated:
        @jupyter-widgets/jupyterlab-manager

   Consider running "jupyter labextension update --all" to check for updates.

I have done "jupyter labextension update --all"  already.

Please assist.

Anton.

![image](https://user-images.githubusercontent.com/59766718/93001180-81e7b180-f52d-11ea-9322-5c64195d46b7.png)
![image](https://user-images.githubusercontent.com/59766718/93001269-223dd600-f52e-11ea-84b0-44370ca30537.png)

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/469119/kite_local/client.log.2020-09-12_07-24-40-PM.bak.gz

**Comment by TheOther-Guy** [comment]
i have exactly the same issue with the same versions and the status is Kite"not running"

**Comment by AntonPietersen** [comment]
such a pity as.  From what I have seen it's a great product and will even be willing to pay for it, if it works properly.

**Comment by its-dhung** [comment]
@AntonPietersen it appears from your screen shot that Kite says that it's ready within JupyterLab. Are you able to get completions from Kite inside JupyterLab?

Your issue with the `jupyterlab-manager` is unrelated to Kite.

**Comment by AntonPietersen** [comment]
Hi @its-dhung - you are correct and autocompletions are working 100% now. Had some issues initially with the setup but all is fine now.  Thank you.

**Comment by TheOther-Guy** [comment]
@AntonPietersen kindly share what you have to solve the issue?

**Comment by AntonPietersen** [comment]
Hi @TheOther-Guy, I must be honest I didn't do anything.  I was simply unaware of the fact that it said should say "Ready" which my KITE status were saying all along.
