### ISSUE TITLE
Unable to activate my free pro license using my email address from school

### ISSUE THREAD

**Issue by jdm1121** [kiteco/issue-tracker#392]
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/208641/kite_local/client.log.2020-09-16_04-46-24-PM.bak.gz

https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/208641/kite_local/1600289302683930000/capture.gz

Attached are the application logs and resource usage if you need them.

**Comment by brendanmcd96** [comment]
Linking this to #354
