### ISSUE TITLE
Free Pro for students

### ISSUE THREAD

**Issue by bartoszc** [kiteco/issue-tracker#395]
Hello Kite Team!

I am writing about Kite PRO for students. I am a student of the Polish WSEI university, which is listed in the repo (lib / domains / pl / lublin/wsei.txt), but after the end of the trial period I do not have access to Kite PRO

University website: https://rekrutacja.wsei.lublin.pl/en/

Can anything be done about this?

PS. The help form on your site does not work, I get a recaptcha error

**Comment by juliukvi** [comment]
Duplicate of #354
