### ISSUE TITLE
Kite function signature does not recognise the start of the docstring, but jumps to the function example

### ISSUE THREAD

**Issue by ryanscott-bas** [kiteco/issue-tracker#396]
**Describe the bug**
I am running Python 3.8 and Kite in Spyder 4.1.5.

In the console I am using a function that I've created, however, the function signature is skipping to the example in the docstring, rather than starting from the start (please see screenshots).

Kite Application log:
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/466430/kite_local/client.log.2020-09-18_12-35-59-PM.bak.gz

**Screenshots**
Screenshot of function signature in console:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/23171311/93596144-cb625180-f9b0-11ea-8cb4-a63c56f43619.png">

Screenshot of full function docstring:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/23171311/93593425-fd24e980-f9ab-11ea-9353-630c90032857.png">

Screenshot of function signature in the same module as the function:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/23171311/93596255-e9c84d00-f9b0-11ea-8884-86b3b95b11ef.png">

**Comment by its-dhung** [comment]
This function signature panel is actually not being provided by Kite, but rather from Spyder's builtin Jedi language server.
