### ISSUE TITLE
Kite for Jupyter-lab doesnt work [the extension doesnt even appear]

### ISSUE THREAD

**Issue by 303001069** [kiteco/issue-tracker#397]
Your OS
Windows 10 Pro

Whether or not you have the Kite desktop app installed
Yes

The error you received when trying to install the plugin from the command line
No error:
**********************************
**********************************
(base) PS C:\Users\GoogleTech> pip install jupyter-kite
>> jupyter labextension install "@kiteco/jupyterlab-kite"
>>
Requirement already satisfied: jupyter-kite in c:\users\googletech\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: setuptools in c:\users\googletech\anaconda3\lib\site-packages (from jupyter-kite) (49.6.0.post20200814)
Requirement already satisfied: notebook>=4.3.1 in c:\users\googletech\anaconda3\lib\site-packages (from jupyter-kite) (6.1.1)
Requirement already satisfied: terminado>=0.8.3 in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.8.3)
Requirement already satisfied: jinja2 in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (2.11.2)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (4.6.3)
Requirement already satisfied: ipython-genutils in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.2.0)
Requirement already satisfied: nbconvert in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.6.1)
Requirement already satisfied: Send2Trash in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (1.5.0)
Requirement already satisfied: prometheus-client in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.8.0)
Requirement already satisfied: nbformat in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.0.7)
Requirement already satisfied: ipykernel in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.3.4)
Requirement already satisfied: tornado>=5.0 in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.0.4)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.1.6)
Requirement already satisfied: argon2-cffi in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (20.1.0)
Requirement already satisfied: pyzmq>=17 in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (19.0.1)
Requirement already satisfied: traitlets>=4.2.1 in c:\users\googletech\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (4.3.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\googletech\anaconda3\lib\site-packages (from jinja2->notebook>=4.3.1->jupyter-kite) (1.1.1)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\googletech\anaconda3\lib\site-packages (from jupyter-core>=4.6.1->notebook>=4.3.1->jupyter-kite) (227)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\googletech\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.3)
Requirement already satisfied: testpath in c:\users\googletech\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.4.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\googletech\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.2)
Requirement already satisfied: pygments in c:\users\googletech\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (2.7.1)
Requirement already satisfied: bleach in c:\users\googletech\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (3.2.1)
Requirement already satisfied: defusedxml in c:\users\googletech\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.6.0)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\googletech\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.8.4)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\googletech\anaconda3\lib\site-packages (from nbformat->notebook>=4.3.1->jupyter-kite) (3.2.0)
Requirement already satisfied: ipython>=5.0.0 in c:\users\googletech\anaconda3\lib\site-packages (from ipykernel->notebook>=4.3.1->jupyter-kite) (7.18.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\googletech\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyter-kite) (2.8.1)
Requirement already satisfied: six in c:\users\googletech\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.15.0)
Requirement already satisfied: cffi>=1.0.0 in c:\users\googletech\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.14.2)
Requirement already satisfied: decorator in c:\users\googletech\anaconda3\lib\site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyter-kite) (4.4.2)
Requirement already satisfied: packaging in c:\users\googletech\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (20.4)
Requirement already satisfied: webencodings in c:\users\googletech\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\googletech\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (20.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\googletech\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (0.17.3)
Requirement already satisfied: pickleshare in c:\users\googletech\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\googletech\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (3.0.7)
Requirement already satisfied: backcall in c:\users\googletech\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\googletech\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.4.3)
Requirement already satisfied: jedi>=0.10 in c:\users\googletech\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.17.1)
Requirement already satisfied: pycparser in c:\users\googletech\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.3.1->jupyter-kite) (2.20)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\googletech\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (2.4.7)
Requirement already satisfied: wcwidth in c:\users\googletech\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\googletech\anaconda3\lib\site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.0)
Building jupyterlab assets (build:prod:minimize)
************************************
*************************************

The output of pip list:

(base) PS C:\Users\GoogleTech> pip list
Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
AnyQt                              0.0.10
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.1.post1
atomicwrites                       1.4.0
attrs                              20.2.0
autopep8                           1.5.4
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
baycomp                            1.0.2
bcrypt                             3.2.0
beautifulsoup4                     4.9.1
bitarray                           1.5.3
bkcharts                           0.2
bleach                             3.2.1
bokeh                              2.2.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
CacheControl                       0.12.6
certifi                            2020.6.20
cffi                               1.14.2
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.3
commonmark                         0.9.1
comtypes                           1.1.7
conda                              4.8.4
conda-build                        3.20.2
conda-package-handling             1.7.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       3.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.10.1
dask                               2.26.0
decorator                          4.4.2
defusedxml                         0.6.0
dictdiffer                         0.8.0
diff-match-patch                   20200713
dill                               0.3.2
distributed                        2.26.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fast-histogram                     0.9
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.3
Flask                              1.1.2
fsspec                             0.8.0
future                             0.18.2
gevent                             20.6.2
glob2                              0.7
glue-core                          0.15.6
glue-vispy-viewers                 0.12.2
glueviz                            0.15.2
gmpy2                              2.0.8
greenlet                           0.4.16
h11                                0.9.0
h2                                 3.2.0
h5py                               2.10.0
HeapDict                           1.0.1
hpack                              3.0.0
html5lib                           1.1
httpcore                           0.10.1
httpx                              0.14.3
hyperframe                         5.2.0
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 1.7.0
iniconfig                          0.0.0
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.18.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.4.2
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
joblib                             0.16.0
jovian                             0.2.18
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.6
jupyter-console                    6.2.0
jupyter-core                       4.6.3
jupyter-kite                       1.0.0
jupyterlab                         2.2.6
jupyterlab-server                  1.2.0
keyring                            21.4.0
keyrings.alt                       3.4.0
kiwisolver                         1.2.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.34.0
locket                             0.2.0
lockfile                           0.12.2
lxml                               4.5.2
MarkupSafe                         1.1.1
matplotlib                         3.3.1
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.5.0
mpl-scatter-density                0.7
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.7
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.1
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.19.2
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.5
openTSNE                           0.4.3
orange-canvas-core                 0.1.15
orange-widget-base                 4.7.0
Orange3                            3.26.0
packaging                          20.4
pandas                             1.1.1
pandocfilters                      1.4.2
paramiko                           2.7.2
parso                              0.7.0
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.2.2
pkginfo                            1.5.0.1
plotly                             4.10.0
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.7
psutil                             5.7.2
py                                 1.9.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.5
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.7.1
pylint                             2.6.0
PyNaCl                             1.4.0
pynndescent                        0.4.8
pyodbc                             4.0.0-unsupported
PyOpenGL                           3.1.1a1
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyqtgraph                          0.11.0
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             6.0.2
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
python-louvain                     0.14
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.1
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.6
QtPy                               1.9.0
regex                              2020.7.14
requests                           2.24.0
retrying                           1.3.3
rfc3986                            1.4.0
rope                               0.17.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.23.2
scipy                              1.5.0
seaborn                            0.10.1
Send2Trash                         1.5.0
serverfiles                        0.3.0
setuptools                         49.6.0.post20200814
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.15.0
sniffio                            1.1.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.19
statsmodels                        0.11.1
sympy                              1.6.2
tables                             3.6.1
tblib                              1.7.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
toml                               0.10.1
toolz                              0.10.0
tornado                            6.0.4
tqdm                               4.48.2
traitlets                          4.3.3
typing-extensions                  3.7.4.3
ujson                              3.1.0
unicodecsv                         0.14.1
urllib3                            1.25.10
uuid                               1.30
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.3.3
xlwings                            0.20.5
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.1.0
zope.event                         4.4
zope.interface                     5.1.0

The output of jupyter labextension list
(base) PS C:\Users\GoogleTech> jupyter labextension list
JupyterLab v2.2.6
Known labextensions:
   app dir: C:\Users\GoogleTech\anaconda3\share\jupyter\lab
        @kiteco/jupyterlab-kite v1.0.0 enabled  ok

Uninstalled core extensions:
    @kiteco/jupyterlab-kite

Thank you

**Comment by cogsci2** [comment]
Same behavior.

Ubuntu 20.04
Jupyter Lab 2.2.8

The co-pilot and auto-completion work fine from VScode but not from JupyterLab (anymore).   I have uninstalled and re-installed numerous times.  

Only 3 extensions are installed:

1. @kiteco/jupyterlab-kite
2. @jupyter-widgets/jupyterlab-manager
3. @jupyterlab/toc

**Comment by cogsci2** [comment]
I was able to resolve this issue by removing the contents of 
`<conda env>/share/jupyter/lab/settings/build_config.json`
