### ISSUE TITLE
Publish VS Code extension to Open VSX

### ISSUE THREAD

**Issue by tywmick** [kiteco/issue-tracker#399]
Would you mind publishing Kite's VS Code extension to [Open VSX](https://open-vsx.org/) in addition to the Visual Studio Marketplace? Open VSX is a vendor-neutral open-source registry that can be used by any editor or IDE that supports VS Code extensions, whereas VS Marketplace's [Terms of Use](https://aka.ms/vsmarketplace-ToU) requires that the Marketplace and any extensions it distributes only be used with Microsoft products.

Here's [Open VSX's publishing instructions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). It looks like a pretty easy one-time process:

1. Log onto their site and create an access token.
2. Use their [ovsx](https://github.com/eclipse/openvsx/tree/master/cli) CLI to create a namespace.
3. Claim ownership of the namespace.
4. Add an `ovsx publish` command to your publishing script.

Alternatively, if you give Eclipse Open VSX written permission (in a manner that satisfies [the plugin's license](https://github.com/kiteco/vscode-plugin/blob/master/LICENSE)) to build and distribute your extension, I'd be happy to add [its repository](https://github.com/kiteco/vscode-plugin) to their [extension-publishing CI](https://github.com/open-vsx/publish-extensions) myself.

This would partially fix #224 and kiteco/vscode-plugin#298, at least in terms of giving VSCodium users a legal way to install and use this plugin. I'm much less concerned about Kite's desktop app being able to detect VSCodium automatically.

**Comment by edzkite** [comment]
We're now on Open VSX: https://open-vsx.org/extension/kiteco/kite.

Feel free to let me know if any issues arise during the installation process. Cheers!

**Comment by tywmick** [comment]
Wow, that was quick! I've installed the extension on VSCodium and everything's working perfectly—thanks so much!
