### ISSUE TITLE
Kite not working properly in my PyCharm 2020.2.1

### ISSUE THREAD

**Issue by jlumbroso** [kiteco/issue-tracker#400]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [X] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [X] Include your Kite application logs, _taken while you are experiencing your issue_.
- [X] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

I am using PyCharm. Here's the link to the logs:
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/354242/kite_local/client.log.2020-09-20_10-43-42-AM.bak.gz

**Describe the bug**

Kite doesn't seem to be integrated in PyCharm, despite the installation seeming to have run through successfully. I don't see the Kite logo in my editor, nor any of the autocomplete suggestions.

**Editor version**

```
PyCharm 2020.2.1 (Professional Edition)
Build #PY-202.6948.78, built on August 25, 2020
Licensed to Jérémie Lumbroso
Subscription is active until March 23, 2021
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: org.toml.lang, com.jetbrains.intellij.datalore, ru.meanmail.plugin.requirements, ru.adelf.idea.dotenv
```

**Comment by jlumbroso** [comment]
I have saved the PyCharm logs, and happy to send them by email.

**Comment by its-dhung** [comment]
Can you confirm that:

1. You see Kite installed for PyCharm in Kite's plugin manager?
2. You restarted PyCharm if it was running when you installed Kite?
2. You've tried opening a saved Python file in PyCharm?

**Comment by jlumbroso** [comment]
@its-dhung I think the answer to all those questions — which you asked two months after the fact, when it is almost impossible to reproduce the same environment and conditions — is obvious. If answers to such trivial questions are necessary to this debugging process — and you don't get them from the existing information you are asking users to collect to report bugs — perhaps consider enhancing your issue reporting procedure. This might save us all time and frustration.
