### ISSUE TITLE
Kite extension for jupyterlab is not working

### ISSUE THREAD

**Issue by aravinth2k** [kiteco/issue-tracker#403]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [x] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

**Screenshots**

hello kite team,
      I have installed kite and used it as pycharm extension 
while i try to install it for jupyterlab it install well but i can't use the extension for jupyter notebook. i uninstall and reinstall jupyterlab and notebook. But it is not working still. so please check and solve this issue as soon as possible. i have provided the information that you mentioned in the guide page
 
The following are the information that you needed
1. My OS
     Microsoft Windows 10 Home Single Language

2. Whether or not you have the Kite desktop app installed
     Yes, it is work well in Pycharm IDE
![Capture](https://user-images.githubusercontent.com/71697881/93864742-f0bdcb00-fce2-11ea-8bfc-042c0f9b1302.JPG)

3. The error you received when trying to install the plugin from the command line
     No error
![Capture1](https://user-images.githubusercontent.com/71697881/93864861-1fd43c80-fce3-11ea-92c1-d5685b2ba103.JPG)

4. The output of pip list

> C:\Users\Aravinth>pip list

> Package                Version
> ---------------------- ---------
> -andas                 1.0.5
> absl-py                0.10.0
> appdirs                1.4.4
> argon2-cffi            20.1.0
> astunparse             1.6.3
> async-generator        1.10
> attrs                  20.2.0
> Babel                  2.8.0
> backcall               0.2.0
> bleach                 3.2.1
> cachetools             4.1.1
> certifi                2020.6.20
> cffi                   1.14.3
> chardet                3.0.4
> colorama               0.4.3
> cycler                 0.10.0
> decorator              4.4.2
> defusedxml             0.6.0
> distlib                0.3.1
> entrypoints            0.3
> et-xmlfile             1.0.1
> filelock               3.0.12
> gast                   0.4.0
> google-auth            1.21.2
> google-auth-oauthlib   0.4.1
> google-pasta           0.2.0
> grpcio                 1.32.0
> h5py                   2.10.0
> idna                   2.10
> ipykernel              5.3.4
> ipython                7.18.1
> ipython-genutils       0.2.0
> ipywidgets             7.5.1
> jdcal                  1.4.1
> jedi                   0.17.2
> Jinja2                 2.11.2
> joblib                 0.16.0
> json5                  0.9.5
> jsonschema             3.2.0
> jupyter                1.0.0
> jupyter-client         6.1.7
> jupyter-console        6.2.0
> jupyter-core           4.6.3
> jupyter-kite           1.0.0
> jupyterlab             2.2.8
> jupyterlab-pygments    0.1.1
> jupyterlab-server      1.2.0
> Keras-Preprocessing    1.1.2
> kiwisolver             1.2.0
> Markdown               3.2.2
> MarkupSafe             1.1.1
> matplotlib             3.3.2
> mistune                0.8.4
> nbclient               0.5.0
> nbconvert              6.0.5
> nbformat               5.0.7
> nest-asyncio           1.4.0
> notebook               6.1.4
> numpy                  1.19.2
> oauthlib               3.1.0
> opencv-python          4.4.0.42
> openpyxl               3.0.5
> opt-einsum             3.3.0
> packaging              20.4
> pandas                 1.1.2
> pandocfilters          1.4.2
> parso                  0.7.1
> pickleshare            0.7.5
> Pillow                 7.2.0
> pip                    20.2.3
> prometheus-client      0.8.0
> prompt-toolkit         3.0.7
> protobuf               3.13.0
> pyasn1                 0.4.8
> pyasn1-modules         0.2.8
> pycparser              2.20
> pygame                 1.9.6
> Pygments               2.7.1
> PyMySQL                0.10.1
> pyparsing              2.4.7
> pyperclip              1.8.0
> pyrsistent             0.17.3
> python-dateutil        2.8.1
> pytz                   2020.1
> pywin32                228
> pywinpty               0.5.7
> pyzmq                  19.0.2
> qtconsole              4.7.7
> QtPy                   1.9.0
> requests               2.24.0
> requests-oauthlib      1.3.0
> rsa                    4.6
> scikit-learn           0.23.2
> scipy                  1.5.2
> seaborn                0.11.0
> Send2Trash             1.5.0
> setuptools             50.3.0
> six                    1.15.0
> sklearn                0.0
> tensorboard            2.3.0
> tensorboard-plugin-wit 1.7.0
> tensorflow             2.3.0
> tensorflow-estimator   2.3.0
> termcolor              1.1.0
> terminado              0.9.1
> testpath               0.4.4
> threadpoolctl          2.1.0
> tkcalendar             1.6.1
> tornado                6.0.4
> traitlets              5.0.4
> urllib3                1.25.10
> virtualenv             20.0.31
> wcwidth                0.2.5
> webencodings           0.5.1
> Werkzeug               1.0.1
> wheel                  0.35.1
> widgetsnbextension     3.5.1
> wrapt                  1.12.1
> xlrd                   1.2.0

5. The output of jupyter labextension list

> C:\Users\Aravinth>jupyter labextension list
> JupyterLab v2.2.8
> Known labextensions:
>    app dir: c:\users\aravinth\appdata\local\programs\python\python38\share\jupyter\lab
>         @kiteco/jupyterlab-kite v1.0.0 enabled  ok

**Comment by aravinth2k** [comment]
The following are the information that you needed
1. My OS
     Microsoft Windows 10 Home Single Language

2. Whether or not you have the Kite desktop app installed
     Yes, it is work well in Pycharm IDE
![Capture](https://user-images.githubusercontent.com/71697881/93864742-f0bdcb00-fce2-11ea-8bfc-042c0f9b1302.JPG)


3. The error you received when trying to install the plugin from the command line
     No error
![Capture1](https://user-images.githubusercontent.com/71697881/93864861-1fd43c80-fce3-11ea-92c1-d5685b2ba103.JPG)

4. The output of pip list
```

> Requirement already satisfied: jupyter-kite in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (1.0.0)
> Requirement already satisfied: notebook>=4.3.1 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from jupyter-kite) (6.1.4)
> Requirement already satisfied: setuptools in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from jupyter-kite) (50.3.0)
> Requirement already satisfied: traitlets>=4.2.1 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.0.4)
> Requirement already satisfied: terminado>=0.8.3 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.9.1)
> Requirement already satisfied: ipykernel in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.3.4)
> Requirement already satisfied: jinja2 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (2.11.2)
> Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.1.7)
> Requirement already satisfied: pyzmq>=17 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (19.0.2)
> Requirement already satisfied: nbformat in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.0.7)
> Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (4.6.3)
> Requirement already satisfied: prometheus-client in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.8.0)
> Requirement already satisfied: Send2Trash in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (1.5.0)
> Requirement already satisfied: ipython-genutils in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.2.0)
> Requirement already satisfied: argon2-cffi in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (20.1.0)
> Requirement already satisfied: tornado>=5.0 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.0.4)
> Requirement already satisfied: nbconvert in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.0.5)
> Requirement already satisfied: pywinpty>=0.5; os_name == "nt" in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from terminado>=0.8.3->notebook>=4.3.1->jupyter-kite) (0.5.7)
> Requirement already satisfied: ipython>=5.0.0 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->notebook>=4.3.1->jupyter-kite) (7.18.1)
> Requirement already satisfied: MarkupSafe>=0.23 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from jinja2->notebook>=4.3.1->jupyter-kite) (1.1.1)
> Requirement already satisfied: python-dateutil>=2.1 in c:\users\aravinth\appdata\roaming\python\python38\site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyter-kite) (2.8.1)
> Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbformat->notebook>=4.3.1->jupyter-kite) (3.2.0)
> Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from jupyter-core>=4.6.1->notebook>=4.3.1->jupyter-kite) (228)
> Requirement already satisfied: six in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.15.0)
> Requirement already satisfied: cffi>=1.0.0 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.14.3)
> Requirement already satisfied: entrypoints>=0.2.2 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.3)
> Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.8.4)
> Requirement already satisfied: defusedxml in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.6.0)
> Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.0)
> Requirement already satisfied: pygments>=2.4.1 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (2.7.1)
> Requirement already satisfied: jupyterlab-pygments in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.1.1)
> Requirement already satisfied: testpath in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.4.4)
> Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.2)
> Requirement already satisfied: bleach in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (3.2.1)
> Requirement already satisfied: jedi>=0.10 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.17.2)
> Requirement already satisfied: backcall in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.0)
> Requirement already satisfied: pickleshare in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.5)
> Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (3.0.7)
> Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.4.3)
> Requirement already satisfied: decorator in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (4.4.2)
> Requirement already satisfied: attrs>=17.4.0 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (20.2.0)
> Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (0.17.3)
> Requirement already satisfied: pycparser in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.3.1->jupyter-kite) (2.20)
> Requirement already satisfied: nest-asyncio in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.0)
> Requirement already satisfied: async-generator in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.3.1->jupyter-kite) (1.10)
> Requirement already satisfied: webencodings in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.1)
> Requirement already satisfied: packaging in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (20.4)
> Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.1)
> Requirement already satisfied: wcwidth in c:\users\aravinth\appdata\local\programs\python\python38\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.5)
> Requirement already satisfied: pyparsing>=2.0.2 in c:\users\aravinth\appdata\roaming\python\python38\site-packages (from packaging->bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (2.4.7)

```

5. The output of jupyter labextension list

> Building jupyterlab assets (build:prod:minimize)
> -

**Comment by edzkite** [comment]
@aravinth2k Is this possibly the same issue as https://github.com/kiteco/issue-tracker/issues/380?

Could you give me the output of `jupyter serverextension list`?

**Comment by aravinth2k** [comment]
> @aravinth2k Is this possibly the same issue as #380?
> 
> Could you give me the output of `jupyter serverextension list`?

> C:\WINDOWS\system32>jupyter serverextension list
> config dir: c:\users\aravinth\appdata\local\programs\python\python38\etc\jupyter
>     jupyter_kite enabled
>     - Validating...
>       jupyter_kite 1.1.0 ok
>     jupyterlab enabled
>     - Validating...
>       jupyterlab 2.2.8 ok

**Comment by aravinth2k** [comment]
hello kite team
First i ask sorry for this trouble created by me. This issue is caused due to misunderstanding about kite engine. Kite software is available for Jupyter lab i open my regular jupyter notebook and wrongly raise this issue i am extremly sorry for this inconvenient from my side i thank you for responding to the issue at early stage 

i suggest your team to built kite software for jupyter notebook also
Thank you
