### ISSUE TITLE
conflicting with COC plugin

### ISSUE THREAD

**Issue by shaeinst** [kiteco/issue-tracker#406]
i use coc plugin for other languages, so i am not going to uninstall it. but i think kite is conflicting with [coc plugin ](https://github.com/neoclide/coc.nvim).

no matter what file, every time i open a file with vim, its shows errors on startup and that error is from kite
`Error detected while processing function kite#onboarding#call[7]..kite#client#onboarding_file[7]..kite#onboarding#handler[3]..kite#utils#set_setting:
line    4:
E482: Can't create file /vim-plugin.json
Press ENTER or type command to continue
`

**Comment by shaeinst** [comment]
sorry my bad, i just uninstalled the coc and tested vim. i still get same problem. i think it's not conflicting with coc, something else is wrong. 
this issue is related with [this issue](https://github.com/kiteco/issue-tracker/issues/407) which i recently opened.

**Comment by airblade** [comment]
There is just one issue here.  I'll close this one in favour of #407 because its title reflects the problem better.
