### ISSUE TITLE
"Logs" tab is not showing in Windows Copilot

### ISSUE THREAD

**Issue by om-hb** [kiteco/issue-tracker#408]
**Describe the bug**
While in the process of submitting another bug, I noticed that my Kite Copilot on Windows doesn't show the "Logs" tab [shown in your instructions](https://help.kite.com/article/96-contact-us-with-logs). Visiting `kite://settings/logs` in my browser doesn't work either.
 
**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/49337083/94368562-f8b3ab80-00e4-11eb-8662-b4871a77f6ef.png)

**Comment by its-dhung** [comment]
It looks like you're using a very old version of Kite. The easiest way to upgrade Kite on Windows is to uninstall Kite and redownload and install it from https://kite.com/download.
