### ISSUE TITLE
Jupyterlab install issue

### ISSUE THREAD

**Issue by d-wrigley** [kiteco/issue-tracker#411]
**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

Jupyterlab will not install labextension "@kiteco/jupyterlab-kite"
- ValueError: Please install Node.js and npm 

nodejs and npm already installed

**Troubleshooting** - from https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin

Windows 10 Home - 10.0.18363
Desktop app installed and working on Atom, Pycharm

**Copy and paste of Anaconda Prompt below**
(base) C:\Users\DJWri>jupyter labextension install "@kiteco/jupyterlab-kite"
An error occured.
ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
See the log file for details:  C:\Users\DJWri\AppData\Local\Temp\jupyterlab-debug-gy_tcrd_.log

(base) C:\Users\DJWri>pip list
Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.1.post1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.2.0
autopep8                           1.5.4
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.9.1
bitarray                           1.5.3
bkcharts                           0.2
bleach                             3.1.5
bokeh                              2.2.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
certifi                            2020.6.20
cffi                               1.14.1
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.3
comtypes                           1.1.7
conda                              4.8.4
conda-build                        3.20.2
conda-package-handling             1.6.1
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       3.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.10.1
dask                               2.26.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.26.0
docutils                           0.16
emoji                              0.6.0
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.3
Flask                              1.1.2
fsspec                             0.8.2
future                             0.18.2
gevent                             20.6.2
glob2                              0.7
gmpy2                              2.1.0b1
greenlet                           0.4.16
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
imagecodecs                        2020.5.30
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 1.7.0
iniconfig                          1.0.1
intervaltree                       3.0.2
ipykernel                          5.3.4
ipython                            7.18.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.5.2
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.15.2
Jinja2                             2.11.2
joblib                             0.16.0
json5                              0.9.4
jsonschema                         3.2.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-core                       4.6.3
jupyter-kite                       1.0.0
jupyterlab                         2.2.7
jupyterlab-pygments                0.1.1
jupyterlab-server                  1.2.0
keyring                            21.4.0
kiwisolver                         1.2.0
langid                             1.1.6
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.34.0
locket                             0.2.0
lxml                               4.5.2
MarkupSafe                         1.1.1
matplotlib                         3.3.1
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.1.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.5.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclient                           0.5.0
nbconvert                          6.0.1
nbformat                           5.0.7
nest-asyncio                       1.4.0
networkx                           2.5
nltk                               3.4.4
nodejs                             0.1.1
nose                               1.3.7
notebook                           6.1.4
npm                                0.1.1
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.19.1
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.5
optional-django                    0.1.0
packaging                          20.4
pandas                             1.1.2
pandocfilters                      1.4.2
paramiko                           2.7.2
parso                              0.5.2
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pdfminer.six                       20181108
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.2.3
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.7
psutil                             5.7.2
ptvsd                              4.3.2
py                                 1.9.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycrypto                           2.6.1
pycryptodome                       3.9.8
pycurl                             7.43.0.5
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.6.1
pylint                             2.6.0
PyNaCl                             1.3.0
pyodbc                             4.0.30
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
PyQt5                              5.12.3
PyQt5-sip                          4.19.18
PyQtWebEngine                      5.12.1
pyreadline                         2.1
pyrsistent                         0.17.2
PySocks                            1.7.1
pytest                             6.0.2
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.31.7
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.7
QtPy                               1.9.0
regex                              2020.7.14
requests                           2.24.0
rope                               0.17.0
rpy2                               3.3.5
Rtree                              0.9.4
ruamel-yaml-conda                  0.15.80
scikit-image                       0.17.2
scikit-learn                       0.23.2
scipy                              1.5.2
seaborn                            0.11.0
Send2Trash                         1.5.0
setuptools                         49.6.0.post20200814
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.20
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.0.1
spyder-kernels                     1.8.1
SQLAlchemy                         1.3.19
statsmodels                        0.12.0
sympy                              1.6.2
tables                             3.6.1
tblib                              1.6.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
tifffile                           2020.9.3
toml                               0.10.1
toolz                              0.10.0
tornado                            6.0.4
tqdm                               4.48.2
traitlets                          5.0.4
typed-ast                          1.4.1
typing-extensions                  3.7.4.2
tzlocal                            2.1
ujson                              3.2.0
unicodecsv                         0.14.1
urllib3                            1.25.10
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xeus-python                        0.8.3
xlrd                               1.2.0
XlsxWriter                         1.3.3
xlwings                            0.20.7
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.1.0
zope.event                         4.4
zope.interface                     5.1.0

(base) C:\Users\DJWri>jupyter labextension list
JupyterLab v2.2.7
No installed extensions

**Comment by its-dhung** [comment]
Please install node first and try again

> Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
