### ISSUE TITLE
Kite doesn't work with phpStorm, while it does work with other JetBrains IDEs such as WebStorm and IntelliJ

### ISSUE THREAD

**Issue by OMA2k** [kiteco/issue-tracker#413]
Kite works with JetBrains IDEs such as IntelliJ and WebStorm. Then, why doesn't it work with phpStorm? I know Kite doesn't support PHP currently, but I would like to use its JavaScript capabilities. If it works in WebStorm and IntelliJ, it should work in phpStorm as well, since they share the same engine.

**Comment by jansorg** [comment]
Thanks for reporting!
You can now install from the marketplace, as with any other plugin. Kite is now also able to detect PhpStorm and all of the other JetBrains IDEs.
