### ISSUE TITLE
Kite not working after removing jupyterlab-lsp

### ISSUE THREAD

**Issue by post-soybeen** [kiteco/issue-tracker#417]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**

To enable "jupyterlab-kite", I uninstalled "jupyterlab-lsp", like
"jupyter labextension uninstall @(jupyterlab-lsp name)".
But the jupyterlab-lsp still work in my jupyter lab.
Does anyone know how to disable jupyterlab-lsp completely and enable jupyter-kite?

my jupyter labextension list is following

jupyter labextension list
JupyterLab v2.2.6
Known labextensions:
app dir: C:\Users\myname\anacondafile\envs\envname\share\jupyter\lab
@kiteco/jupyterlab-kite v1.1.0 enabled ok

Uninstalled core extensions:
@kiteco/jupyterlab-kite

**Comment by post-soybeen** [comment]
To enable "jupyterlab-kite", I uninstalled "jupyterlab-lsp", like
 "jupyter labextension uninstall @(jupyterlab-lsp name)".
But the jupyterlab-lsp still work in my jupyter lab.
Does anyone know how to disable jupyterlab-lsp completely and enable jupyter-kite?

 my jupyter labextension list is following

> jupyter labextension list
JupyterLab v2.2.6
Known labextensions:
   app dir: C:\Users\myname\anacondafile\envs\envname\share\jupyter\lab
        @kiteco/jupyterlab-kite v1.1.0 enabled  ok

Uninstalled core extensions:
    @kiteco/jupyterlab-kite

**Comment by edzkite** [comment]
You may also need to remove the jupyterlab-lsp server extension -- `pip uninstall jupyterlab-lsp`.

If you type `jupyter serverextension list` it should output a couple of config directories. You may also need to navigate to those directories and remove entries for jupyterlab-lsp within those config JSON files

**Comment by post-soybeen** [comment]
Thanks, edzkite!

I followed your message, and I tried to enable kite, but so far, unfortunately it didn't work well.

I will consider whether I comprehend your advice well.

**Comment by its-dhung** [comment]
Given that Kite is shown as both installed and uninstalled, you may need to manually remove JupyterLab's `build_config.json` file. [This issue](https://github.com/jupyterlab/jupyterlab/issues/8122) in the JupyterLab main repo contains more info.
