### ISSUE TITLE
Kite JupyterLab Plugin problem

### ISSUE THREAD

**Issue by hansphenca** [kiteco/issue-tracker#421]
Hi I would like to issued a problem regarding my Kite JupyterLab Plugin not running. Thank you!

OS: Windows 10 Pro Version 1903
JupyterLab Version 2.2.6
Kite desktop app installed, also set to always run on startup
Kite logo at the bottom left corner of the JupyterLab window not there
Additional thing that I notice: if I were to go to my Kite's copilot, then to Settings, then to Plugins, only Spyder IDE is found under 'INSTALLED EDITOR PLUGINS', JupyterLab is under 'AVAILABLE EDITOR PLUGINS'

(base) C:\Users\User>pip install jupyter-kite
Requirement already satisfied: jupyter-kite in c:\users\user\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: notebook>=4.3.1 in c:\users\user\anaconda3\lib\site-packages (from jupyter-kite) (6.1.4)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\lib\site-packages (from jupyter-kite) (50.3.0.post20201006)
Requirement already satisfied: Send2Trash in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (1.5.0)
Requirement already satisfied: pyzmq>=17 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (19.0.2)
Requirement already satisfied: nbformat in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.0.7)
Requirement already satisfied: ipython-genutils in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.2.0)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (4.6.3)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.1.7)
Requirement already satisfied: prometheus-client in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.8.0)
Requirement already satisfied: tornado>=5.0 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.0.4)
Requirement already satisfied: ipykernel in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.3.4)
Requirement already satisfied: nbconvert in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.0.7)
Requirement already satisfied: terminado>=0.8.3 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.8.3)
Requirement already satisfied: traitlets>=4.2.1 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.0.4)
Requirement already satisfied: argon2-cffi in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (20.1.0)
Requirement already satisfied: jinja2 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (2.11.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\user\anaconda3\lib\site-packages (from nbformat->notebook>=4.3.1->jupyter-kite) (3.2.0)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\user\anaconda3\lib\site-packages (from jupyter-core>=4.6.1->notebook>=4.3.1->jupyter-kite) (227)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\user\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyter-kite) (2.8.1)
Requirement already satisfied: ipython>=5.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipykernel->notebook>=4.3.1->jupyter-kite) (7.18.1)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.2)
Requirement already satisfied: jupyterlab-pygments in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.1.2)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.3)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.0)
Requirement already satisfied: bleach in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (3.2.1)
Requirement already satisfied: testpath in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.4.4)
Requirement already satisfied: defusedxml in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.6.0)
Requirement already satisfied: pygments>=2.4.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (2.7.1)
Requirement already satisfied: cffi>=1.0.0 in c:\users\user\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.14.3)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.15.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\user\anaconda3\lib\site-packages (from jinja2->notebook>=4.3.1->jupyter-kite) (1.1.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (20.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (0.17.3)
Requirement already satisfied: backcall in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.0)
Requirement already satisfied: decorator in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (4.4.2)
Requirement already satisfied: jedi>=0.10 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.17.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (3.0.7)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.4.3)
Requirement already satisfied: pickleshare in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.5)
Requirement already satisfied: nest-asyncio in c:\users\user\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.1)
Requirement already satisfied: async-generator in c:\users\user\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.3.1->jupyter-kite) (1.10)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (20.4)
Requirement already satisfied: webencodings in c:\users\user\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.1)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.3.1->jupyter-kite) (2.20)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\user\anaconda3\lib\site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.0)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.5)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\user\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (2.4.7)

(base) C:\Users\User>jupyter labextension install "@kiteco/jupyterlab-kite"
Building jupyterlab assets (build:prod:minimize)
-

(base) C:\Users\User>pip install jupyter-kite
Requirement already satisfied: jupyter-kite in c:\users\user\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: notebook>=4.3.1 in c:\users\user\anaconda3\lib\site-packages (from jupyter-kite) (6.1.4)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\lib\site-packages (from jupyter-kite) (50.3.0.post20201006)
Requirement already satisfied: Send2Trash in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (1.5.0)
Requirement already satisfied: pyzmq>=17 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (19.0.2)
Requirement already satisfied: nbformat in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.0.7)
Requirement already satisfied: ipython-genutils in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.2.0)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (4.6.3)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.1.7)
Requirement already satisfied: prometheus-client in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.8.0)
Requirement already satisfied: tornado>=5.0 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.0.4)
Requirement already satisfied: ipykernel in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.3.4)
Requirement already satisfied: nbconvert in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.0.7)
Requirement already satisfied: terminado>=0.8.3 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.8.3)
Requirement already satisfied: traitlets>=4.2.1 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.0.4)
Requirement already satisfied: argon2-cffi in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (20.1.0)
Requirement already satisfied: jinja2 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (2.11.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\user\anaconda3\lib\site-packages (from nbformat->notebook>=4.3.1->jupyter-kite) (3.2.0)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\user\anaconda3\lib\site-packages (from jupyter-core>=4.6.1->notebook>=4.3.1->jupyter-kite) (227)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\user\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyter-kite) (2.8.1)
Requirement already satisfied: ipython>=5.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipykernel->notebook>=4.3.1->jupyter-kite) (7.18.1)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.2)
Requirement already satisfied: jupyterlab-pygments in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.1.2)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.3)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.0)
Requirement already satisfied: bleach in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (3.2.1)
Requirement already satisfied: testpath in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.4.4)
Requirement already satisfied: defusedxml in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.6.0)
Requirement already satisfied: pygments>=2.4.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (2.7.1)
Requirement already satisfied: cffi>=1.0.0 in c:\users\user\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.14.3)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.15.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\user\anaconda3\lib\site-packages (from jinja2->notebook>=4.3.1->jupyter-kite) (1.1.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (20.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (0.17.3)
Requirement already satisfied: backcall in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.0)
Requirement already satisfied: decorator in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (4.4.2)
Requirement already satisfied: jedi>=0.10 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.17.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (3.0.7)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.4.3)
Requirement already satisfied: pickleshare in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.5)
Requirement already satisfied: nest-asyncio in c:\users\user\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.1)
Requirement already satisfied: async-generator in c:\users\user\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.3.1->jupyter-kite) (1.10)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (20.4)
Requirement already satisfied: webencodings in c:\users\user\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.1)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.3.1->jupyter-kite) (2.20)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\user\anaconda3\lib\site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.0)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.5)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\user\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (2.4.7)

(base) C:\Users\User>jupyter labextension install "@kiteco/jupyterlab-kite"
Building jupyterlab assets (build:prod:minimize)
-
(base) C:\Users\User>
(base) C:\Users\User>pip list
Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.1.post1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.2.0
autopep8                           1.5.4
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
bitarray                           1.5.3
bkcharts                           0.2
bleach                             3.2.1
bokeh                              2.2.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
certifi                            2020.6.20
cffi                               1.14.3
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.3
comtypes                           1.1.7
conda                              4.8.5
conda-build                        3.20.3
conda-package-handling             1.7.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       3.1.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.11.0
dask                               2.30.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.30.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.4
Flask                              1.1.2
fsspec                             0.8.0
future                             0.18.2
gevent                             20.9.0
glob2                              0.7
gmpy2                              2.0.8
greenlet                           0.4.17
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 1.7.0
iniconfig                          0.0.0
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.18.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.5.4
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
joblib                             0.17.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-core                       4.6.3
jupyter-kite                       1.1.0
jupyterlab                         2.2.6
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
keyring                            21.4.0
kiwisolver                         1.2.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.34.0
locket                             0.2.0
lxml                               4.5.2
MarkupSafe                         1.1.1
matplotlib                         3.3.1
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.5.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclient                           0.5.0
nbconvert                          6.0.7
nbformat                           5.0.7
nest-asyncio                       1.4.1
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.4
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.19.1
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.5
packaging                          20.4
pandas                             1.1.3
pandocfilters                      1.4.2
paramiko                           2.7.2
parso                              0.7.0
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.2.3
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.7
psutil                             5.7.2
py                                 1.9.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.5
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.7.1
pylint                             2.6.0
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             0.0.0
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.7
QtPy                               1.9.0
regex                              2020.7.14
requests                           2.24.0
rope                               0.17.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.23.2
scipy                              1.5.0
seaborn                            0.11.0
Send2Trash                         1.5.0
setuptools                         50.3.0.post20201006
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.19
statsmodels                        0.11.1
sympy                              1.6.2
tables                             3.6.1
tblib                              1.7.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
toml                               0.10.1
toolz                              0.11.1
tornado                            6.0.4
tqdm                               4.50.0
traitlets                          5.0.4
typing-extensions                  3.7.4.3
ujson                              3.2.0
unicodecsv                         0.14.1
urllib3                            1.25.10
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.3.6
xlwings                            0.20.7
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.3.0
zope.event                         4.4
zope.interface                     5.1.2

(base) C:\Users\User>jupyter labextension list
JupyterLab v2.2.6
Known labextensions:
   app dir: C:\Users\User\anaconda3\share\jupyter\lab
        @kiteco/jupyterlab-kite v1.1.0 enabled  ok

Uninstalled core extensions:
    @kiteco/jupyterlab-kite

**Comment by cogsci2** [comment]
I was able to resolve this issue with the following:
https://github.com/kiteco/issue-tracker/issues/397#issuecomment-695181764
