### ISSUE TITLE
Installations issues

### ISSUE THREAD

**Issue by naija-land** [kiteco/issue-tracker#424]
**Your OS** - MacOS
**Whether or not you have the Kite desktop app installed** - Installed
**The error you received when trying to install the plugin from the command line** - JupyterLab failed to build
**The output of pip list** -
absl-py                            0.9.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
appnope                            0.1.0
appscript                          1.0.1
asn1crypto                         1.0.1
astroid                            2.3.1
astropy                            4.0.1.post1
astunparse                         1.6.3
atomicwrites                       1.3.0
attrs                              19.3.0
Babel                              2.7.0
backcall                           0.1.0
backports.functools-lru-cache      1.6.1
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
beautifulsoup4                     4.8.0
bitarray                           1.0.1
bkcharts                           0.2
bleach                             3.1.0
blis                               0.4.1
bokeh                              1.3.4
boto                               2.49.0
boto3                              1.13.21
botocore                           1.16.21
Bottleneck                         1.2.1
cachetools                         4.1.0
catalogue                          1.0.0
catboost                           0.23.2
certifi                            2019.9.11
cffi                               1.12.3
chardet                            3.0.4
Click                              7.0
cloudpickle                        1.2.2
clyent                             1.2.2
cmdstanpy                          0.9.5
colorama                           0.4.1
conda                              4.8.5
conda-build                        3.18.9
conda-package-handling             1.6.0
conda-verify                       3.4.2
confuse                            1.3.0
contextlib2                        0.6.0
convertdate                        2.2.1
cryptography                       2.7
cvxpy                              1.1.1
cycler                             0.10.0
cymem                              2.0.3
Cython                             0.29.13
cytoolz                            0.10.0
dask                               2.5.2
decorator                          4.4.0
defusedxml                         0.6.0
distributed                        2.5.2
docutils                           0.15.2
ecos                               2.0.7.post1
entrypoints                        0.3
ephem                              3.7.7.1
et-xmlfile                         1.0.1
fancyimpute                        0.5.4
fastcache                          1.1.0
fbprophet                          0.7
filelock                           3.0.12
Flask                              1.1.1
fsspec                             0.5.2
future                             0.18.2
gast                               0.3.3
gensim                             3.8.3
gevent                             1.4.0
glob2                              0.7
gmpy2                              2.0.8
google-auth                        1.17.2
google-auth-oauthlib               0.4.1
google-pasta                       0.2.0
graphviz                           0.14
greenlet                           0.4.15
grpcio                             1.29.0
h5py                               2.10.0
HeapDict                           1.0.1
holidays                           0.10.3
html5lib                           1.0.1
htmlmin                            0.1.12
idna                               2.8
ImageHash                          4.1.0
imageio                            2.6.0
imagesize                          1.1.0
imbalanced-learn                   0.6.2
imblearn                           0.0
importlib-metadata                 0.23
ipykernel                          5.1.2
ipython                            7.8.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.15.1
Jinja2                             2.11.2
jmespath                           0.10.0
joblib                             0.13.2
json5                              0.8.5
jsonschema                         3.0.2
jupyter                            1.0.0
jupyter-client                     5.3.3
jupyter-console                    6.0.0
jupyter-contrib-core               0.3.3
jupyter-contrib-nbextensions       0.5.1
jupyter-core                       4.5.0
jupyter-highlight-selected-word    0.2.0
jupyter-kite                       1.1.0
jupyter-latex-envs                 1.4.4
jupyter-nbextensions-configurator  0.4.1
jupyterlab                         1.1.4
jupyterlab-server                  1.0.6
Keras                              2.3.1
Keras-Applications                 1.0.8
Keras-Preprocessing                1.1.2
keyring                            18.0.0
kiwisolver                         1.1.0
knnimpute                          0.1.0
korean-lunar-calendar              0.2.1
lazy-object-proxy                  1.4.2
libarchive-c                       2.8
lief                               0.9.0
lightgbm                           2.3.1
llvmlite                           0.29.0
locket                             0.2.0
LunarCalendar                      0.0.9
lxml                               4.4.1
Markdown                           3.2.2
MarkupSafe                         1.1.1
matplotlib                         3.2.2
mccabe                             0.6.1
missingno                          0.4.2
mistune                            0.8.4
mkl-fft                            1.0.14
mkl-random                         1.1.0
mkl-service                        2.3.0
mlxtend                            0.17.3
mock                               3.0.5
more-itertools                     7.2.0
mpmath                             1.1.0
msgpack                            0.6.1
multipledispatch                   0.6.0
murmurhash                         1.0.2
navigator-updater                  0.2.1
nbconvert                          5.6.0
nbformat                           4.4.0
networkx                           2.4
nltk                               3.4.5
node                               0.9.25
nose                               1.3.7
notebook                           6.0.1
numba                              0.45.1
numexpr                            2.7.0
numpy                              1.17.2
numpydoc                           0.9.1
oauthlib                           3.1.0
odict                              1.7.0
olefile                            0.46
openpyxl                           3.0.0
opt-einsum                         3.2.1
osqp                               0.6.1
packaging                          19.2
pandas                             1.0.5
pandas-profiling                   2.8.0
pandocfilters                      1.4.2
parso                              0.5.1
partd                              1.0.0
path.py                            12.0.1
pathlib2                           2.3.5
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.7.0
phik                               0.10.0
pickleshare                        0.7.5
Pillow                             6.2.0
pip                                20.2.2
pkginfo                            1.5.0.1
plac                               1.1.3
plotly                             4.8.2
pluggy                             0.13.0
plumber                            1.6
ply                                3.11
preshed                            3.0.2
prometheus-client                  0.7.1
prompt-toolkit                     2.0.10
protobuf                           3.12.2
psutil                             5.6.3
ptyprocess                         0.6.0
py                                 1.8.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pycurl                             7.43.0.3
pyflakes                           2.1.1
Pygments                           2.4.2
pylint                             2.4.2
PyMeeus                            0.3.7
pyodbc                             4.0.27
pyOpenSSL                          19.0.0
pyparsing                          2.4.2
pyrsistent                         0.15.4
PySocks                            1.7.1
pystan                             2.19.1.1
pytest                             5.2.1
pytest-arraydiff                   0.3
pytest-astropy                     0.5.0
pytest-doctestplus                 0.4.0
pytest-openfiles                   0.4.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.0
pytz                               2019.3
PyWavelets                         1.0.3
PyYAML                             5.1.2
pyzmq                              18.1.0
QtAwesome                          0.6.0
qtconsole                          4.5.5
QtPy                               1.9.0
requests                           2.24.0
requests-oauthlib                  1.3.0
retrying                           1.3.3
rope                               0.14.0
rsa                                4.6
ruamel-yaml                        0.15.46
s3transfer                         0.3.3
scikit-image                       0.15.0
scikit-learn                       0.23.1
scikit-surprise                    1.1.1
scipy                              1.5.1
scs                                2.1.2
seaborn                            0.9.0
Send2Trash                         1.5.0
setuptools                         49.1.2
setuptools-git                     1.2
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.12.0
smart-open                         2.0.0
snowballstemmer                    2.0.0
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.9.3
spacy                              2.2.4
Sphinx                             2.2.0
sphinxcontrib-applehelp            1.0.1
sphinxcontrib-devhelp              1.0.1
sphinxcontrib-htmlhelp             1.0.2
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.2
sphinxcontrib-serializinghtml      1.1.3
sphinxcontrib-websupport           1.1.2
spyder                             3.3.6
spyder-kernels                     0.5.2
SQLAlchemy                         1.3.9
srsly                              1.0.2
statsmodels                        0.12.0
sympy                              1.4
tables                             3.5.2
tangled-up-in-unicode              0.0.6
tblib                              1.4.0
tensorboard                        2.2.2
tensorboard-plugin-wit             1.6.0.post3
tensorflow                         2.2.0
tensorflow-estimator               2.2.0
termcolor                          1.1.0
terminado                          0.8.2
testpath                           0.4.2
textblob                           0.15.3
thinc                              7.4.0
threadpoolctl                      2.0.0
toolz                              0.10.0
tornado                            6.0.3
tqdm                               4.46.0
traitlets                          4.3.3
tweepy                             3.8.0
unicodecsv                         0.14.1
urllib3                            1.24.2
visions                            0.4.4
wasabi                             0.6.0
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.16.0
wheel                              0.34.2
widgetsnbextension                 3.5.1
wordcloud                          1.7.0
wrapt                              1.11.2
wurlitzer                          1.0.3
xgboost                            1.1.1
xlrd                               1.2.0
XlsxWriter                         1.2.1
xlwings                            0.15.10
xlwt                               1.3.0
xmltodict                          0.12.0
zict                               1.0.0
zipp                               0.6.0
zope.component                     4.6.2
zope.deferredimport                4.3.1
zope.deprecation                   4.4.0
zope.event                         4.5.0
zope.hookable                      5.0.1
zope.interface                     5.1.2
zope.lifecycleevent                4.3
zope.proxy                         4.3.5

**The output of jupyter labextension list**

jupyter labextension list
JupyterLab v1.1.4
Known labextensions:
   app dir: /opt/anaconda3/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.1.0  enabled  OK

Build recommended, please run `jupyter lab build`:
    @kiteco/jupyterlab-kite needs to be included in build

**Comment by its-dhung** [comment]
If you are still experiencing this issue, please re-open this issue with the full contents of the error you see when running `jupyter lab build`.
