### ISSUE TITLE
Kite vscode extension makes typescript react-dom fail to check

### ISSUE THREAD

**Issue by Songkeys** [kiteco/issue-tracker#426]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**

```
npx create-react-app cra-demo-ts --template typescript
code cra-demo-ts
```
![image](https://user-images.githubusercontent.com/22665058/95812385-d908be00-0d47-11eb-878c-1e00c1d42318.png)

Typescript can't recognise the react-dom's types. Take me a while to figure out that disabling kite plugin solves the problem.

logs:

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/340441/kite_local/client.log.2020-10-13_11-31-09-AM.bak.gz

- kite vscode extension version: 0.128.0
- vscode version: 1.50.0

**Screenshots**
See above.

**Comment by tonycheang** [comment]
Thanks for filing the issue! We did a new release that hopefully addresses this. If you update to `v0.129.0`, has this been fixed? If not you might try clicking "typescript" on the bottom bar. This should bring up a command menu. Try clicking "Auto Detect" and restarting VSCode to see if that changes the file type to "Typescript React".

If that doesn't resolve this, feel free to reopen and we can take another look.
