### ISSUE TITLE
High speed network usage

### ISSUE THREAD

**Issue by zifeiYv** [kiteco/issue-tracker#431]
I install for the first time in my MacBook Pro and it uses a high speed network (about 2M/s)to download something for quite a long time.

Is it normal? How much things does it need to download?

**Comment by metalogical** [comment]
Once Kite is installed, it should not need any network to get working, so if you're experiencing this sort of issue, it's not expected. Please confirm that Kite is the application causing this issue.

Then please attach logs (as described in the issue template). Read this guide on how to report an issue https://help.kite.com/article/96-contact-us-with-logs.

**Comment by zifeiYv** [comment]
> Once Kite is installed, it should not need any network to get working, so if you're experiencing this sort of issue, it's not expected. Please confirm that Kite is the application causing this issue.
> 
> Then please attach logs (as described in the issue template). Read this guide on how to report an issue https://help.kite.com/article/96-contact-us-with-logs.

The network speed will be reduced as I quit Kite, and become high again when I start Kite. So I guess it it Kite that cause this issue.

By the way, this high-speed-network state has already stop after it downloaded about 0.5G. Anyway, I'm going to close this issue
