### ISSUE TITLE
Kite Enginge backend not installed on remote server

### ISSUE THREAD

**Issue by ArefAz** [kiteco/issue-tracker#432]
Hi,

I am using Kite with vscode 1.49.2 on Ubuntu for developing Python on a remote server via SSH. Although I tried to install Kite multiple times on the server (via vscode itself and the `bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"`, I am not able to use the Kite features while working on the server. I should mention that I could install and use Kite on my own system without any problem. 

I would appreciate it if you could help me with this.

Thanks.

![image](https://user-images.githubusercontent.com/49265411/96330194-3fe7e900-1060-11eb-836b-a3311773597c.png)

**Comment by its-dhung** [comment]
Are you using VS Code's remote development feature? Kite doesn't currently support this.
