### ISSUE TITLE
(jupyter)TypeError: object Future can't be used in 'await' expression

### ISSUE THREAD

**Issue by Woncheol1905** [kiteco/issue-tracker#434]
I'm trying to install kite on my **ubuntu16.04LTS server.**
I installed kite engine and Kite Extension for JupyterLab.
But when I run jupyter lab, the kite is 'not running', 
![image](https://user-images.githubusercontent.com/65215248/96536062-34015e80-12ce-11eb-99dd-8d521092f2ff.png)

and the terminal show this error message:

[E 11:47:21.588 LabApp] <LspStdIoReader(parent=<LanguageServerSession(language_server=kitels, argv=['/home/ubuntu/.local/share/kite/current/kite-lsp'])>)> couldn't enqueue message: None
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/jupyter_kite/stdio.py", line 90, in read
        message = await self.read_one()
      File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/jupyter_kite/stdio.py", line 109, in read_one
        line = await convert_yielded(self._readline())
    TypeError: object Future can't be used in 'await' expression

**I'm using Python 3.6**,

**output of pip list**:
Package                            Version
alabaster                          0.7.10
anaconda-client                    1.6.14
anaconda-navigator                 1.8.7
anaconda-project                   0.8.2
asn1crypto                         0.24.0
astroid                            1.6.3
astropy                            3.0.2
attrs                              18.1.0
Babel                              2.5.3
backcall                           0.1.0
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.6.0
bitarray                           0.8.1
bkcharts                           0.2
blaze                              0.11.3
bleach                             2.1.3
bokeh                              0.12.16
boto                               2.48.0
Bottleneck                         1.2.1
certifi                            2019.11.28
cffi                               1.11.5
chardet                            3.0.4
click                              6.7
cloudpickle                        0.5.3
clyent                             1.2.2
colorama                           0.3.9
conda                              4.5.12
conda-build                        3.10.5
conda-verify                       2.0.0
contextlib2                        0.5.5
cryptography                       2.8
cycler                             0.10.0
Cython                             0.28.2
cytoolz                            0.9.0.1
dask                               0.17.5
datashape                          0.5.4
decorator                          4.3.0
distributed                        1.21.8
docutils                           0.14
entrypoints                        0.2.3
environment-kernels                1.1.1
et-xmlfile                         1.0.1
fastcache                          1.0.2
filelock                           3.0.4
Flask                              1.0.2
Flask-Cors                         3.0.4
gevent                             1.3.0
glob2                              0.6
gmpy2                              2.0.8
greenlet                           0.4.13
h5py                               2.7.1
heapdict                           1.0.0
html5lib                           1.0.1
idna                               2.6
imageio                            2.3.0
imagesize                          1.0.0
importlib-metadata                 2.0.0
ipykernel                          4.8.2
ipython                            6.4.0
ipython-genutils                   0.2.0
ipywidgets                         7.2.1
isort                              4.3.4
itsdangerous                       0.24
jdcal                              1.4
jedi                               0.12.0
Jinja2                             2.10
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     5.2.3
jupyter-console                    5.2.0
jupyter-core                       4.4.0
jupyter-kite                       1.1.0
jupyterlab                         2.2.8
jupyterlab-launcher                0.10.5
jupyterlab-server                  1.2.0
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
llvmlite                           0.23.1
locket                             0.2.0
lxml                               4.2.1
MarkupSafe                         1.0
matplotlib                         2.2.2
mccabe                             0.6.1
mistune                            0.8.3
mkl-fft                            1.0.0
mkl-random                         1.0.1
more-itertools                     4.1.0
mpmath                             1.0.0
msgpack                            1.0.0
msgpack-python                     0.5.6
multipledispatch                   0.5.0
navigator-updater                  0.2.1
nbconvert                          5.3.1
nbformat                           4.4.0
networkx                           2.1
nltk                               3.3
nose                               1.3.7
notebook                           5.5.0
numba                              0.38.0
numexpr                            2.6.5
numpy                              1.14.3
numpydoc                           0.8.0
odo                                0.5.1
olefile                            0.45.1
openpyxl                           2.5.3
packaging                          17.1
pandas                             0.23.0
pandocfilters                      1.4.2
parso                              0.2.0
partd                              0.3.8
path.py                            11.0.1
pathlib2                           2.3.2
patsy                              0.5.0
pep8                               1.7.1
pexpect                            4.5.0
pickleshare                        0.7.4
Pillow                             5.1.0
pip                                20.0.2
pkginfo                            1.4.2
pluggy                             0.6.0
ply                                3.11
prompt-toolkit                     1.0.15
psutil                             5.4.5
ptyprocess                         0.5.2
py                                 1.5.3
pycodestyle                        2.4.0
pycosat                            0.6.3
pycparser                          2.18
pycrypto                           2.6.1
pycurl                             7.43.0.1
pyflakes                           1.6.0
Pygments                           2.2.0
pylint                             1.8.4
pyodbc                             4.0.23
pyOpenSSL                          19.1.0
pyparsing                          2.2.0
pyrsistent                         0.17.3
PySocks                            1.6.8
pytest                             3.5.1
pytest-arraydiff                   0.2
pytest-astropy                     0.3.0
pytest-doctestplus                 0.1.3
pytest-openfiles                   0.3.0
pytest-remotedata                  0.2.1
python-dateutil                    2.7.3
pytz                               2018.4
PyWavelets                         0.5.2
PyYAML                             3.12
pyzmq                              17.0.0
QtAwesome                          0.4.4
qtconsole                          4.3.1
QtPy                               1.4.1
requests                           2.23.0
rope                               0.10.7
ruamel-yaml                        0.15.35
scikit-image                       0.13.1
scikit-learn                       0.19.1
scipy                              1.1.0
seaborn                            0.8.1
Send2Trash                         1.5.0
setuptools                         41.6.0.post20191030
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.11.0
snowballstemmer                    1.2.1
sortedcollections                  0.6.1
sortedcontainers                   1.5.10
Sphinx                             1.7.4
sphinxcontrib-websupport           1.0.1
spyder                             3.2.8
SQLAlchemy                         1.2.7
statsmodels                        0.9.0
sympy                              1.1.1
tables                             3.4.3
tblib                              1.3.2
terminado                          0.8.1
testpath                           0.3.1
toolz                              0.9.0
tornado                            5.0.2
traitlets                          4.3.2
typing                             3.6.4
unicodecsv                         0.14.1
urllib3                            1.25.8
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.14.1
wheel                              0.34.2
widgetsnbextension                 3.2.1
wrapt                              1.10.11
xlrd                               1.1.0
XlsxWriter                         1.0.4
xlwt                               1.3.0
zict                               0.1.3
zipp                               3.3.1

**output of jupyter labextension list**:
JupyterLab v2.2.8
Known labextensions:
   app dir: /home/ubuntu/anaconda3/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.2.0  enabled  OK
 

I'd appreciate it if you could tell me the answer..

**Comment by edzkite** [comment]
@Woncheol1905, 

Thanks for letting us know about this issue. A couple follow up questions:

- If you type anything in the notebook, are any other errors emitted in the terminal? 
- Could you also check the browser console logs and see if any errors appear?
- Does this happen if you restart JupyterLab and the browser session consistently?

**Comment by edzkite** [comment]
@Woncheol1905 Could you try upgrading to Tornado 5.1.0+? I found that anything less than that will cause this error.

**Comment by edzkite** [comment]
I'm pushed an update to `jupyter-kite` that will check for Tornado. Please upgrade to 1.2.0 when you have a chance.
