### ISSUE TITLE
RuntimeError: JupyterLab failed to build

### ISSUE THREAD

**Issue by tharakagalpaya** [kiteco/issue-tracker#436]
**Log**

Yarn configuration loaded.
Node v12.19.0

> "C:\Program Files\nodejs\npm.CMD" pack @kiteco/jupyterlab-kite
npm notice 
npm notice package: @kiteco/jupyterlab-kite@1.2.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE                                                    
npm notice 707B   style/variables/base.css                                   
npm notice 1.4kB  style/variables/cm-themes.css                              
npm notice 423B   style/console.css                                          
npm notice 1.7kB  style/diagnostics_listing.css                              
npm notice 1.8kB  style/highlight.css                                        
npm notice 567B   style/index.css                                            
npm notice 131B   style/variables/jupyterlab-dark.css                        
npm notice 128B   style/variables/jupyterlab-light.css                       
npm notice 1.1kB  style/kite_accessible.css                                  
npm notice 374B   style/logo.css                                             
npm notice 68B    style/statusbar.css                                        
npm notice 68B    src/babel.config.js                                        
npm notice 2.7kB  lib/adapters/codemirror/cm_adapter.js                      
npm notice 2.1kB  lib/adapters/codemirror/cm_adapter.spec.js                 
npm notice 6.7kB  lib/command_manager.js                                     
npm notice 1.8kB  lib/command_manager.spec.js                                
npm notice 1.9kB  lib/adapters/codemirror/features/completion.js             
npm notice 16.9kB lib/adapters/jupyterlab/components/completion.js           
npm notice 10.7kB lib/connection_manager.js                                  
npm notice 4.9kB  lib/connection.js                                          
npm notice 1.4kB  lib/virtual/console.js                                     
npm notice 480B   lib/converter.js                                           
npm notice 4.2kB  lib/extractors/defaults.js                                 
npm notice 5.1kB  lib/magics/defaults.js                                     
npm notice 4.0kB  lib/extractors/defaults.spec.js                            
npm notice 4.2kB  lib/magics/defaults.spec.js                                
npm notice 9.4kB  lib/adapters/codemirror/features/diagnostics_listing.js    
npm notice 14.9kB lib/adapters/codemirror/features/diagnostics.js            
npm notice 10.3kB lib/adapters/codemirror/features/diagnostics.spec.js       
npm notice 21.2kB lib/virtual/document.js                                    
npm notice 8.1kB  lib/virtual/document.spec.js                               
npm notice 6.7kB  lib/virtual/editor.js                                      
npm notice 5.6kB  lib/virtual/editor.spec.js                                 
npm notice 14.1kB lib/adapters/codemirror/feature.js                         
npm notice 10.4kB lib/adapters/codemirror/feature.spec.js                    
npm notice 2.3kB  lib/adapters/jupyterlab/file_editor.js                     
npm notice 1.7kB  lib/virtual/editors/file_editor.js                         
npm notice 2.1kB  lib/adapters/jupyterlab/components/free_tooltip.js         
npm notice 3.6kB  lib/adapters/codemirror/features/highlights.js             
npm notice 7.9kB  lib/adapters/codemirror/features/hover.js                  
npm notice 6.9kB  lib/index.js                                               
npm notice 19.1kB lib/adapters/jupyterlab/jl_adapter.js                      
npm notice 4.9kB  lib/adapters/codemirror/features/jump_to.js                
npm notice 9.4kB  lib/kite_accessible.js                                     
npm notice 1.4kB  lib/kite_commands.js                                       
npm notice 1.2kB  lib/adapters/jupyterlab/kite_completer.js                  
npm notice 19.4kB lib/adapters/jupyterlab/kite_model.js                      
npm notice 1.9kB  lib/kite_onboarding.js                                     
npm notice 2.8kB  lib/lsp.js                                                 
npm notice 2.2kB  lib/manager.js                                             
npm notice 1.7kB  lib/magics/maps.js                                         
npm notice 5.8kB  lib/adapters/jupyterlab/notebook.js                        
npm notice 9.3kB  lib/virtual/editors/notebook.js                            
npm notice 37B    lib/magics/overrides.js                                    
npm notice 1.1kB  lib/positioning.js                                         
npm notice 2.8kB  lib/positioning.spec.js                                    
npm notice 3.4kB  lib/extractors/regexp.js                                   
npm notice 7.6kB  lib/extractors/regexp.spec.js                              
npm notice 4.3kB  lib/adapters/codemirror/features/rename.js                 
npm notice 1.5kB  lib/adapters/codemirror/features/rename.spec.js            
npm notice 2.7kB  lib/magics/rpy2.js                                         
npm notice 3.9kB  lib/magics/rpy2.spec.js                                    
npm notice 1.7kB  lib/adapters/codemirror/features/selection.js              
npm notice 4.4kB  lib/adapters/codemirror/features/signature.js              
npm notice 4.6kB  lib/adapters/jupyterlab/components/status_model.js         
npm notice 1.6kB  lib/adapters/jupyterlab/components/statusbar.js            
npm notice 6.2kB  lib/adapters/codemirror/testutils.js                       
npm notice 210B   lib/tokens.js                                              
npm notice 33B    lib/extractors/types.js                                    
npm notice 3.4kB  lib/utils.js                                               
npm notice 3.9kB  package.json                                               
npm notice 2.5kB  lib/adapters/codemirror/cm_adapter.js.map                  
npm notice 1.9kB  lib/adapters/codemirror/cm_adapter.spec.js.map             
npm notice 5.5kB  lib/command_manager.js.map                                 
npm notice 1.9kB  lib/command_manager.spec.js.map                            
npm notice 1.3kB  lib/adapters/codemirror/features/completion.js.map         
npm notice 11.7kB lib/adapters/jupyterlab/components/completion.js.map       
npm notice 8.0kB  lib/connection_manager.js.map                              
npm notice 4.4kB  lib/connection.js.map                                      
npm notice 1.7kB  lib/virtual/console.js.map                                 
npm notice 629B   lib/converter.js.map                                       
npm notice 2.9kB  lib/extractors/defaults.js.map                             
npm notice 3.2kB  lib/magics/defaults.js.map                                 
npm notice 3.8kB  lib/extractors/defaults.spec.js.map                        
npm notice 3.4kB  lib/magics/defaults.spec.js.map                            
npm notice 9.2kB  lib/adapters/codemirror/features/diagnostics_listing.js.map
npm notice 10.4kB lib/adapters/codemirror/features/diagnostics.js.map        
npm notice 8.7kB  lib/adapters/codemirror/features/diagnostics.spec.js.map   
npm notice 15.9kB lib/virtual/document.js.map                                
npm notice 6.4kB  lib/virtual/document.spec.js.map                           
npm notice 4.6kB  lib/virtual/editor.js.map                                  
npm notice 4.9kB  lib/virtual/editor.spec.js.map                             
npm notice 11.1kB lib/adapters/codemirror/feature.js.map                     
npm notice 8.0kB  lib/adapters/codemirror/feature.spec.js.map                
npm notice 2.2kB  lib/adapters/jupyterlab/file_editor.js.map                 
npm notice 1.5kB  lib/virtual/editors/file_editor.js.map                     
npm notice 1.8kB  lib/adapters/jupyterlab/components/free_tooltip.js.map     
npm notice 2.9kB  lib/adapters/codemirror/features/highlights.js.map         
npm notice 5.8kB  lib/adapters/codemirror/features/hover.js.map              
npm notice 5.5kB  lib/index.js.map                                           
npm notice 12.9kB lib/adapters/jupyterlab/jl_adapter.js.map                  
npm notice 3.5kB  lib/adapters/codemirror/features/jump_to.js.map            
npm notice 5.5kB  lib/kite_accessible.js.map                                 
npm notice 1.3kB  lib/kite_commands.js.map                                   
npm notice 1.0kB  lib/adapters/jupyterlab/kite_completer.js.map              
npm notice 13.5kB lib/adapters/jupyterlab/kite_model.js.map                  
npm notice 1.8kB  lib/kite_onboarding.js.map                                 
npm notice 1.8kB  lib/lsp.js.map                                             
npm notice 2.2kB  lib/manager.js.map                                         
npm notice 1.8kB  lib/magics/maps.js.map                                     
npm notice 4.9kB  lib/adapters/jupyterlab/notebook.js.map                    
npm notice 8.2kB  lib/virtual/editors/notebook.js.map                        
npm notice 120B   lib/magics/overrides.js.map                                
npm notice 1.1kB  lib/positioning.js.map                                     
npm notice 3.8kB  lib/positioning.spec.js.map                                
npm notice 2.8kB  lib/extractors/regexp.js.map                               
npm notice 7.0kB  lib/extractors/regexp.spec.js.map                          
npm notice 3.4kB  lib/adapters/codemirror/features/rename.js.map             
npm notice 1.6kB  lib/adapters/codemirror/features/rename.spec.js.map        
npm notice 2.9kB  lib/magics/rpy2.js.map                                     
npm notice 3.4kB  lib/magics/rpy2.spec.js.map                                
npm notice 1.3kB  lib/adapters/codemirror/features/selection.js.map          
npm notice 3.4kB  lib/adapters/codemirror/features/signature.js.map          
npm notice 3.9kB  lib/adapters/jupyterlab/components/status_model.js.map     
npm notice 1.4kB  lib/adapters/jupyterlab/components/statusbar.js.map        
npm notice 5.7kB  lib/adapters/codemirror/testutils.js.map                   
npm notice 220B   lib/tokens.js.map                                          
npm notice 116B   lib/extractors/types.js.map                                
npm notice 2.8kB  lib/utils.js.map                                           
npm notice 486B   style/icons/kite-logo.svg                                  
npm notice 7.0kB  src/_schema.d.ts                                           
npm notice 886B   lib/adapters/codemirror/cm_adapter.d.ts                    
npm notice 11B    lib/adapters/codemirror/cm_adapter.spec.d.ts               
npm notice 2.3kB  src/adapters/codemirror/cm_adapter.spec.ts                 
npm notice 2.9kB  src/adapters/codemirror/cm_adapter.ts                      
npm notice 3.6kB  lib/command_manager.d.ts                                   
npm notice 11B    lib/command_manager.spec.d.ts                              
npm notice 1.9kB  src/command_manager.spec.ts                                
npm notice 7.7kB  src/command_manager.ts                                     
npm notice 309B   lib/adapters/codemirror/features/completion.d.ts           
npm notice 3.2kB  lib/adapters/jupyterlab/components/completion.d.ts         
npm notice 1.9kB  src/adapters/codemirror/features/completion.ts             
npm notice 17.7kB src/adapters/jupyterlab/components/completion.ts           
npm notice 3.3kB  lib/connection_manager.d.ts                                
npm notice 12.0kB src/connection_manager.ts                                  
npm notice 1.5kB  lib/connection.d.ts                                        
npm notice 5.6kB  src/connection.ts                                          
npm notice 734B   lib/virtual/console.d.ts                                   
npm notice 1.7kB  src/virtual/console.ts                                     
npm notice 497B   lib/converter.d.ts                                         
npm notice 743B   src/converter.ts                                           
npm notice 134B   lib/extractors/defaults.d.ts                               
npm notice 581B   lib/magics/defaults.d.ts                                   
npm notice 11B    lib/extractors/defaults.spec.d.ts                          
npm notice 11B    lib/magics/defaults.spec.d.ts                              
npm notice 3.9kB  src/extractors/defaults.spec.ts                            
npm notice 4.0kB  src/magics/defaults.spec.ts                                
npm notice 3.8kB  src/extractors/defaults.ts                                 
npm notice 4.5kB  src/magics/defaults.ts                                     
npm notice 2.6kB  lib/adapters/codemirror/features/diagnostics_listing.d.ts  
npm notice 1.8kB  lib/adapters/codemirror/features/diagnostics.d.ts          
npm notice 11B    lib/adapters/codemirror/features/diagnostics.spec.d.ts     
npm notice 9.0kB  src/adapters/codemirror/features/diagnostics.spec.ts       
npm notice 14.8kB src/adapters/codemirror/features/diagnostics.ts            
npm notice 8.0kB  lib/virtual/document.d.ts                                  
npm notice 11B    lib/virtual/document.spec.d.ts                             
npm notice 8.0kB  src/virtual/document.spec.ts                               
npm notice 24.3kB src/virtual/document.ts                                    
npm notice 4.4kB  lib/virtual/editor.d.ts                                    
npm notice 11B    lib/virtual/editor.spec.d.ts                               
npm notice 6.0kB  src/virtual/editor.spec.ts                                 
npm notice 8.4kB  src/virtual/editor.ts                                      
npm notice 5.0kB  lib/adapters/codemirror/feature.d.ts                       
npm notice 11B    lib/adapters/codemirror/feature.spec.d.ts                  
npm notice 9.6kB  src/adapters/codemirror/feature.spec.ts                    
npm notice 16.4kB src/adapters/codemirror/feature.ts                         
npm notice 1.8kB  lib/adapters/jupyterlab/file_editor.d.ts                   
npm notice 946B   lib/virtual/editors/file_editor.d.ts                       
npm notice 3.3kB  src/adapters/jupyterlab/file_editor.ts                     
npm notice 2.2kB  src/virtual/editors/file_editor.ts                         
npm notice 785B   lib/adapters/jupyterlab/components/free_tooltip.d.ts       
npm notice 2.4kB  src/adapters/jupyterlab/components/free_tooltip.ts         
npm notice 591B   lib/adapters/codemirror/features/highlights.d.ts           
npm notice 3.4kB  src/adapters/codemirror/features/highlights.ts             
npm notice 1.3kB  lib/adapters/codemirror/features/hover.d.ts                
npm notice 8.1kB  src/adapters/codemirror/features/hover.ts                  
npm notice 257B   lib/index.d.ts                                             
npm notice 6.7kB  src/index.ts                                               
npm notice 6.9kB  lib/adapters/jupyterlab/jl_adapter.d.ts                    
npm notice 21.0kB src/adapters/jupyterlab/jl_adapter.ts                      
npm notice 599B   lib/adapters/codemirror/features/jump_to.d.ts              
npm notice 4.6kB  src/adapters/codemirror/features/jump_to.ts                
npm notice 848B   lib/kite_accessible.d.ts                                   
npm notice 544B   lib/kite_commands.d.ts                                     
npm notice 1.5kB  src/kite_commands.ts                                       
npm notice 635B   lib/adapters/jupyterlab/kite_completer.d.ts                
npm notice 1.2kB  src/adapters/jupyterlab/kite_completer.ts                  
npm notice 5.5kB  lib/adapters/jupyterlab/kite_model.d.ts                    
npm notice 19.0kB src/adapters/jupyterlab/kite_model.ts                      
npm notice 781B   lib/kite_onboarding.d.ts                                   
npm notice 2.4kB  src/kite_onboarding.ts                                     
npm notice 1.7kB  lib/lsp.d.ts                                               
npm notice 2.2kB  src/lsp.ts                                                 
npm notice 642B   lib/manager.d.ts                                           
npm notice 2.7kB  src/manager.ts                                             
npm notice 1.1kB  lib/magics/maps.d.ts                                       
npm notice 2.1kB  src/magics/maps.ts                                         
npm notice 2.3kB  lib/adapters/jupyterlab/notebook.d.ts                      
npm notice 3.7kB  lib/virtual/editors/notebook.d.ts                          
npm notice 7.0kB  src/adapters/jupyterlab/notebook.ts                        
npm notice 11.2kB src/virtual/editors/notebook.ts                            
npm notice 532B   lib/magics/overrides.d.ts                                  
npm notice 516B   src/magics/overrides.ts                                    
npm notice 856B   lib/positioning.d.ts                                       
npm notice 11B    lib/positioning.spec.d.ts                                  
npm notice 2.6kB  src/positioning.spec.ts                                    
npm notice 1.6kB  src/positioning.ts                                         
npm notice 2.6kB  lib/extractors/regexp.d.ts                                 
npm notice 11B    lib/extractors/regexp.spec.d.ts                            
npm notice 6.8kB  src/extractors/regexp.spec.ts                              
npm notice 5.5kB  src/extractors/regexp.ts                                   
npm notice 350B   lib/adapters/codemirror/features/rename.d.ts               
npm notice 11B    lib/adapters/codemirror/features/rename.spec.d.ts          
npm notice 1.4kB  src/adapters/codemirror/features/rename.spec.ts            
npm notice 4.4kB  src/adapters/codemirror/features/rename.ts                 
npm notice 707B   lib/magics/rpy2.d.ts                                       
npm notice 11B    lib/magics/rpy2.spec.d.ts                                  
npm notice 3.6kB  src/magics/rpy2.spec.ts                                    
npm notice 2.5kB  src/magics/rpy2.ts                                         
npm notice 223B   lib/adapters/codemirror/features/selection.d.ts            
npm notice 1.5kB  src/adapters/codemirror/features/selection.ts              
npm notice 934B   lib/adapters/codemirror/features/signature.d.ts            
npm notice 4.4kB  src/adapters/codemirror/features/signature.ts              
npm notice 1.4kB  lib/adapters/jupyterlab/components/status_model.d.ts       
npm notice 4.4kB  src/adapters/jupyterlab/components/status_model.ts         
npm notice 466B   lib/adapters/jupyterlab/components/statusbar.d.ts          
npm notice 74B    src/svg.d.ts                                               
npm notice 3.4kB  lib/adapters/codemirror/testutils.d.ts                     
npm notice 7.5kB  src/adapters/codemirror/testutils.ts                       
npm notice 879B   lib/tokens.d.ts                                            
npm notice 845B   src/tokens.ts                                              
npm notice 2.3kB  lib/extractors/types.d.ts                                  
npm notice 2.3kB  src/extractors/types.ts                                    
npm notice 166B   src/typings.d.ts                                           
npm notice 1.3kB  lib/utils.d.ts                                             
npm notice 3.3kB  src/utils.ts                                               
npm notice 10.0kB src/adapters/codemirror/features/diagnostics_listing.tsx   
npm notice 11.0kB src/kite_accessible.tsx                                    
npm notice 1.7kB  src/adapters/jupyterlab/components/statusbar.tsx           
npm notice === Tarball Details === 
npm notice name:          @kiteco/jupyterlab-kite                 
npm notice version:       1.2.0                                   
npm notice filename:      kiteco-jupyterlab-kite-1.2.0.tgz        
npm notice package size:  222.1 kB                                
npm notice unpacked size: 1.0 MB                                  
npm notice shasum:        d7e92c39c7f8bff080937de27ff7a234fbd170b3
npm notice integrity:     sha512-GiUGpLJ7s+H6q[...]flkUHXrldLOxQ==
npm notice total files:   250                                     
npm notice 
kiteco-jupyterlab-kite-1.2.0.tgz

Yarn configuration loaded.
Node v12.19.0

Building jupyterlab assets (build:prod:minimize)
> node "C:\Users\nekma - tharaka\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js" install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.44s.

> node "C:\Users\nekma - tharaka\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js" yarn-deduplicate -s fewer
yarn run v1.15.2
$ "C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate" -s fewer
Done in 0.32s.

> node "C:\Users\nekma - tharaka\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js" run build:prod:minimize
yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab/settingregistry' in 'C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\lib'
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\Compilation.js:925:10
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\neo-async\async.js:2830:7
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\neo-async\async.js:6877:13
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:184:12
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:26:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:23:37
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\forEachBail.js:30:14
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
resolve '@jupyterlab/settingregistry' in 'C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\lib'
  Parsed request is a module
  using description file: C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\lib\node_modules doesn't exist or is not a directory
      C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\node_modules doesn't exist or is not a directory
      C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\node_modules doesn't exist or is not a directory
      C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\node_modules doesn't exist or is not a directory
      C:\Users\nekma - tharaka\anaconda3\share\jupyter\node_modules doesn't exist or is not a directory
      C:\Users\nekma - tharaka\anaconda3\share\node_modules doesn't exist or is not a directory
      C:\Users\nekma - tharaka\anaconda3\node_modules doesn't exist or is not a directory
      C:\Users\nekma - tharaka\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\node_modules
        using description file: C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules
        using description file: C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\package.json (relative path: ./node_modules/@jupyterlab/settingregistry)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\package.json (relative path: ./node_modules/@jupyterlab/settingregistry)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\node_modules\@jupyterlab\settingregistry doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\settingregistry doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\node_modules\@jupyterlab\settingregistry.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\settingregistry.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\node_modules\@jupyterlab\settingregistry.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\settingregistry.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\node_modules\@jupyterlab\settingregistry.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\settingregistry.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\node_modules\@jupyterlab\settingregistry.json doesn't exist
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\settingregistry.json doesn't exist
            as directory
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@kiteco\jupyterlab-kite\node_modules\@jupyterlab\settingregistry doesn't exist
            as directory
              C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\settingregistry doesn't exist
child_process.js:656
    throw err;
    ^

Error: Command failed: C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\.bin\webpack.CMD --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at Object.<anonymous> (C:\Users\nekma - tharaka\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13200,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "C:\Users\nekma - tharaka\anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\nekma - tharaka\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "C:\Users\nekma - tharaka\anaconda3\lib\site-packages\jupyterlab\commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "C:\Users\nekma - tharaka\anaconda3\lib\site-packages\jupyterlab\commands.py", line 669, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter

**Comment by edzkite** [comment]
@tharakagalpaya Could you try this? https://github.com/jupyterlab/jupyterlab/issues/5177#issuecomment-415733918

Also, ensure you have `jupyterlab` installed as well.

**Comment by tharakagalpaya** [comment]
Thanks for the reply.I have already fixed the issue.
