### ISSUE TITLE
I can't activate Kite Pro

### ISSUE THREAD

**Issue by jxxiao** [kiteco/issue-tracker#437]
![image](https://user-images.githubusercontent.com/15158054/96545824-b5abb900-12db-11eb-9a0a-0cdcec9e3e9d.png)
![image](https://user-images.githubusercontent.com/15158054/96545951-fa375480-12db-11eb-80fb-c321d6dabb2e.png)
![image](https://user-images.githubusercontent.com/15158054/96545872-d07e2d80-12db-11eb-973c-f0351ae19f95.png)

**Comment by metalogical** [comment]
Hi @jxxiao 

We had a problem with a bad release over the weekend that caused this. If you update to the most recent version of Kite, this should be resolved. Apologies for the inconvenience!

If you have other questions, feel free to reach out.

**Comment by MarkoShiva** [comment]
I have similar issue where my pro subscription is not activated. 
![Screenshot from 2021-02-01 18-46-39](https://user-images.githubusercontent.com/993923/106497309-2909bd00-64be-11eb-971a-5a54d5ec41e0.png)

**Comment by metalogical** [comment]
@MarkoShiva please email us directly at feedback@kite.com with

- the email address on your Kite account, and
- the version of Kite you have installed (you can check this by looking at the bottom of the copilot settings page)
