### ISSUE TITLE
jupyterlab extension "Kite: initializing"

### ISSUE THREAD

**Issue by Jacques2101** [kiteco/issue-tracker#439]
I don't know why but now I have a message "Kite: initializing" inside jupyterlab bar (cf. screenshot). 

I am using Version 2.2.8 of jupyterlab. 

I tried to delete the extensions and reinstall it completely with : 
```
pip uninstall jupyter-kite   
jupyter labextension uninstall @kiteco/jupyterlab-kite
```

and reinstall with : 
```
pip install jupyter-kite   
jupyter labextension install @kiteco/jupyterlab-kite
```

but now it does not appear anymore in the bar status...:((
whereas it is installed as you can see here : 
JupyterLab v2.2.8
Known labextensions:
   app dir: /Users/jacques/opt/anaconda3/envs/Data/share/jupyter/lab
        @aquirdturtle/collapsible_headings v2.2.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.3.4  enabled  OK
        @jupyterlab/shortcutui v0.5.0-beta.2  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @karosc/jupyterlab_dracula v2.0.3  enabled  OK
        **@kiteco/jupyterlab-kite v1.2.0  enabled  OK**
        @krassowski/jupyterlab_go_to_definition v1.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.1  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.6  enabled  OK
        @telamonian/theme-darcula v2.0.0  enabled  OK
        jupyterlab-chart-editor v4.10.0  enabled  OK
        jupyterlab-code-snippets v1.0.4  enabled  OK
        jupyterlab-dash v0.3.0  enabled  OK
        jupyterlab-execute-time v1.0.0  enabled  OK
        jupyterlab-logout v0.5.0  enabled  OK
        jupyterlab-plotly v4.11.0  enabled  OK
        jupyterlab-python-file v0.4.0  enabled  OK
        jupyterlab-skip-traceback v3.0.0  enabled  OK
        jupyterlab-spreadsheet v0.3.2  enabled  OK
        jupyterlab-system-monitor v0.6.0  enabled  OK
        jupyterlab-theme-solarized-dark v1.0.2  enabled  OK
        jupyterlab-theme-toggle v0.5.0  enabled  OK
        jupyterlab-topbar-extension v0.5.0  enabled  OK
        jupyterlab-topbar-text v0.5.1  enabled  OK
        jupyterlab_filetree v0.2.2  enabled  OK
        plotlywidget v4.11.0  enabled  OK
        run-tag-cells-jlab v0.1.3  enabled  OK

Uninstalled core extensions:
    @kiteco/jupyterlab-kite
    @krassowski/jupyterlab-lsp
    @krassowski/jupyterlab_go_to_definition

### update 
**_Ok now I have it again after deleting build_config.json file but still have "initializing" in the bar and not "ready" as should tie the case I think_** 

Thx for your help 

Screenshot bar of jupyterlab with "initialising" message :
<img width="1318" alt="Capture d’écran 2020-10-21 à 13 05 44" src="https://user-images.githubusercontent.com/49912455/96711647-2e734980-139e-11eb-8e3f-cd1e4ba9b67a.png">

Screenshot bar of jupyterlab after reinstallation of kite extension  :
<img width="1125" alt="Capture d’écran 2020-10-21 à 17 21 24" src="https://user-images.githubusercontent.com/49912455/96741330-f7169400-13c1-11eb-834c-00000f33e33c.png">

**Comment by edzkite** [comment]
@Jacques2101 Thanks for writing in. When it says "initializing", Kite is creating an index of your project, which may take a bit of time, but is expected. During that time, completions should still return. Is that not the case?

**Comment by Jacques2101** [comment]
Yes. It works but I thought it should be "ready". So everything is ok I suppose.

**Comment by tonycheang** [comment]
The initializing status should change to ready after a short while (maybe 20 seconds or so). Does that happen?

**Comment by Jacques2101** [comment]
No. It's always on "initializing" even after 3-4 minutes.

**Comment by Jacques2101** [comment]
The same more than 1h after

**Comment by edzkite** [comment]
While this shouldn't affect your experience with Kite, it is puzzling why the initialization is taking so long. Do you have any other Kite supported IDEs on your system? If you opened the same project, does it say initializing as well? Alternatively, if you open a different notebook or python file, does the status change?

**Comment by Jacques2101** [comment]
No. The same !

**Comment by edzkite** [comment]
In other editors or different files in JupyterLab?

**Comment by Jacques2101** [comment]
with others project with jupyterlab. 
I don't use others ide. I Tried to launch Spyder and it seems that "Kite : Ready" appeared.

**Comment by Jacques2101** [comment]
it is on "ready" this morning !!! strange
 thx
