### ISSUE TITLE
pro version features in pycharm are different with demos in official websites.

### ISSUE THREAD

**Issue by JiayuMaoReal** [kiteco/issue-tracker#442]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [x] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.
The intelligent snippets feature demonstrates differently with demo in official websites.
The choices in autocompletion are without '<>'. When I choose one of them, it won't show another level of choices automatically like the demo.
How to fix it or how to update if there is the new features in the latestest version.
**Screenshots**
different appearences in offered choices.
without '<>'
![图像 022](https://user-images.githubusercontent.com/69234314/97070986-67662500-160f-11eb-94c0-740a15cfdc60.png)
with '<>'
![图像 023](https://user-images.githubusercontent.com/69234314/97071004-849af380-160f-11eb-82e8-76c72d4141b5.png)
does not show drop-down menu
![图像 025](https://user-images.githubusercontent.com/69234314/97071076-27537200-1610-11eb-8451-817b53a27858.png)
show drop-down menu automatically
![图像 024](https://user-images.githubusercontent.com/69234314/97071101-5833a700-1610-11eb-913b-fff5b5c6cafd.png)

**Comment by JiayuMaoReal** [comment]
pycharm2020.2
kite Version: 1.2020.1022.0

**Comment by its-dhung** [comment]
The demo videos are actually outdated.
