### ISSUE TITLE
Asking me to install kit engine even when installed

### ISSUE THREAD

**Issue by Yuvraj15101999** [kiteco/issue-tracker#444]
**Required Information**

**Describe the bug**
Asking me to **install kit engine even when it is installed**

**Screenshots**
![kite issue](https://user-images.githubusercontent.com/48157851/97080456-14916b00-1619-11eb-9d69-1b3118b37cda.jpg)

**Comment by its-dhung** [comment]
Assuming you're using Windows, what is the output of this command in command prompt?

```
reg query "HKEY_LOCAL_MACHINE\Software\Kite\AppData" /v InstallPath /s /reg:64
```

**Comment by Yuvraj15101999** [comment]
Thank you I finally solved the problem by simply reinstalling the Kite Launcher
