### ISSUE TITLE
Jupyter Lab - Kite not working

### ISSUE THREAD

**Issue by TheCodeCow** [kiteco/issue-tracker#445]
**Describe the bug**
i've been trying to install Kite in JupyterLab v2.2.6 (Anaconda). I have dowloaded and installed Kite, have node.js 15.0.1 and i've run the console commands:

pip install jupyter-kite
jupyter labextension install "@kiteco/jupyterlab-kite"

i have no problems with either and when i check in jupyter extension manager it tells me that it is installed
![Sin título](https://user-images.githubusercontent.com/73436236/97113325-f9c60180-16bf-11eb-8313-7a51be32d199.png)

I have VsCode and Pycharm and kite seems to be working fine in both
I'm using Windows10

**Logs**
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/533748/kite_local/client.log.2020-10-25_12-42-29-PM.bak.gz

**pip install jupyter-kite**
(base) C:\Users\Usuario>pip install jupyter-kite
Requirement already satisfied: jupyter-kite in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: setuptools in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from jupyter-kite) (50.3.0.post20201006)
Requirement already satisfied: notebook>=4.3.1 in c:\users\usuario\appdata\roaming\python\python38\site-packages (from jupyter-kite) (6.1.4)
Requirement already satisfied: tornado>=5.1.0 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from jupyter-kite) (6.0.4)
Requirement already satisfied: traitlets>=4.2.1 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (4.3.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.9.1)
Requirement already satisfied: prometheus-client in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.8.0)
Requirement already satisfied: argon2-cffi in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (20.1.0)
Requirement already satisfied: jinja2 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (2.11.2)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (4.6.3)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.1.7)
Requirement already satisfied: Send2Trash in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (1.5.0)
Requirement already satisfied: ipykernel in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.3.4)
Requirement already satisfied: nbconvert in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (6.0.7)
Requirement already satisfied: ipython-genutils in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (0.2.0)
Requirement already satisfied: pyzmq>=17 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (19.0.2)
Requirement already satisfied: nbformat in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from notebook>=4.3.1->jupyter-kite) (5.0.8)
Requirement already satisfied: six in c:\users\usuario\appdata\roaming\python\python38\site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyter-kite) (1.15.0)
Requirement already satisfied: decorator in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyter-kite) (4.4.2)
Requirement already satisfied: pywinpty>=0.5 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=4.3.1->jupyter-kite) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.3.1->jupyter-kite) (1.14.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from jinja2->notebook>=4.3.1->jupyter-kite) (1.1.1)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from jupyter-core>=4.6.1->notebook>=4.3.1->jupyter-kite) (227)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyter-kite) (2.8.1)
Requirement already satisfied: ipython>=5.0.0 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from ipykernel->notebook>=4.3.1->jupyter-kite) (7.18.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.1.2)
Requirement already satisfied: testpath in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.4.4)
Requirement already satisfied: defusedxml in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.6.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.2)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.3)
Requirement already satisfied: pygments>=2.4.1 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (2.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (0.8.4)
Requirement already satisfied: bleach in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyter-kite) (3.2.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbformat->notebook>=4.3.1->jupyter-kite) (3.2.0)
Requirement already satisfied: pycparser in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.3.1->jupyter-kite) (2.20)
Requirement already satisfied: jedi>=0.10 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.17.1)
Requirement already satisfied: pickleshare in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.5)
Requirement already satisfied: backcall in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\usuario\appdata\roaming\python\python38\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.4.4)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (3.0.8)
Requirement already satisfied: async-generator in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.3.1->jupyter-kite) (1.10)
Requirement already satisfied: nest-asyncio in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.3.1->jupyter-kite) (1.4.1)
Requirement already satisfied: webencodings in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (0.5.1)
Requirement already satisfied: packaging in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (20.4)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.3.1->jupyter-kite) (20.2.0)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.7.0)
Requirement already satisfied: wcwidth in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyter-kite) (0.2.5)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\usuario\downloads\code\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.3.1->jupyter-kite) (2.4.7)

**jupyter labextension install "@kiteco/jupyterlab-kite"**
(base) C:\Users\Usuario>jupyter labextension install "@kiteco/jupyterlab-kite"
Building jupyterlab assets (build:prod:minimize)

**image of the kite message i get in jupyter-lab**
![kite error](https://user-images.githubusercontent.com/73436236/97221322-1d15ad00-17a3-11eb-93f0-9a020f8fb1e1.png)

** kite status inside jupyter-lab**
![kite not running](https://user-images.githubusercontent.com/73436236/97222050-23f0ef80-17a4-11eb-9a11-8fbf219a4098.png)

Thanks for the help, excuse my grammar, I am not native

**Comment by edzkite** [comment]
@TheCodeCow 

- Do you see any errors in your browser console logs?
- Do you see any errors in the terminal window when you launch `jupyter lab`?
- What's the output of `jupyter labextension list` and `jupyter serverextension list`?

**Comment by TheCodeCow** [comment]
Thanks for the repply @edzkite !!

I have no console errors in my console or in the jupyter lab terminal

jupyter labextension list output:

 Uninstalled core extensions:
   @kiteco/jupyterlab-kite

jupyter serverextension list:
    jupyter_kite enabled
    - Validating...
      jupyter_kite 1.2.0 ok
    jupyterlab enabled
    - Validating...
      jupyterlab 2.2.6 ok
    jupyter_nbextensions_configurator enabled
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok

**Comment by edzkite** [comment]
Thanks @TheCodeCow.

It looks like you uninstalled the extension @kiteco/jupyterlab-kite. Could you try reinstalling it and then checking for any errors, both in the console and in the terminal? Also, ensure that the Kite desktop application is running along with Jupyter Lab.

**Comment by TheOther-Guy** [comment]
I have the same problem, did you find any solutions?

**Comment by bala-srm** [comment]
I have the same issue. kite desktop is installed and running and showing in jupyterlab console. I have uninstalled and reinstalled kite extension and the output of  jupyter serverextension list is given below:
config dir: C:\Users\alabm\.jupyter
    jupyter_nbextensions_configurator enabled
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok
config dir: C:\Users\alabm\anaconda3\etc\jupyter
    jupyter_kite enabled
    - Validating...
      jupyter_kite 1.2.0 ok
    jupyterlab enabled
    - Validating...
      jupyterlab 2.2.6 ok

I don't even get the Kite: not running status on the status bar of jupyter lab

**Comment by edzkite** [comment]
@TheOther-Guy @bala-srm Could you please upload a screenshot of your browser console logs when you launch JupyterLab? Also, please ensure you have a .py or .ipynb file active, otherwise, the Kite logo will not appear.

**Comment by bala-srm** [comment]
> @TheOther-Guy @bala-srm Could you please upload a screenshot of your browser console logs when you launch JupyterLab? Also, please ensure you have a .py or .ipynb file active, otherwise, the Kite logo will not appear.

I uninstalled anaconda and python and kite and resinstalled kite again. Now I am getting "kite not running" in the jupyter lab statis bar, even though kite desktop app is running.
Not sure what you mean by browser console. Sorry I am new to this. Probably you mean the output when I execute "jupyter lab" in the anaconda prompt . If yes the screenshot is below:
![image](https://user-images.githubusercontent.com/53083124/97403582-b1eee680-191a-11eb-8719-1e24a1de61c6.png)

**Comment by TheCodeCow** [comment]
Thanks @edzkite, but the issue keeps persisiting. I reinstalled kite with `pip install jupyter kite` and i i stopped getting the kite status bar in jupyter even with the desktop aplication open and running. I get this in the anaconda prompt:
```
(jupyterlab) C:\Users\Usuario>jupyter labextension install "@kiteco/jupyterlab-kite"
Building jupyterlab assets (build:prod:minimize)
-
(jupyterlab) C:\Users\Usuario>
```
Checking for errors with `jupyter labextension list`:
```

Known labextensions:
   app dir: C:\Users\Usuario\Downloads\Code\Anaconda3\envs\jupyterlab\share\jupyter\lab
        @kiteco/jupyterlab-kite v1.2.0 enabled  ok
```
Checking for `errrors with jupyter server extension list`:
```
    jupyter_kite enabled
    - Validating...
      jupyter_kite 1.2.0 ok
    jupyterlab enabled
    - Validating...
      jupyterlab 2.2.6 ok
```

Is there any other place where i can check for errors @edzkite ? I am kinda new with programing and i'm probably missing something

**Comment by edzkite** [comment]
@TheCodeCow @bala-srm 

To get your browser console logs, see https://support.happyfox.com/kb/article/882-accessing-the-browser-console-and-network-logs/

Could you also upload your conda environments? See https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment

This will help me reproduce your working state.

**Comment by bala-srm** [comment]
I uninstalled anaconda and python as well and reinstalled it. Then upgraded jupyter lab to latest version from anaconda prompt. Also uninstalled kite and reinstalled the same couple of times. Suddenly it started working now. !! Issue started when I tried to update the kite plug in  from within jupyter lab.. upgrading should not be such a painful and disruptive process though..

**Comment by edzkite** [comment]
@bala-srm Happy to hear you got it to work. Definitely agree that it shouldn't be this painful. 

That being said, I'd recommend updating the plugin via the command line as opposed to the UI going forward.

**Comment by TheCodeCow** [comment]
@edzkite  

i've managed to get my console logs and my conda enviroment, this is my jupyterlab conda enviroment in google drive:
https://drive.google.com/file/d/1r0I8aMuSpGfPdlW0fllkLEGGsTBPO37t/view?usp=sharing

And my console logs (I supposed you needed an image):
![jupyter](https://user-images.githubusercontent.com/73436236/97718045-d6260100-1a9b-11eb-8320-e537773f58d2.png)
![jupyter2](https://user-images.githubusercontent.com/73436236/97718057-d920f180-1a9b-11eb-8bf1-522016f97743.png)

i'm also going to try with reinstalling everything like @bala-srm

**Comment by edzkite** [comment]
@TheCodeCow Thanks for uploading your env. I just installed it to a Windows machine, and it seems to work fine. I did notice earlier that your output displayed:

> Uninstalled core extensions:
@kiteco/jupyterlab-kite

Please ensure the front end extension is installed by running `jupyter labextension install "@kiteco/jupyterlab-kite"`.

Given that there are no console logs in your screenshot above, this is the most likely culprit right now.

**Comment by TheCodeCow** [comment]
@edzkite 
Ok, i uninstalled and uninstalled python, kite and anaconda, then i installed python and anaconda (updating everything in anaconda with conda update all) and then i installed and started Kite. After that i ran the commands pip install jupyter-kite and jupyter labextension install "@kiteco/jupyterlab-kite" in the anaconda prompt.

Only after all of that, the kite status bar in jupyter lab started displaying "innitializing" for a while and after that "ready".
Now Kite works just fine, allthough a little slowly. I suspect that the problem emanates from updating jupyter lab after Kite is installed, but i'm not shure of that either.

Thanks a lot @edzkite  for your help and @bala-srm  for the idea
