### ISSUE TITLE
Kite atom plugin stuck in initializing

### ISSUE THREAD

**Issue by alexnanchen** [kiteco/issue-tracker#446]
Hello,

I am using atom on mac os x (10.13.6) and Kite plugin suddenly got stuck in "initializing".

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/7e26c4b6-4886-442f-9355-5294fec178f6/kite_local/client.log.2020-10-26_09-00-09-AM.bak.gz

![02](https://user-images.githubusercontent.com/3436090/97148114-dc9a3d00-176a-11eb-9c0d-d975a014c6a0.png)

**Comment by alexnanchen** [comment]
> Hello,
> 
> I am using atom on mac os x (10.13.6) and Kite plugin suddenly got stuck in "initializing".
> 
> https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/7e26c4b6-4886-442f-9355-5294fec178f6/kite_local/client.log.2020-10-26_09-00-09-AM.bak.gz
> 
> ![02](https://user-images.githubusercontent.com/3436090/97148114-dc9a3d00-176a-11eb-9c0d-d975a014c6a0.png)
![01](https://user-images.githubusercontent.com/3436090/97150199-13be1d80-176e-11eb-8813-5ed5b35e5391.png)

**Comment by its-dhung** [comment]
This message should switch to `kite: ready` after you've received your first completion from Kite. Is this not the case?

**Comment by alexnanchen** [comment]
Hello, 

Just purchase a one year license because I find kite very helpful. It it not following the cursor. Got a bad status in atom.

Do you have any suggestions. 

![01](https://user-images.githubusercontent.com/3436090/99948777-3ac23c00-2d7a-11eb-8cec-565c0ce9b5ea.png)

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/536699/kite_local/client.log.2020-11-23_10-52-42-AM.bak.gz

Many thanks.

Best regards.

Alexandres

**Comment by alexnanchen** [comment]
This "Uncaught Error: bad_status" happen when hitting ctrl-alt-k do display the doc because it was not following the cursor. By clicking on the blue doc at the bottom of the poput it works.

Many thanks.

Best regards.

Alexandre

**Comment by alexnanchen** [comment]
I am trying to avoid the mouse, and the follow cursor functionality is very useful.

**Comment by its-dhung** [comment]
Hi @alexnanchen, can you share:

* What version of Kite are you using?
* What version of Kite's Atom plugin are you using?

**Comment by alexnanchen** [comment]
Hello @its-dhung,

Kite version is 0.1.0
Kite plugin version is 0.196.0
Atom version is 1.53.0 x64

Many thanks.

Alexandre

**Comment by its-dhung** [comment]
> Kite version is 0.1.0

Can you visit `kite://settings` in your browser, then scroll to the bottom and share what the version says?

**Comment by alexnanchen** [comment]
![01](https://user-images.githubusercontent.com/3436090/100191144-f22c8f00-2eef-11eb-8bb5-35508509e37f.png)

**Comment by its-dhung** [comment]
Just to make sure I understand your issue:

1. You no longer are seeing Kite stuck on `initializing` correct?
2. But you are having issues with docs following your cursor. Does this problem go away after you restart Kite? Even if it does fix itself upon restarting Kite, does it stop working again after you've had Kite running for a while?
3. If you use the keyboard shortcut to pull up docs, you get the `bad_status` error?
4. Clicking on the docs link works fine though?

**Comment by alexnanchen** [comment]
1. Yes, no longer suck on initializing. It was solved after logging in kite account. Not sure that it is the answer
2. Yes, sometimes it stop working and sometimes it works
3. The bad status error happens when no doc is found and you use the keyboard shortcut
4. Hovering on the symbol, does not show anything

Regarding no doc found, is there a way to check that the content of ~/.kite/libraries is indexed properly?

Next time I encounter the problem, I will try to restart Kite.
