### ISSUE TITLE
Kite not showing up in Jupyterlab after installation of plug in

### ISSUE THREAD

**Issue by bala-srm** [kiteco/issue-tracker#449]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
Post installation of Kite desktop app and installing the plug in from the terminal, kite autocomplete doesn't show up in the status bar of jupyter lab. I am using version 2.2.6. kite extension is showing up in the list of extensions in the left panel of jupyterlabs through. I am a kite pro user.

Your OS: **Windows10**
Whether or not you have the Kite desktop app installed - **Yes**
The error you received when trying to install the plugin from the command line - **No Error**
The output of pip list
Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
alembic                            1.4.2
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.2.0
autopep8                           1.5.4
azure-core                         1.8.0
azure-storage-blob                 12.4.0
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
bitarray                           1.6.0
bkcharts                           0.2
bleach                             3.2.1
blis                               0.4.1
bokeh                              2.2.3
boto                               2.49.0
boto3                              1.14.51
botocore                           1.17.51
Bottleneck                         1.3.2
brotlipy                           0.7.0
catalogue                          1.0.0
catboost                           0.24.1
certifi                            2020.6.20
cffi                               1.14.3
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.3
colorlover                         0.3.0
combo                              0.1.1
comtypes                           1.1.7
conda                              4.9.1
conda-build                        3.20.3
conda-package-handling             1.7.2
conda-verify                       3.4.2
confuse                            1.3.0
contextlib2                        0.6.0.post1
cryptography                       3.1.1
cufflinks                          0.17.3
cycler                             0.10.0
cymem                              2.0.3
Cython                             0.29.21
cytoolz                            0.11.0
dask                               2.30.0
databricks-cli                     0.11.0
datefinder                         0.7.1
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.30.0
docker                             4.3.1
docutils                           0.16
en-core-web-sm                     2.3.1
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.4
Flask                              1.1.2
fsspec                             0.8.3
funcy                              1.14
future                             0.18.2
gensim                             3.8.3
gevent                             20.9.0
gitdb                              4.0.5
GitPython                          3.1.7
glob2                              0.7
gmpy2                              2.0.8
gorilla                            0.3.0
graphviz                           0.14.1
greenlet                           0.4.17
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
htmlmin                            0.1.12
idna                               2.10
ImageHash                          4.1.0
imageio                            2.9.0
imagesize                          1.2.0
imbalanced-learn                   0.7.0
importlib-metadata                 2.0.0
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.18.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isodate                            0.6.0
isort                              5.6.4
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.2
Jinja2                             2.11.2
jmespath                           0.10.0
joblib                             0.17.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-contrib-core               0.3.3
jupyter-contrib-nbextensions       0.5.1
jupyter-core                       4.6.3
jupyter-highlight-selected-word    0.2.0
jupyter-kite                       1.2.0
jupyter-latex-envs                 1.4.6
jupyter-nbextensions-configurator  0.4.1
jupyterlab                         2.2.8
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
jupyterthemes                      0.20.0
keyring                            21.4.0
kiwisolver                         1.2.0
kmodes                             0.10.2
lazy-object-proxy                  1.4.3
lesscpy                            0.14.0
libarchive-c                       2.9
lightgbm                           2.3.1
llvmlite                           0.34.0
locket                             0.2.0
lxml                               4.6.1
Mako                               1.1.3
MarkupSafe                         1.1.1
matplotlib                         3.3.2
mccabe                             0.6.1
menuinst                           1.4.16
missingno                          0.4.2
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mlflow                             1.10.0
mlxtend                            0.17.3
mock                               4.0.2
more-itertools                     8.5.0
mpmath                             1.1.0
msgpack                            1.0.0
msrest                             0.6.18
multipledispatch                   0.6.0
murmurhash                         1.0.2
navigator-updater                  0.2.1
nbclient                           0.5.1
nbconvert                          5.6.1
nbformat                           5.0.8
nest-asyncio                       1.4.1
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.4
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.19.2
numpydoc                           1.1.0
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           3.0.5
packaging                          20.4
pandas                             1.1.3
pandas-profiling                   2.8.0
pandocfilters                      1.4.2
paramiko                           2.7.2
parso                              0.7.1
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
phik                               0.10.0
pickleshare                        0.7.5
Pillow                             8.0.0
pip                                20.2.4
pkginfo                            1.6.0
plac                               1.1.3
plotly                             4.9.0
pluggy                             0.13.1
ply                                3.11
preshed                            3.0.2
prometheus-client                  0.8.0
prometheus-flask-exporter          0.16.0
prompt-toolkit                     3.0.7
protobuf                           3.13.0
psutil                             5.7.2
py                                 1.9.0
pycaret                            2.1
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.7.1
pyLDAvis                           2.1.2
pylint                             2.6.0
PyNaCl                             1.4.0
pyod                               0.8.1
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             0.0.0
python-dateutil                    2.8.1
python-editor                      1.0.4
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            228
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          1.0.1
qtconsole                          4.7.7
QtPy                               1.9.0
querystring-parser                 1.2.4
regex                              2020.10.15
requests                           2.24.0
requests-oauthlib                  1.3.0
retrying                           1.3.3
rope                               0.18.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
s3transfer                         0.3.3
scikit-image                       0.17.2
scikit-learn                       0.23.2
scipy                              1.5.0
seaborn                            0.11.0
Send2Trash                         1.5.0
setuptools                         50.3.0.post20201006
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.15.0
smart-open                         2.1.1
smmap                              3.0.4
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
spacy                              2.3.2
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.19
sqlparse                           0.3.1
srsly                              1.0.2
statsmodels                        0.12.0
suod                               0.0.4
sympy                              1.6.2
tables                             3.6.1
tabulate                           0.8.7
tangled-up-in-unicode              0.0.6
tblib                              1.7.0
terminado                          0.9.1
testpath                           0.4.4
textblob                           0.15.3
thinc                              7.4.1
threadpoolctl                      2.1.0
tifffile                           2020.10.1
toml                               0.10.1
toolz                              0.11.1
tornado                            6.0.4
tqdm                               4.50.2
traitlets                          5.0.4
typing-extensions                  3.7.4.3
ujson                              4.0.1
umap-learn                         0.4.6
unicodecsv                         0.14.1
urllib3                            1.25.11
visions                            0.4.4
waitress                           1.4.4
wasabi                             0.8.0
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   0.57.0
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wordcloud                          1.8.0
wrapt                              1.11.2
xgboost                            1.2.0
xlrd                               1.2.0
XlsxWriter                         1.3.7
xlwings                            0.20.8
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
yellowbrick                        1.1
zict                               2.0.0
zipp                               3.3.1
zope.event                         4.5.0
zope.interface                     5.1.2

The output of jupyter labextension list

JupyterLab v2.2.6
Known labextensions:
   app dir: C:\Users\alabm\anaconda3\share\jupyter\lab
        @arbennett/base16-gruvbox-light v0.1.3 enabled  ok
        @hokyjack/jupyterlab-monokai-plus v0.1.4 enabled  ok
        @jupyterlab/toc v4.0.0 enabled  ok
        @kiteco/jupyterlab-kite v1.2.0 enabled  ok
        jupyterlab-code-snippets v1.0.4 enabled  ok

Uninstalled core extensions:
    @kiteco/jupyterlab-kite
    jupyterlab-theme-toggle
    jupyterlab_onedark

**Screenshots**
![image](https://user-images.githubusercontent.com/53083124/97317341-b66ebd00-1890-11eb-9430-dc9e09be3190.png)

output of jupyter serverextension list is given below:
config dir: C:\Users\alabm.jupyter
jupyter_nbextensions_configurator enabled
- Validating...
jupyter_nbextensions_configurator 0.4.1 ok
config dir: C:\Users\alabm\anaconda3\etc\jupyter
jupyter_kite enabled
- Validating...
jupyter_kite 1.2.0 ok
jupyterlab enabled
- Validating...
jupyterlab 2.2.6 ok

I don't even get the Kite: not running status on the status bar of jupyter lab

Given below is the kite logs link:
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/175539/kite_local/client.log.2020-10-27_08-30-39-PM.bak.gz

**Comment by its-dhung** [comment]
Given that Kite is shown as both installed and uninstalled, you may need to manually remove JupyterLab's `build_config.json` file. [This issue](https://github.com/jupyterlab/jupyterlab/issues/8122) in the JupyterLab main repo contains more info.
