### ISSUE TITLE
VScode's kite Unable to type the prompt code properly

### ISSUE THREAD

**Issue by ResistanceTo** [kiteco/issue-tracker#450]
When I'm writing a Python file, i input `def m` kite give me `main():`. And I press Enter, it just enters `main`
```
kite: 2.20201026.1
vscode-kite: 0.134.0
python: 3.6.5
vscode: 1.50.1
system: ubuntu 18.4
```

**Comment by its-dhung** [comment]
This may be due to Kite Pro completions showing up even though you're using Kite Free. You can disable this behavior from the Copilot settings by unchecking "Show multi-word completions in Kite Free".
