### ISSUE TITLE
Error executing Jupyter command 'labextension': [WinError 5] Access is denied

### ISSUE THREAD

**Issue by yoanand** [kiteco/issue-tracker#451]
I am getting this
![Screenshot (24)](https://user-images.githubusercontent.com/27909944/97539892-c699b000-19e8-11eb-877b-f4aa108654c2.png)

**Comment by its-dhung** [comment]
This seems unrelated to Kite and more about your installation of JupyterLab. Perhaps you don't have the proper admin rights to install extensions? Since this isn't Kite related, I'm going to close this issue.
