### ISSUE TITLE
Can't move kite app to bin - it says it's still open?!

### ISSUE THREAD

**Issue by moonchip1** [kiteco/issue-tracker#455]
Hi there, I'm not a coder and I don't understand much about how the app works, but I followed the instructions to uninstall the app on your website. I had to do this because it is taking up a lot of my %CPU, and I may reinstall later when I continue learning how to code.

It was all going well until I hit the final step of moving the Kite App icon from application to the bin. See screenshot for error message. Kite is not open as you can see from my Force Quit window, so I don't know what I can do to convince my computer that Kite is not running!
![Screenshot 2020-10-30 at 10 15 08](https://user-images.githubusercontent.com/73695355/97695086-66b01180-1a9b-11eb-95fc-3dec7f7730c6.png)

Thanks in advance for your help.

**Comment by metalogical** [comment]
It looks like the Kite Engine is still running based on the activity monitor in the background. Please try to quit Kite Engine from the activity monitor before deleting Kite.

Regarding Kite consuming CPU: if you're so inclined, it would be helpful if you could share a CPU profile before removing Kite. You can do this by
- double-click the Kite app to open the Kite copilot
- going into settings via the gear icon on the bottom right
- click on the logs tab
- capture both application logs, as well as a CPU profile while Kite is consuming a lot of CPU

Your feedback would be very helpful here.

Let us know if you're still having trouble deleting Kite either way.
