### ISSUE TITLE
Kite always showing initalizing 

### ISSUE THREAD

**Issue by Trid-collab** [kiteco/issue-tracker#461]
Since the vs code kite extension upgrades in Oct 20 I am finding that the kite engine for python is always showing initalizing endlessly. This is slowing down vs code and levaing me with no other alternative other than remove kite from my system. 

I have attached the logs and a screenshot for your reference

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/271779/kite_local/client.log.2020-11-03_07-40-33-PM.bak.gz

https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/271779/kite_local/1604412587494772700/capture.gz

![image](https://user-images.githubusercontent.com/61322708/97996799-360b0780-1e0e-11eb-8e8c-37ce70f231f7.png)

**Comment by busdav** [comment]
I have the same issue, except that it's for typescript and javascript. Log here: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/323875/kite_local/client.log.2020-11-03_10-41-28-PM.bak.gz

**Comment by its-dhung** [comment]
Does this message persist even after you start receiving completions from Kite?

**Comment by busdav** [comment]
For me, this issue currently is not present anymore. Unfortunately I don't know what did the trick..

**Comment by KNIF** [comment]
Had the same issue until today, now its working again. All I did was reinstall the VSCode extension, but I think it was some back-end related issue as I also tried reinstalling the extension a few days ago and it didn't help but now it did.

**Comment by its-dhung** [comment]
The models that predict completions take a while to warm up. While they are warming up, Kite will report that it's initializing, but the message should go away as soon as you start receiving completions.

Please re-open this if you experience this issue again in the future.

**Comment by HQDragon** [comment]
IDE:spyder 4.1.5
Python Version: 3.8.5
always initializing, even after start receiving completions
