### ISSUE TITLE
can't install plugin for jupyter

### ISSUE THREAD

**Issue by anabapz** [kiteco/issue-tracker#465]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

I open Kite and it says that any plugin for jupyter was installed
so I open Anaconda prompt
I enter 
pip install jupyter-kite
which worked correctly
then 
jupyter labextension install "@kiteco/jupyterlab-kite"
and it was for this command that I got a problem
system says: 
'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-labextension` not found.

**Screenshots**

pip list:
Package                Version
---------------------- -------------------
absl-py                0.10.0
argon2-cffi            20.1.0
astunparse             1.6.3
async-generator        1.10
attrs                  20.3.0
backcall               0.2.0
biopython              1.78
bleach                 3.2.1
cachetools             4.1.1
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
click                  7.1.2
colorama               0.4.4
cycler                 0.10.0
decorator              4.4.2
defusedxml             0.6.0
entrypoints            0.3
gast                   0.3.3
google-auth            1.22.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.33.1
h5py                   2.10.0
idna                   2.10
importlib-metadata     2.0.0
ipykernel              5.3.4
ipython                7.18.1
ipython-genutils       0.2.0
jedi                   0.17.2
Jinja2                 2.11.2
joblib                 0.17.0
jsonschema             3.2.0
jupyter-client         6.1.7
jupyter-core           4.6.3
jupyter-kite           1.2.0
jupyterlab-pygments    0.1.2
Keras-Preprocessing    1.1.2
kiwisolver             1.2.0
Markdown               3.3.2
MarkupSafe             1.1.1
matplotlib             3.3.1
mistune                0.8.4
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.2
nltk                   3.5
notebook               6.1.4
numpy                  1.19.1
oauthlib               3.1.0
olefile                0.46
opt-einsum             3.3.0
packaging              20.4
pandas                 1.1.3
pandocfilters          1.4.3
parso                  0.7.0
pickleshare            0.7.5
Pillow                 8.0.0
pip                    20.2.4
prometheus-client      0.8.0
prompt-toolkit         3.0.8
protobuf               3.13.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
Pygments               2.7.1
pyparsing              2.4.7
pyrsistent             0.17.3
python-dateutil        2.8.1
pytz                   2020.1
pywin32                227
pywinpty               0.5.7
pyzmq                  19.0.2
regex                  2020.10.15
requests               2.24.0
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.23.2
scipy                  1.5.2
seaborn                0.11.0
Send2Trash             1.5.0
setuptools             50.3.0.post20201006
six                    1.15.0
tensorboard            2.3.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.3.1
tensorflow-estimator   2.3.0
termcolor              1.1.0
terminado              0.9.1
testpath               0.4.4
threadpoolctl          2.1.0
tornado                6.0.4
tqdm                   4.50.2
traitlets              5.0.5
urllib3                1.25.11
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.35.1
wincertstore           0.2
wrapt                  1.12.1
zipp                   3.3.1

 jupyter labextension list:
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-labextension` not found.

I work on windows
i use anaconda
jupyter 6.0.3

thank you in advance

**Comment by its-dhung** [comment]
You need to install JupyterLab to use Kite. It seems like you're using the older Jupyter notebooks.
