### ISSUE TITLE
Kite refuses to Activate

### ISSUE THREAD

**Issue by solarisjon** [kiteco/issue-tracker#470]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ X] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/505844/kite_local/client.log.2020-11-09_12-16-41-PM.bak.gz

**Describe the bug**
Was running on the free trial I bought pro over the weekend tried everything in the documents, logged in and out of Kite and also re-installed nothing is working.

**Screenshots**

**Comment by its-dhung** [comment]
Hi @solarisjon, someone on our Kite Pro support team will assist you with this and get this fixed.
