### ISSUE TITLE
Unable to get Kite to work with VS Code and Sublime

### ISSUE THREAD

**Issue by PingLH** [kiteco/issue-tracker#472]
- [] Kite application logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/556269/kite_local/client.log.2020-11-10_12-44-05-AM.bak.gz
- [ ] RESOURCE USAGE: https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/556269/kite_local/1604990653337929800/capture.gz
![kite not loading in vs or sublime](https://user-images.githubusercontent.com/74230996/98638136-20568000-22ef-11eb-8369-22789a68a053.JPG)
![kite not loading in vs or sublime](https://user-images.githubusercontent.com/74230996/98638286-2e0c0580-22ef-11eb-84c5-6cf3c3b0d8dc.JPG)
![kite](https://user-images.githubusercontent.com/74230996/98638721-4aa83d80-22ef-11eb-8d24-0379389ae17f.jpg)
![kite](https://user-images.githubusercontent.com/74230996/98638909-572c9600-22ef-11eb-97cc-4c8edbcd066c.jpg)

**Describe the bug**
Kite is not running on my VS or Sublime program. I have the Kite plugin showing installed.
on the VS program Kite said it did not see VS by default. So I had to open VS and click the fix this option after that it loaded in the plugin section.
Thank you for any help you can give.

**Screenshots** I was unable to upload image on the ticket. I added the screenshot to the url below.
https://snipboard.io/SrKtg4.jpg

**Comment by its-dhung** [comment]
@PingLH have you tried restarting your editors? If that doesn't work, can you check and see if there are any errors in your editors' consoles?

**Comment by PingLH** [comment]
Restarting the PC worked
