### ISSUE TITLE
vscode can't autocomplete all the code

### ISSUE THREAD

**Issue by mepleleo** [kiteco/issue-tracker#477]
why my kite can't autocomplete all the code? only complete part of the code. 
It doesn't work whether I press Enter or Tab.
Did I set it wrong?
see the gif 
![video](https://user-images.githubusercontent.com/40195523/99038879-4024c700-25c1-11eb-99a8-726ac6105209.gif)

_________________________________
vscode version: 1.51.1 (user setup)
提交: e5a624b788d92b8d34d1392e4c4d9789406efe8f
date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
_________________________________
kite version 1.2020.1026.1
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/162144/kite_local/client.log.2020-11-13_03-26-58-PM.bak.gz

**Comment by its-dhung** [comment]
This is actually working as intended, though it's understandable why it seems like a bug.

You can continue to use these multi word completions if you upgrade to Kite Pro. Or if you would like to disable them, you can open the Copilot's settings and uncheck the box titled "Show multi-word completions in Kite Free".
