### ISSUE TITLE
Code Completion

### ISSUE THREAD

**Issue by TheGreatKO** [kiteco/issue-tracker#478]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.
I upgraded Pycharm 2020.2.3 yesterday (Nov 12, 2020) and my code completion did not work correctly. I would get the code replacement recommendation and I could select the desired completion code but only the first part of the replacement code would be entered on the editor.
i.e. I typed if '__name" the code replacement suggested '__name__' == '_main__':  When I hit <enter> to select only if '__name would show,
I reported to Pycharm and they suggested I disable several plugins. When I disable Kite - the completion code worked.

Pycharm support asked that I report this to you.

**Screenshots**

**Comment by JewelryStone** [comment]
I have the same trouble both in vscode and in jupyterlab.

**Comment by its-dhung** [comment]
See https://github.com/kiteco/issue-tracker/issues/477#issuecomment-732529906 for a fix.
