### ISSUE TITLE
Jupyterlab plugin not working Windows 10

### ISSUE THREAD

**Issue by cebasfu93** [kiteco/issue-tracker#479]
It has been impossible to install Kite's plugin for Jupyterlab. I followed all the instructions from https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin 

Also tried reinstalling Anaconda and Kite and start from scratch. 

OS: Microsoft Windows 10 Enterprise

Browser logs when starting Jupyter notebook:
![image](https://user-images.githubusercontent.com/12839647/99248190-5c667500-2808-11eb-8028-ceeda7fd3ea3.png)

Extensions and server extension:
![image](https://user-images.githubusercontent.com/12839647/99248075-3214b780-2808-11eb-89e2-62ce97262bf2.png)

pip list:
[piplist.txt](https://github.com/kiteco/issue-tracker/files/5545939/piplist.txt)

Environment:
[SFUenv.zip](https://github.com/kiteco/issue-tracker/files/5545947/SFUenv.zip)

**Comment by edzkite** [comment]
@cebasfu93 For the browser logs, could you include the contents of the log in your web browser? You can do so by following the instructions [here](https://zapier.com/help/troubleshoot/behavior/view-and-save-your-browser-console-logs).

**Comment by cebasfu93** [comment]
> 
> 
> @cebasfu93 For the browser logs, could you include the contents of the log in your web browser? You can do so by following the instructions [here](https://zapier.com/help/troubleshoot/behavior/view-and-save-your-browser-console-logs).

Thank you for the help!

Here the browser (firefox) logs.
When starting jupyter:
![image](https://user-images.githubusercontent.com/12839647/99521979-610c6400-2995-11eb-9ce2-b627ab95b097.png)

When creating a new notebook:
![image](https://user-images.githubusercontent.com/12839647/99522579-22c37480-2996-11eb-9460-92da43e99cba.png)

I hope this is what you were asking for. Let me know if you need anything else!

**Comment by cebasfu93** [comment]
@edzkite Just for the record. My default browser is Firefox-v83.0 in private browsing mode. I disabled the private browsing, update the Kite extension, and open Jupyter, but it still was unsuccessful. I followed the same procedure setting Chrome-v86.0.4240.198 (64-bit) as the default browser but obtained again the same results (i.e. the Kite extension not working with JupyterLab)

**Comment by edzkite** [comment]
@cebasfu93 Thanks for sending that over!

I used the conda env you exported and installed it, and it seems to work fine. For reference, this is what my browser looks like with your conda env:

<img width="1258" alt="Screen Shot 2020-11-18 at 11 53 03 AM" src="https://user-images.githubusercontent.com/47993402/99580873-dcb9e100-2994-11eb-928f-f6638366c63a.png">

Looking at your browser logs though, it seems like our extension doesn't activate at all. It also looks like it's loading an extension named "jupyter-js-widget". Do you have any other extensions or kernels active? That could help me reproduce your issue.

**Comment by edzkite** [comment]
Also, could you check Task Manager and ensure that `kited.exe` is an active process?

**Comment by cebasfu93** [comment]
@edzkite Thank you very much for the help! 
This is embarrassing.... I gave for granted that it would work the same when executing Jupyter notebook. I just learned Jupyter lab is not the same thing. The more you know...

When I open Jupyter lab, it works perfectly 👍
