### ISSUE TITLE
Recently I came to know about Kite

### ISSUE THREAD

**Issue by saninkiliyamannil** [kiteco/issue-tracker#487]
I can't run the kite setup file since I have enough system requirement (my system is running in 64 bit and windows 7). I need the help to run and install Kite engine for my  VS Code

**Comment by its-dhung** [comment]
Please check [our guides](https://help.kite.com/category/39-getting-started) to learn how to setup Kite.

**Comment by saninkiliyamannil** [comment]
![image_2020-11-24_230549](https://user-images.githubusercontent.com/69413437/100139895-96d7ae00-2ea9-11eb-9f78-a301e153a2a2.png)
This is what it showing all the time

**Comment by its-dhung** [comment]
As mentioned, Kite requires AVX support. Unfortunately this means that it won't work on your computer.

**Comment by saninkiliyamannil** [comment]
Thank you for for spending a lot of it me with me

**Comment by saninkiliyamannil** [comment]
I like the way you convince me
