### ISSUE TITLE
jupyterlab extension not working in Big Sur

### ISSUE THREAD

**Issue by xellosiris** [kiteco/issue-tracker#493]
- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Kite application logs**
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/17d5d09b-5ad0-4aba-8b0a-a2479758b850/kite_local/client.log.2020-11-27_08-25-28-AM.bak.gz

**jupyter lab and kite version**
jupyter-client      6.1.7
jupyter-core        4.6.3
jupyter-kite        1.2.0
jupyterlab          2.2.9
jupyterlab-pygments 0.1.2
jupyterlab-server   1.2.0

**environmental r**
Mac osx 11.0.1
Safari 14.0.1
python3.8
pip 20.2.4
**Describe the bug**
cannot install plugin kite directly from jupyter lab extension manger, it shows message below. 
I tried to use command to install kite but it still failed.

**Screenshots**
<img width="313" alt="截圖 2020-11-27 下午12 34 27" src="https://user-images.githubusercontent.com/33425166/100411552-12557d00-30ad-11eb-9c17-d18833dafa72.png">
<img width="995" alt="截圖 2020-11-27 上午8 23 42" src="https://user-images.githubusercontent.com/33425166/100398738-f3de8a00-308a-11eb-99fa-90ddb3cadfe7.png">
<img width="1439" alt="截圖 2020-11-27 下午12 34 54" src="https://user-images.githubusercontent.com/33425166/100411545-0e295f80-30ad-11eb-81a0-d56bd984e72c.png">

**Comment by its-dhung** [comment]
Try following [these instructions](https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin) to install Kite's JupyterLab plugin. As mentioned, you'll need to run `pip install jupyter-kite` in the environment from where you're running JupyterLab.

**Comment by xellosiris** [comment]
> Try following [these instructions](https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin) to install Kite's JupyterLab plugin. As mentioned, you'll need to run `pip install jupyter-kite` in the environment from where you're running JupyterLab.

I did follow instructions................
I run command `pip install jupyter-kite` and it show successful.
<img width="1440" alt="截圖 2020-12-01 下午7 55 23" src="https://user-images.githubusercontent.com/33425166/100737674-6b0b7980-340f-11eb-9144-938cc61bd015.png">
install extension:
<img width="1440" alt="截圖 2020-12-01 下午7 58 13" src="https://user-images.githubusercontent.com/33425166/100738115-1c121400-3410-11eb-8c88-a3daf2d63fe2.png">
extension showed,but it doesn't work:
<img width="1440" alt="截圖 2020-12-01 下午8 00 21" src="https://user-images.githubusercontent.com/33425166/100738019-f1c05680-340f-11eb-8baa-da6a8f32b488.png">

**Comment by its-dhung** [comment]
Can you share the output of the 3 commands

```
jupyter labextension list
```

```
jupyter serverextension list
```

```
pip list
```
