### ISSUE TITLE
VSCode extension stuck at initializing.

### ISSUE THREAD

**Issue by anirudh242** [kiteco/issue-tracker#494]
I just installed Kite today to use with Visual Studio Code and I installed the extension for it. It is now stuck at initializing in the bottom right corner.
![image](https://user-images.githubusercontent.com/73819495/100516438-d7853f00-31a9-11eb-9941-8ebce87f0a5d.png)
This is what the actual Co-Pilot app looks like.
![image](https://user-images.githubusercontent.com/73819495/100516445-e2d86a80-31a9-11eb-94d9-a30e025cba6c.png)

**Comment by its-dhung** [comment]
The `initializing` message should go away after you start receiving completions from Kite. Please re-open if that's not the case for you.
