### ISSUE TITLE
Cannot Install Jupyter Lab Extension

### ISSUE THREAD

**Issue by jessicabrock** [kiteco/issue-tracker#501]
[kite.txt](https://github.com/kiteco/issue-tracker/files/5644428/kite.txt)
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

**Screenshots**

**Comment by edzkite** [comment]
Can you ensure that `jupyterlab` is [installed](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html)? It doesn't look like it's present in `pip list`.

```
jupyter-client      6.1.7
jupyter-core        4.7.0
jupyter-kite        1.2.0
jupyterlab-pygments 0.1.2
```
