### ISSUE TITLE
Kite not Starting in Jupyter Labs 2.29

### ISSUE THREAD

**Issue by ggblake** [kiteco/issue-tracker#506]
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/291931/kite_local/client.log.2020-12-09_01-51-36-PM.bak.gz

- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

WIndows 10
AnaConda 1.10.0
Kite Service is running and works in Spyder but not discovered in Jupyter labs

**Comment by edzkite** [comment]
@ggblake Can you please provide all the information in the Troubleshooting section of https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin?

**Comment by ggblake** [comment]
Solved

There were 2 instance l installed and uninstalled

Removing build.config.json from anaconda/share/jupyte/rlab/settings worked




GGB


On 12/14/2020 at 12:58 PM, edzkite <notifications@github.com> wrote:



@ggblake Can you please provide all the information in the Troubleshooting
section of
https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by edzkite** [comment]
@ggblake Nice! Thanks for letting me know.
