### ISSUE TITLE
cannot install kite plugin for Jupyter Notebook

### ISSUE THREAD

**Issue by Andy-Pham-72** [kiteco/issue-tracker#507]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
I tried to install the Kite Plugin for Jupyter Notebook but it showed "ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org)."

**Screenshots**
<img width="1656" alt="Screen Shot 2020-12-09 at 10 32 17 PM" src="https://user-images.githubusercontent.com/70767722/101718045-6e85ad00-3a6e-11eb-88d2-e964b4d72d36.png">

**Comment by edzkite** [comment]
@Andy-Pham-72 Our plugin requires Node.js to be globally installed. Please see https://nodejs.org/en/download/ for more details.
