### ISSUE TITLE
Kite Not Opening Mac Mini M1

### ISSUE THREAD

**Issue by ChrisF24** [kiteco/issue-tracker#513]
When launching app it simply does not open. I tried reinstalling, still nothing. 

Hardware: Mac Mini M1 
Software: Big Sur 11.1

**Comment by metalogical** [comment]
duplicate of #491

**Comment by sayedsadat98** [comment]
Right now they are not yet supported on M1 chips and also they are not supported on Rosetta. You have to wait or subscribe to the newsletter so you will be notified. Check the link : https://help.kite.com/article/146-support-for-apple-m1-hardware
