### ISSUE TITLE
Kite is not working on my Linux machine with Jupyter Lab

### ISSUE THREAD

**Issue by kubekmonika** [kiteco/issue-tracker#517]
**Description**
Kite is not running and I see the following error in the terminal after I open jupyter lab in the browser:

`[E 11:25:10.641 LabApp] <LspStdIoReader(parent=<LanguageServerSession(language_server=kitels, argv=['/home/monika/.local/share/kite/current/kite-lsp'])>)> couldn't enqueue message: None
    Traceback (most recent call last):
      File "/home/monika/Python/venv/lib/python3.8/site-packages/jupyter_kite/stdio.py", line 90, in read
        message = await self.read_one()
      File "/home/monika/Python/venv/lib/python3.8/site-packages/jupyter_kite/stdio.py", line 109, in read_one
        line = await convert_yielded(self._readline())
    TypeError: object Future can't be used in 'await' expression`

**Information**

- Logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/360568/kite_local/client.log.2020-12-23_11-26-59-AM.bak.gz
- Editor: jupyter lab ver. 2.2.9
- `jupyter labextension list` output:
JupyterLab v2.2.9
Known labextensions:
   app dir: /home/monika/Python/venv/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.2.0  enabled  OK
        @jupyterlab/git v0.23.2  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @kiteco/jupyterlab-kite v1.2.0  enabled  OK
        @pyviz/jupyterlab_pyviz v1.0.4  enabled  OK
        nbdime-jupyterlab v2.0.1  enabled  OK

- `jupyter serverextension list` output:
config dir: /home/monika/Python/venv/etc/jupyter
    jupyter_kite  enabled 
    - Validating...
      jupyter_kite 1.1.0 OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.9 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.23.2 OK
    nbdime  enabled 
    - Validating...
      nbdime 2.1.0 OK
config dir: /usr/local/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.9 OK

- `pip list` output:
Package                       Version
absl-py                       0.9.0
aiohttp                       3.6.3
alabaster                     0.7.12
alembic                       1.4.1
astroid                       2.4.2
astunparse                    1.6.3
async-timeout                 3.0.1
atomicwrites                  1.4.0
attrs                         19.3.0
autopep8                      1.5.3
azure-core                    1.8.1
azure-storage-blob            12.5.0
Babel                         2.8.0
backcall                      0.1.0
beautifulsoup4                4.6.3
bleach                        3.1.5
blis                          0.4.1
bokeh                         2.0.2
Bottleneck                    1.3.2
cachetools                    4.1.0
catalogue                     1.0.0
catboost                      0.24.1
certifi                       2020.6.20
cffi                          1.14.0
chardet                       3.0.4
click                         7.1.2
cloudpickle                   1.4.1
cmdstanpy                     0.4.0
colorama                      0.4.4
colorcet                      2.0.2
coloredlogs                   14.0
colorlover                    0.3.0
combo                         0.1.1
confuse                       1.3.0
convertdate                   2.2.1
cryptography                  2.9.2
cufflinks                     0.17.3
cycler                        0.10.0
cymem                         2.0.3
Cython                        0.29.17
dask                          2.25.0
databricks-cli                0.12.0
dataprep                      0.2.14
datefinder                    0.7.1
decorator                     4.4.2
defusedxml                    0.6.0
diff-match-patch              20181111
docker                        4.3.1
docutils                      0.16
entrypoints                   0.3
ephem                         3.7.7.1
et-xmlfile                    1.0.1
fbprophet                     0.6
flake8                        3.8.3
Flask                         1.1.2
fsspec                        0.8.5
funcy                         1.14
future                        0.18.2
gast                          0.3.3
gensim                        3.8.3
gitdb                         4.0.5
GitPython                     3.1.8
google-auth                   1.17.0
google-auth-oauthlib          0.4.1
google-pasta                  0.2.0
gorilla                       0.3.0
graphviz                      0.14.1
grpcio                        1.29.0
gunicorn                      20.0.4
h5py                          2.10.0
helpdev                       0.7.1
holidays                      0.10.2
holoviews                     1.13.3
html5lib                      1.0.1
htmlmin                       0.1.12
humanfriendly                 8.2
hvplot                        0.6.0
idna                          2.9
ImageHash                     4.1.0
imagesize                     1.2.0
imbalanced-learn              0.7.0
intervaltree                  3.0.2
ipykernel                     5.2.1
ipython                       7.14.0
ipython-genutils              0.2.0
ipywidgets                    7.5.1
isodate                       0.6.0
isort                         4.3.21
itsdangerous                  1.1.0
jdcal                         1.4.1
jedi                          0.17.1
jeepney                       0.4.3
Jinja2                        2.11.2
joblib                        0.15.1
json5                         0.9.5
jsonpath-ng                   1.5.2
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.3
jupyter-console               6.1.0
jupyter-core                  4.6.3
jupyter-kite                  1.1.0
jupyterlab                    2.2.9
jupyterlab-git                0.23.2
jupyterlab-server             1.1.5
Keras                         2.3.1
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
keyring                       21.2.1
kiwisolver                    1.2.0
kmodes                        0.10.2
korean-lunar-calendar         0.2.1
lazy-object-proxy             1.4.3
lightgbm                      3.0.0
llvmlite                      0.34.0
locket                        0.2.0
LunarCalendar                 0.0.9
lxml                          4.5.0
Mako                          1.1.3
Markdown                      3.2.2
MarkupSafe                    1.1.1
matplotlib                    3.3.2
mccabe                        0.6.1
missingno                     0.4.2
mistune                       0.8.4
mlflow                        1.11.0
mlxtend                       0.17.3
more-itertools                8.3.0
msrest                        0.6.19
multidict                     4.7.6
murmurhash                    1.0.2
nbconvert                     5.6.1
nbdime                        2.1.0
nbformat                      5.0.6
networkx                      2.5
nltk                          3.5
notebook                      6.0.3
numba                         0.51.2
numexpr                       2.7.1
numpy                         1.19.4
numpydoc                      1.0.0
oauthlib                      3.1.0
openpyxl                      2.5.12
opt-einsum                    3.2.1
packaging                     20.3
pandas                        1.0.5
pandas-profiling              2.9.0
pandocfilters                 1.4.2
panel                         0.9.7
param                         1.9.3
parso                         0.7.0
partd                         1.1.0
pathtools                     0.1.2
patsy                         0.5.1
pexpect                       4.8.0
phik                          0.10.0
pickleshare                   0.7.5
Pillow                        7.2.0
pip                           20.1.1
plac                          1.1.3
plotly                        4.8.1
pluggy                        0.13.1
ply                           3.11
pmdarima                      1.5.3
preshed                       3.0.2
prometheus-client             0.7.1
prometheus-flask-exporter     0.18.0
prompt-toolkit                3.0.5
protobuf                      3.12.2
psutil                        5.7.0
ptyprocess                    0.6.0
py                            1.8.1
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycaret                       2.1.2
pycodestyle                   2.6.0
pycparser                     2.20
pyct                          0.4.6
pydantic                      1.7.3
pydocstyle                    5.0.2
pyflakes                      2.2.0
Pygments                      2.6.1
pyLDAvis                      2.1.2
pylint                        2.5.3
PyMeeus                       0.3.7
pyod                          0.8.3
pyparsing                     2.4.7
PyQt5                         5.12.3
PyQt5-sip                     12.8.0
PyQtWebEngine                 5.12.1
pyrsistent                    0.16.0
pystan                        2.19.1.1
pytest                        5.4.2
python-dateutil               2.8.1
python-editor                 1.0.4
python-jsonrpc-server         0.3.4
python-language-server        0.34.1
pytz                          2018.7
pyviz-comms                   0.7.6
PyWavelets                    1.1.1
pyxdg                         0.26
PyYAML                        5.3.1
pyzmq                         19.0.1
QDarkStyle                    2.8.1
QtAwesome                     0.7.2
qtconsole                     4.7.4
QtPy                          1.9.0
querystring-parser            1.2.4
regex                         2020.10.28
requests                      2.24.0
requests-oauthlib             1.3.0
retrying                      1.3.3
rope                          0.17.0
rsa                           4.1
scikit-learn                  0.23.1
scipy                         1.5.2
seaborn                       0.11.0
SecretStorage                 3.1.2
Send2Trash                    1.5.0
setuptools                    46.1.3
setuptools-git                1.2
shap                          0.36.0
six                           1.14.0
sklearn                       0.0
slicer                        0.0.4
smart-open                    2.2.0
smmap                         3.0.4
snowballstemmer               2.0.0
sortedcontainers              2.2.2
spacy                         2.3.2
Sphinx                        3.1.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
spyder                        4.1.4
spyder-kernels                1.9.3
spyder-terminal               0.3.2
SQLAlchemy                    1.3.13
sqlparse                      0.3.1
srsly                         1.0.2
statsmodels                   0.11.1
suod                          0.0.4
tabulate                      0.8.7
tangled-up-in-unicode         0.0.6
tenacity                      6.2.0
tensorboard                   2.3.0
tensorboard-plugin-wit        1.6.0.post3
tensorflow                    2.3.1
tensorflow-estimator          2.3.0
termcolor                     1.1.0
terminado                     0.8.3
testpath                      0.4.4
textblob                      0.15.3
thinc                         7.4.1
threadpoolctl                 2.0.0
toml                          0.10.1
toolz                         0.11.1
tornado                       5.0.2
tqdm                          4.48.2
traitlets                     4.3.3
typing-extensions             3.7.4.2
ujson                         1.35
umap-learn                    0.4.6
urllib3                       1.25.9
visions                       0.5.0
wasabi                        0.8.0
watchdog                      0.10.2
wcwidth                       0.1.9
webencodings                  0.5.1
websocket-client              0.57.0
Werkzeug                      1.0.1
wheel                         0.34.2
widgetsnbextension            3.5.1
wordcloud                     1.8.0
wrapt                         1.12.1
wurlitzer                     2.0.0
xgboost                       1.2.0
xlrd                          1.2.0
yapf                          0.30.0
yarl                          1.5.1
yellowbrick                   1.1

- system information
`Operating System: Kubuntu 20.04
Kernel Version: 5.4.45-050445-generic
OS Type: 64-bit
`

**Comment by edzkite** [comment]
The Kite plugin requires `tornado >=5.1.0`.
