### ISSUE TITLE
Not working with jupyterlab

### ISSUE THREAD

**Issue by htann** [kiteco/issue-tracker#519]
Please refer to as attached screen shot 
![Screen Shot 2020-12-24 at 8 57 28 AM](https://user-images.githubusercontent.com/8087618/103045035-45186580-45c6-11eb-9450-92557ca48a64.png)
![Screen Shot 2020-12-24 at 8 57 49 AM](https://user-images.githubusercontent.com/8087618/103045037-477abf80-45c6-11eb-9a68-a03424b57feb.png)
![Screen Shot 2020-12-24 at 8 57 58 AM](https://user-images.githubusercontent.com/8087618/103045038-48abec80-45c6-11eb-8cd4-ad1b9be3156c.png)

![Screen Shot 2020-12-24 at 9 06 44 AM](https://user-images.githubusercontent.com/8087618/103045344-6cbbfd80-45c7-11eb-83ed-23ae97b65ae5.png)

**Comment by htann** [comment]
OS: mac Big Sur version 11.1

**Comment by edzkite** [comment]
If you have the jupyterlab-lsp extension installed, you must disable it for Kite's plugin to work.
