### ISSUE TITLE
jupyterlab-kite extension doesn't work for JupyterLab 3.0.0

### ISSUE THREAD

**Issue by Dekay999** [kiteco/issue-tracker#532]
Hi, everyone. I am a beginner in jupyter lab. Firstly, I installed Node.js v14.15.3. Then in a virtualenv, I installed jupyter lab, jupyter-kite using pip. Then I run the following command in the virtualenv.
```
jupyter labextension install "@kiteco/jupyterlab-kite"
```
Finally, I ran a jupyter lab, and got the following information (seems normal):
![image](https://user-images.githubusercontent.com/37211395/103366815-847f0e80-4afe-11eb-9e6f-38136796c6a2.png)
And also I got
![image](https://user-images.githubusercontent.com/37211395/103366909-b1cbbc80-4afe-11eb-9679-f31c2d3ad0b5.png)
**The problem is, the expected auto-completion didn't happen, and the status bar is always like this when I was editing in a jupyter notebook:**
![image](https://user-images.githubusercontent.com/37211395/103367058-18e97100-4aff-11eb-831a-1cab1aa6ac29.png)
which should have shown a logo of "Kite". Can you help me fix it? Thank you very much.

By the way, the command `jupyter troubleshoot` returns the following result
```
(test) D:\myenvs\test\Scripts>jupyter troubleshoot
$PATH:
        D:\myenvs\test\Scripts
        C:\Python39\Scripts\
        C:\Python39\
        D:\ProgramFiles\myXftp6\
        D:\ProgramFiles\myXshell6\
        C:\Program Files\Common Files\Oracle\Java\javapath
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Windows\System32\OpenSSH\
        D:\ProgramFiles\Git\cmd
        C:\Program Files\SumatraPDF
        C:\Users\Hongyin\AppData\Local\Programs\MiKTeX\miktex\bin\x64\
        C:\Program Files\Pandoc\
        C:\ProgramData\chocolatey\bin
        D:\ProgramFiles\nodejs\
        C:\Users\Hongyin\AppData\Roaming\Python\Python39\Scripts
        C:\Program Files\MySQL\MySQL Shell 8.0\bin\
        C:\Users\Hongyin\AppData\Local\Microsoft\WindowsApps
        C:\Users\Hongyin\AppData\Local\Programs\MiKTeX\miktex\bin\x64\
        D:\ProgramFiles\Microsoft VS Code\bin
        D:\ProgramFiles\PyCharm 2020.3\bin

        C:\Users\Hongyin\AppData\Roaming\npm


sys.path:
        D:\myenvs\test\Scripts\jupyter-troubleshoot.EXE
        C:\Python39\python39.zip
        C:\Python39\DLLs
        C:\Python39\lib
        C:\Python39
        d:\myenvs\test
        d:\myenvs\test\lib\site-packages
        d:\myenvs\test\lib\site-packages\win32
        d:\myenvs\test\lib\site-packages\win32\lib
        d:\myenvs\test\lib\site-packages\Pythonwin

sys.executable:
        d:\myenvs\test\scripts\python.exe

sys.version:
        3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.19041-SP0

where jupyter:
        D:\myenvs\test\Scripts\jupyter.exe

pip list:
        Package             Version
        ------------------- ---------
        anyio               2.0.2
        argon2-cffi         20.1.0
        async-generator     1.10
        attrs               20.3.0
        Babel               2.9.0
        backcall            0.2.0
        bleach              3.2.1
        certifi             2020.12.5
        cffi                1.14.4
        chardet             4.0.0
        colorama            0.4.4
        decorator           4.4.2
        defusedxml          0.6.0
        entrypoints         0.3
        idna                2.10
        ipykernel           5.4.2
        ipython             7.19.0
        ipython-genutils    0.2.0
        jedi                0.18.0
        Jinja2              2.11.2
        json5               0.9.5
        jsonschema          3.2.0
        jupyter-client      6.1.7
        jupyter-core        4.7.0
        jupyter-kite        1.2.0
        jupyter-server      1.1.3
        jupyterlab          3.0.0
        jupyterlab-pygments 0.1.2
        jupyterlab-server   2.0.0
        MarkupSafe          1.1.1
        mistune             0.8.4
        nbclassic           0.2.5
        nbclient            0.5.1
        nbconvert           6.0.7
        nbformat            5.0.8
        nest-asyncio        1.4.3
        notebook            6.1.6
        numpy               1.19.4
        packaging           20.8
        pandas              1.2.0
        pandocfilters       1.4.3
        parso               0.8.1
        pickleshare         0.7.5
        pip                 20.3.3
        prometheus-client   0.9.0
        prompt-toolkit      3.0.8
        pycparser           2.20
        Pygments            2.7.3
        pyparsing           2.4.7
        pyrsistent          0.17.3
        python-dateutil     2.8.1
        pytz                2020.5
        pywin32             300
        pywinpty            0.5.7
        pyzmq               20.0.0
        requests            2.25.1
        Send2Trash          1.5.0
        setuptools          49.2.1
        six                 1.15.0
        sniffio             1.2.0
        terminado           0.9.1
        testpath            0.4.4
        tornado             6.1
        traitlets           5.0.5
        urllib3             1.26.2
        wcwidth             0.2.5
        webencodings        0.5.1
```

**Comment by edzkite** [comment]
Unfortunately, it looks like JupyterLab 3.0 is causing an issue with our plugin. 

While we investigate, a workaround is to downgrade to JupyterLab 2.2.9. You can do so in conda via `conda install -c conda-forge "jupyterlab<3.0"`.

**Comment by edzkite** [comment]
I've updated our extension so that it should support JupyterLab 3.0+. To upgrade:

1. Uninstall `jupyter-kite` (`pip install jupyter-kite`)
2. Uninstall `@kiteco/jupyterlab-kite` (`jupyter labextension uninstall @kiteco/jupyterlab-kite`)
3. `jupyter labextension list` and `jupyter serverextension list` should not contain any references to Kite anymore. If they do, navigate to the Config directory listed and delete the config files
4. Run `pip install "jupyterlab-kite>=2.0.2"`

**Comment by Dekay999** [comment]
Thank you very much@edzkite, this solved my problem perfectly.

**Comment by Starslayerx** [comment]
Same issue, I'm linux(pop_os) with jupyter 3.0.3.
```bash
jupyter labextension list
jupyter srerverextension list
```
> If this commands still show something like uninstalled core extensions...(after you uninstalled the plug)

1. use this command to find your jupyter path
```bash
jupyter --paths
```
2. find file **build_config.json** and delete it, then the uninstalled information should gone.
You can find more information [here](https://github.com/jupyterlab/jupyterlab/issues/8122).
Hope this helps.

**Comment by Starslayerx** [comment]
> Same issue, I'm linux(pop_os) with jupyter 3.0.3.
> 
> ```shell
> jupyter labextension list
> jupyter srerverextension list
> ```
> 
> > If this commands still show something like uninstalled core extensions...(after you uninstalled the plug)
> 
> 1. use this command to find your jupyter path
> 
> ```shell
> jupyter --paths
> ```
> 
> 1. find file **build_config.json** and delete it, then the uninstalled information should gone.
>    You can find more information [here](https://github.com/jupyterlab/jupyterlab/issues/8122).
>    Hope this helps.

It still not work for me even all plug is ok
```bash
$ jupyter serverextension list
config dir: /home/starslayerx/.jupyter
    jupyter_kite  enabled
    - Validating...
      jupyter_kite 2.0.2 OK

$ jupyter labextension list
JupyterLab v3.0.3
/home/starslayerx/.local/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @kiteco/jupyterlab-kite v2.0.2 enabled OK (python, jupyterlab_kite)

Other labextensions (built into JupyterLab)
   app dir: /home/starslayerx/.local/share/jupyter/lab
```
this is warning from jupyterlab
```
Server Extension Unreachable

The jupyterlab-kite extension will not work because the jupyter-kite server extension could not be reached.

To fix this, please ensure the jupyter-kite server extension is installed and active (`jupyter serverextension list`), then restart the JupyterLab process.
```
- In the json file, the plug is called **jupyter_kite** ,but jupyterlab says**jupyter-kite**. It confused me.

**Comment by Starslayerx** [comment]
I did this again(with proxychains), then it worked!
I think my network is not good enough before.

**Comment by mixaal** [comment]
In case anyone bumps into an issue that lab extensions shows kite but server extensions doesn't the explicit enable helped me:
```
jupyter serverextension enable 'jupyter_kite'
```

**Comment by nett7** [comment]
I had recently this problem, do all stuff above, but it didn't help. The solution was in fact, that not all jupyter-lab versions supported  kite, so I switch to previous version by command

` pip3 install jupyterlab==3.0.14
`

and it works! (3.0.16 doesn't work at this moment), so switch to appropriate previous verson

**Comment by ahmadasmandar** [comment]
> I had recently this problem, do all stuff above, but it didn't help. The solution was in fact, that not all jupyter-lab versions supported kite, so I switch to previous version by command
> 
> `pip3 install jupyterlab==3.0.14`
> 
> and it works! (3.0.16 doesn't work at this moment), so switch to appropriate previous verson

thank you it is working now

**Comment by jithu7432** [comment]
> I had recently this problem, do all stuff above, but it didn't help. The solution was in fact, that not all jupyter-lab versions supported kite, so I switch to previous version by command
> 
> `pip3 install jupyterlab==3.0.14`
> 
> and it works! (3.0.16 doesn't work at this moment), so switch to appropriate previous verson


Yes, can confirm this.

**Comment by Zhu-Haobo** [comment]
> I had recently this problem, do all stuff above, but it didn't help. The solution was in fact, that not all jupyter-lab versions supported kite, so I switch to previous version by command
> 
> `pip3 install jupyterlab==3.0.14`
> 
> and it works! (3.0.16 doesn't work at this moment), so switch to appropriate previous verson

It works, thank you!

**Comment by VyNgo97** [comment]
I'm running jupyer-labs 3.0.14 and with extension version 2.0.2 and running into this issue after trying all of the above. When I start up, jupyter labs says "The jupyterlab-kite extension will not work because the jupyter-kite server extension could not be reached". I've enabled jupyter-kite but still no fix. This is on windows but using WSL.

**Comment by mohellen** [comment]
> I had recently this problem, do all stuff above, but it didn't help. The solution was in fact, that not all jupyter-lab versions supported kite, so I switch to previous version by command
> 
> `pip3 install jupyterlab==3.0.14`
> 
> and it works! (3.0.16 doesn't work at this moment), so switch to appropriate previous verson

Thank you! I was on `3.0.16` it didn't work. Downgrading to `3.0.14` works!  (I'm on macOS Big Sur 11.5.2)

**Comment by duckbill** [comment]
```
conda search nodejs
conda install nodejs==16.6.1 -c conda-forge
```

**Comment by orome** [comment]
> I've updated our extension so that it should support JupyterLab 3.0+. To upgrade:
> 
> 1. Uninstall `jupyter-kite` (`pip uninstall jupyter-kite`)
> 2. Uninstall `@kiteco/jupyterlab-kite` (`jupyter labextension uninstall @kiteco/jupyterlab-kite`)
> 3. `jupyter labextension list` and `jupyter serverextension list` should not contain any references to Kite anymore. If they do, navigate to the Config directory listed and delete the config files
> 4. Run `pip install "jupyterlab-kite>=2.0.2"`

This doesn't work for me. 

Is it still the case that Kite doesn't work in JupyterLab (3.4)?

**Comment by caleb98kymez** [comment]
> > I've updated our extension so that it should support JupyterLab 3.0+. To upgrade:
> > 
> > 1. Uninstall `jupyter-kite` (`pip uninstall jupyter-kite`)
> > 2. Uninstall `@kiteco/jupyterlab-kite` (`jupyter labextension uninstall @kiteco/jupyterlab-kite`)
> > 3. `jupyter labextension list` and `jupyter serverextension list` should not contain any references to Kite anymore. If they do, navigate to the Config directory listed and delete the config files
> > 4. Run `pip install "jupyterlab-kite>=2.0.2"`
> 
> This doesn't work for me.
> 
> Is it still the case that Kite doesn't work in JupyterLab (3.4)?

It's not yet being updated to support that version. Use Jupyter lab v3.0

**Comment by orome** [comment]
> It's not yet being updated to support that version. Use Jupyter lab v3.0

When will it work with the version of JupyterLab people are using (3.4)?
