### ISSUE TITLE
Kite is not working in Jupyter Lab 3+

### ISSUE THREAD

**Issue by floriandotorg** [kiteco/issue-tracker#541]
**Describe the bug**

***Steps to reproduce***
- pip3 install jupyterlab jupyter-kite
- jupyter labextension install "@kiteco/jupyterlab-kite"
- jupyter lab
- check version is 3.x.x

***Expected behaviour***
- Kite is running fine

***Actual behaviour***
- Kite is not showing up
- Inspector shows following error:
```
index.es6.js:282 Plugin '@kiteco/jupyterlab-kite:plugin' failed to activate.
(anonymous) @ index.es6.js:282
index.es6.js:283 TypeError: Cannot read property 'composite' of undefined
    at new _ (model.js:71)
    at new ei (kite_accessible.js:23)
    at Function.ei.CreateAsync (kite_accessible.js:142)
    at async activate (index.js:52)
    at async Promise.all (index 101)
```

**Screenshots**
![CleanShot 2021-01-05 at 17 50 45](https://user-images.githubusercontent.com/6143734/103681389-aefe1b00-4f87-11eb-9fd4-794abab52233.png)

**Comment by edzkite** [comment]
Please see https://github.com/kiteco/issue-tracker/issues/532#issuecomment-754197763. Closing as duplicate.

**Comment by edzkite** [comment]
I've updated our extension to support JupyterLab 3.0, with [instructions to update](https://github.com/kiteco/issue-tracker/issues/532#issuecomment-757050104). Please let me know if this resolves things for you!
