### ISSUE TITLE
jupyter labextension install failed

### ISSUE THREAD

**Issue by bleyfueszt** [kiteco/issue-tracker#542]
Required informations : 

- Your OS = Windows 10
- Your browser console logs = 

[Browser log.log](https://github.com/kiteco/issue-tracker/files/5776642/Browser.log.log)

- The output of jupyter labextension list and jupyter serverextension list : 

JupyterLab v2.2.6
Known labextensions:
   app dir: D:\ProgramData\Anaconda3\share\jupyter\lab
        @kiteco/jupyterlab-kite v1.2.0 enabled  ok

config dir: D:\ProgramData\Anaconda3\etc\jupyter
    jupyter_kite enabled
    - Validating...
      jupyter_kite 1.2.0 ok
    jupyterlab enabled
    - Validating...
      jupyterlab 2.2.6 ok

- The output of pip list

[pip list output.txt](https://github.com/kiteco/issue-tracker/files/5776646/pip.list.output.txt)

- If you use conda, please share your environment

Yes I use an environment ! (Can't import .yml file)

**Describe the bug**

When I run " jupyter labextension install "@kiteco/jupyterlab-kite" ", I finally have this output in the terminal (see Output labextension install.txt) 
[Output labextension install.txt](https://github.com/kiteco/issue-tracker/files/5776715/Output.labextension.install.txt)

Then Jupyter Lab say that the build is complete and need to reload (see "build complete.jpg")
![build complete](https://user-images.githubusercontent.com/77060153/103788873-a23cfe00-503f-11eb-9486-df69787d30d1.jpg)

and when I reload, Jupyter says that a build is recommended. (see "build recommended.jpg")
![build recommended](https://user-images.githubusercontent.com/77060153/103788890-a6691b80-503f-11eb-9234-3d542319e120.jpg)

Then if I press build, it restart the procedure and I get again the "build complete" message and this is going forever. 

How can I complete the installation of the extension in Jupyterlab ?

Thanks.

**Comment by edzkite** [comment]
Can you try running `jupyter lab build` via the command line, then restarting JupyterLab? It may also be helpful to exit any active JupyterLab processes before doing this.

**Comment by bleyfueszt** [comment]
I tried but same error.

**Comment by bleyfueszt** [comment]
I think i was on a bad version of jupyterlab ! I upgrade it to 3.0.1 
=> 
![Jupyterlab version](https://user-images.githubusercontent.com/77060153/103881016-2b087800-50da-11eb-8322-66a00a85926f.jpg)
But still a problem when i run "jupyter labextension install "@kiteco/jupyterlab-kite" "

Here is what I get : 
![building error](https://user-images.githubusercontent.com/77060153/103881467-c4378e80-50da-11eb-9987-9584eebf2d23.jpg)
And there is the log file : 
[jupyterlab-debug-kh9zmuvm.log](https://github.com/kiteco/issue-tracker/files/5780987/jupyterlab-debug-kh9zmuvm.log)

**Comment by edzkite** [comment]
Unfortunately, we don't support JupyterLab 3.0+ yet (it should be rolling out soon!). You'll need to downgrade to JupyterLab 2.2.x.

I would then try uninstalling the extension `jupyterlab labextension uninstall @kiteco/jupyterlab-kite`, ensuring `D:\ProgramData\Anaconda3\share\jupyter\lab` does not contain any artifacts leftover, then reinstalling the plugin.

**Comment by edzkite** [comment]
I've updated our extension to support JupyterLab 3.0, with [instructions to update](https://github.com/kiteco/issue-tracker/issues/532#issuecomment-757050104). Please let me know if this resolves things for you!

**Comment by bleyfueszt** [comment]
It worked on 2.2.6 ! Thanks !
