### ISSUE TITLE
Kite Jupyterlab on Centos remote machine

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [kiteco/issue-tracker#544]
**Describe the bug**
Kite installed on a remote machine with Centos and already run, but the Jupyter lab can't detect it

**Screenshots**
![image](https://user-images.githubusercontent.com/35159954/103888466-607f8680-5117-11eb-9ba7-773740692105.png)
![image](https://user-images.githubusercontent.com/35159954/103888485-69705800-5117-11eb-94fa-43857c2c8fc3.png)

**Comment by edzkite** [comment]
While we don't officially support remote installs, these are the steps required:

- Check all prerequisites are met, and install/update where necessary.
- Install Kite
- Install Kite JupyterLab Extension
- Check output of `jupyter serverextension list`. If nothing appears, run `jupyter serverextension enable jupyter_kite`.
- Launch JupyterLab: `jupyter lab --no-browser`
- Port forward 8888 (or whatever port JupyterLab's launched with) to the remote instance’s localhost:8888
- Use one of the URLs with the token generated by `jupyter lab`

**Comment by bhaskoro-muthohar** [comment]
I able to managed it to work by restarted my Jupyter-lab service, it works properly now.
