### ISSUE TITLE
Does Kite have an auto-updater?

### ISSUE THREAD

**Issue by VladPutinEu** [kiteco/issue-tracker#546]
I have Kite installed but I don't know if it has an auto-updater. I couldn't find an update button in the application. Does it have an auto-updater or not? How does it update?

**Comment by metalogical** [comment]
Kite automatically updates in the background without any user action. You can see the current version in the settings tab of the Kite Copilot window. If you suspect that Kite is not updating, please provide your version number.

**Comment by VladPutinEu** [comment]
@metalogical Thanks for the help. This answers my question.
