### ISSUE TITLE
Kite not working with Jupyter Notebook

### ISSUE THREAD

**Issue by mcerini** [kiteco/issue-tracker#552]
I couldn't find any other issue exactly like mine, though I tried...

These are steps:
1. Installed Kite on Windows 10 machine as instructed.  No errors.
2. Ran pip install "jupyterlab-kite>=2.0.2"
3. Restarted jupyter notebook 
4. Tested, but autocomplete NOT happening.
5. I checked the following:

> pip list 
jupyter             1.0.0
jupyter-client      6.1.7
jupyter-console     6.2.0
jupyter-core        4.7.0
jupyter-kite        2.0.2
jupyter-server      1.2.1
jupyterlab          3.0.4
jupyterlab-kite     2.0.2
jupyterlab-pygments 0.1.2
jupyterlab-server   2.1.2

> jupyter labextension list
JupyterLab v3.0.4
c:\users\django\.pyenv\pyenv-win\versions\3.8.2\share\jupyter\labextensions
        @kiteco/jupyterlab-kite v2.0.2 enabled ok (python, jupyterlab_kite)

> jupyter serverextension list
config dir: c:\users\django\.pyenv\pyenv-win\versions\3.8.2\etc\jupyter
    jupyterlab enabled
    - Validating...
      jupyterlab 3.0.4 ok

> jupyter --paths
config:
    C:\Users\Django\.jupyter
    c:\users\django\.pyenv\pyenv-win\versions\3.8.2\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\Django\AppData\Roaming\jupyter
    c:\users\django\.pyenv\pyenv-win\versions\3.8.2\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\Django\AppData\Roaming\jupyter\runtime

Observations:
- I am getting no kite errors when running > jupyter notebook --port 9999
- While I don't see kite in the jupyter serverextension list, I do see the following in the config dir: c:\users\django\.pyenv\pyenv-win\versions\3.8.2\etc\jupyter

![image](https://user-images.githubusercontent.com/686324/104500795-e040a180-55ac-11eb-8d01-4119de36d9f8.png)

Thanks in advance.

**Comment by edzkite** [comment]
Are you using `jupyter notebook` or `jupyterlab`? Kite is only supported in `jupyterlab`.

**Comment by mcerini** [comment]
I guess that was an easy one.  I hadn't used jupyterlab before.  I just installed jupyterlab now, opened my code and autocomplete seems to be working there, although the responsiveness seems very slow.  Why it works in one and not the other is beyond me, but I guess I'll try using jupyterlab.  It seems similar enough and I could use the autocomplete.  Thanks much!
