### ISSUE TITLE
associate a custome filename extension with a language

### ISSUE THREAD

**Issue by gzt5142** [kiteco/issue-tracker#566]
I find myself often coding in Python for a specific curated environment (Esri's ArcGIs Pro).  The code is pure Python, but their system requires that "python toolbox" files end with .pyt.  I am unable to use Kite for those python files because they don't end in .py. 

My IDE (PyCharm) allows a configuration to associate an arbitrary extension to a language.  I would love it if I could do something similar with Kite: convince Kite to participate in the coding of these .pyt files.  I have not yet  been able to find a way to convince it that pyt==python.   

Many Thanks, 

--gt

**Comment by metalogical** [comment]
Thanks for the issue. For now, we can simply manually add `.pyt` as a Python file extension.

**Comment by metalogical** [comment]
This should be fixed in the next Kite release (later this week).
