### ISSUE TITLE
Kite Not Running

### ISSUE THREAD

**Issue by iwatts3519** [kiteco/issue-tracker#567]
Hi
I have tried all of the suggestions I have found but I constantly have Kite Not Running displayed in Jupyter Labs, even though Kite is Running.
I have generated logs from within coPilot - https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/172060/kite_local/client.log.2021-01-26_12-55-44-PM.bak.gz

I just cannot seem to get it to work - the computer has been restarted several times, NODE.JS has been installed - I have used the correct installation method for my version of JupyterLab, but nothing seems to work. I love having Kite in my other environments and am really missing it in this.
Cheers
Ian

An have attached all of the logs that I can think of:

<img width="305" alt="Screenshot 2021-01-26 124428" src="https://user-images.githubusercontent.com/24248852/105847747-eb94c380-5fd5-11eb-985e-9de4f8362c9b.png">
[conda list.txt](https://github.com/kiteco/issue-tracker/files/5873358/conda.list.txt)
[console log.txt](https://github.com/kiteco/issue-tracker/files/5873359/console.log.txt)
[jupyter serverextension list.txt](https://github.com/kiteco/issue-tracker/files/5873360/jupyter.serverextension.list.txt)
<img width="292" alt="Kite" src="https://user-images.githubusercontent.com/24248852/105847750-ed5e8700-5fd5-11eb-838c-46b88f5358e4.png">
[localhost-1611664931137.log](https://github.com/kiteco/issue-tracker/files/5873361/localhost-1611664931137.log)

**Comment by edzkite** [comment]
Hi @iwatts3519,

Thanks for writing in and providing all the logs. It looks like there's a bug on our end that's causing this issue. I'll keep you posted as soon as a fix is available.

**Comment by iwatts3519** [comment]
Thanks – I did have a thought that there seems to be a clash between Jupyter’s normal autocomplete (it clashes with Jedi 0.18, so I have had to downgrade it to 0.17). Could that be the cause?

**Comment by bamel-yashvander** [comment]
I too have the same problem integrating kite to jupyter. 

            >>>jupyter labextension list
            JupyterLab v2.2.6
            Known labextensions:
               app dir: C:\Users\YASHVANDER\anaconda3\share\jupyter\lab
                    @kiteco/jupyterlab-kite v1.2.0 enabled 

Seems that the extension is installed and enabled as well, but don't know where the problem is.

**Comment by edzkite** [comment]
> Thanks – I did have a thought that there seems to be a clash between Jupyter’s normal autocomplete (it clashes with Jedi 0.18, so I have had to downgrade it to 0.17). Could that be the cause?

@iwatts3519 No, it's unrelated. However, that will fix issues with providing kernel completions (which are generated by Jedi).

**Comment by edzkite** [comment]
@bamel-yashvander Could you please provide some more information https://github.com/kiteco/jupyterlab-kite/wiki/Troubleshooting?

**Comment by iwatts3519** [comment]
@edzkite Any eta on when this might be fixed

**Comment by edzkite** [comment]
@iwatts3519 Unfortunatley, I'm blocked from reproducing this bug due to https://github.com/jupyterlab/jupyterlab/issues/9726.
 
That said, I noticed in the logs that you were working with a file named `D:\OneDrive - University of Keele\CSC - 4007 - Application of AI\notebooks\.virtual_documents\Lab 1.ipynb.py`. 

For testing purposes, could you see if Kite works for notebooks launched from the C:\ Drive?

**Comment by iwatts3519** [comment]
Interestingly I had that error - [ jupyterlab/jupyterlab#9726](https://github.com/jupyterlab/jupyterlab/issues/9726). - and somehow managed to get rid of it (I can't remember how) - I've just tried on the C Drive and it is the same error - it is not recognising that Kite is installed even though it is

![image](https://user-images.githubusercontent.com/24248852/107341240-a208a600-6ab6-11eb-915f-1a68510c0b37.png)

**Comment by iwatts3519** [comment]
Someone suggested I try installing it all in my base environment first (which is on the C drive) before trying to get it in a specific environment - and then triggering Redo Setup - that didn't work either

![image](https://user-images.githubusercontent.com/24248852/107372077-ec9d1900-6adc-11eb-9a73-30337844de07.png)

**Comment by iwatts3519** [comment]
Hi @edzkite - just to let you know everything suddenly seems to be working - not sure if you have done something at your end but Kite is now running in Jupyter Lab for me

**Comment by edzkite** [comment]
Happy to hear that @iwatts3519! We haven't done anything on our end, so that's definitely interesting.

Thanks for bearing with us through this though. Feel free to reach out if you have any feedback or run into additional issues with Kite for JupyterLab!
