### ISSUE TITLE
Kite icon not showing in VS Code

### ISSUE THREAD

**Issue by kundanb** [kiteco/issue-tracker#568]
I installed the Kite Engine with the extension installed, done everything as documented at the official kite website. But nothing worked.

![Screenshot from 2021-01-30 21-13-40](https://user-images.githubusercontent.com/67975986/106360720-22553b80-6340-11eb-8d3b-724f720223bc.png)

**Comment by edzkite** [comment]
Does the file end with a `.js` extension? If not, the status bar won't show.
