### ISSUE TITLE
Kite is stuck at “Initializing” in JupeterLab

### ISSUE THREAD

**Issue by leanhdung1994** [kiteco/issue-tracker#569]
I have installed Kite for `JupyterLab 2.2.9`. I dont know why it is stuck at "Initializing":

![image](https://user-images.githubusercontent.com/28704090/106369113-0f963300-634f-11eb-80e2-e6488ac26af4.png)

Could you please elaborate on this issue?

**Comment by edzkite** [comment]
Kite can take some time to index your code and warm up its models. Do you receive any completions? If so, it should be okay to ignore.

**Comment by questerashish** [comment]
> I have installed Kite for `JupyterLab 2.2.9`. I dont know why it is stuck at "Initializing":
> 
> ![image](https://user-images.githubusercontent.com/28704090/106369113-0f963300-634f-11eb-80e2-e6488ac26af4.png)
> 
> Could you please elaborate on this issue?

same issue with me
