### ISSUE TITLE
Kite on Linux is failing to update it self

### ISSUE THREAD

**Issue by Spurlos** [kiteco/issue-tracker#574]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
Seems that self-update process is automatic, but something is causing it to fail.

OS: Ubuntu 20.10
Kite Version: 2.20201221.0

**Screenshots**
![image](https://user-images.githubusercontent.com/667533/106668518-073e3200-65b3-11eb-995d-94ac69c91b50.png)
![image](https://user-images.githubusercontent.com/667533/106672383-a1ed3f80-65b8-11eb-859c-c96ebd5bdc74.png)

**Logs**
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/ebb5ec9e-052e-44de-b86b-8d0eb11408e9/kite_local/client.log.2021-02-03_12-02-34-AM.bak.gz

**Comment by Spurlos** [comment]
Command output:
~$ ~/.local/share/kite/current/kite-update update
[update] found version 2.20201221.0 installed
[update] latest version is 2.20210114.0, downloading now...
[update] Downloading Kite:  100.0% of 12 MiB
[update] verifying checksum
[update] validating signature
[update] installing version 2.20210114.0
[update] failed to update kite: exit status 1, output: 'Creating directory patch
Verifying archive integrity...  100%   All good.
Uncompressing Kite patch updater, version 2.20201221.0-2.20210114.0  100%  
Creating tar of previous version directory...
Applying patch update... 
bspatch: Invalid input checksum: expected e6 7b b6 d1 c2 42 39 b5 f0 61 95 42 63 94 16 fc 8d 68 6a ef 31 7b f3 1a d4 6d d8 ff 8b a3 6f d1, but got 4f 13 05 9c 00 f0 40 30 bd f4 7d 90 b8 a9 f5 1f c9 06 c2 8c 2c 9e f3 62 ae 7d 04 95 fd d7 d7 4d
usage: ./bspatch oldfile newfile patchfile
Cleaning up...
'

**Comment by metalogical** [comment]
We just released a new version which will probably fix this for you. Let us know if there's still an issue for further debugging.

**Comment by Spurlos** [comment]
Just read your reply and retried the update command:
```
$ ~/.local/share/kite/current/kite-update update
[update] found version 2.20210128.0 installed
[update] already up to date!
```
Et voila - its already updated itself in the background and self repaired.

Considering this bug closed indeed. Thank you for your fast support!
