### ISSUE TITLE
Problem with installing kite for jupyter-lab 2.2.6

### ISSUE THREAD

**Issue by bamel-yashvander** [kiteco/issue-tracker#575]
I tried installing the kite plugin for jupyter lab 2.2.6 and all went well, there was no error during the execution of `pip install jupyter-kite<2.0.0`, `conda install nodejs` and `jupyter labextension install "@kiteco/jupyterlab-kite"`.

My operating system currently is Windows 10 Home.

When I started jupyter lab it showed the following error (screenshot):

![image](https://user-images.githubusercontent.com/51825289/106701373-8d3a9700-660c-11eb-876e-5b37827a1dc9.png)

After clicking "fix this" it takes me to download kite setup and on opening the setup, as I already have it installed, windows gives a warning that if I wish to install kite again, first I need to uninstall it.

![image](https://user-images.githubusercontent.com/51825289/106702785-f4f1e180-660e-11eb-9835-6cb77f143ea7.png)

Following is the kite console:
![image](https://user-images.githubusercontent.com/51825289/106701611-f0c4c480-660c-11eb-8f66-8e77f2e6a40d.png)

The logs generated from KITE application: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/efc931bb-fa94-4ca4-a3a0-12786b7191ce/kite_local/client.log.2021-02-03_10-21-54-AM.bak.gz

I am attaching a text file with other necessary command outputs:
[kite.txt](https://github.com/kiteco/issue-tracker/files/5916242/kite.txt)

**Comment by edzkite** [comment]
- Is Kite installed at `C:\Program Files\Kite\kited.exe'? If it's not present there, that is why the notification may be showing.
- If not, could you also provide your browser console logs, as well as the logs from your shell when you run Jupyter Lab?

**Comment by bamel-yashvander** [comment]
> * Is Kite installed at `C:\Program Files\Kite\kited.exe`? If it's not present there, that is why the notification may be showing.
> * If not, could you also provide your browser console logs, as well as the logs from your shell when you run Jupyter Lab?

I used to start Jupyter Lab from Anaconda Navigator. I started it from command prompt this time so that I could generate logs and surprisingly my problem got solved itself. Now whether I run it from cmd or Anaconda, kite gets initialized automatically.

But my kite application still doesn't show the plugin installed for jupyter lab, if that's a problem. Kite is working fine though.

**Comment by edzkite** [comment]
Interesting, but good to hear that it's working for you. From the Kite application side, it'll always show JupyterLab as an available plugin to install.
