### ISSUE TITLE
how to manage/cancel kite pro subscription?

### ISSUE THREAD

**Issue by cschou** [kiteco/issue-tracker#579]
I want to stop my kite pro subscription for several months. But i cannot find the page to do it.
Please tell me how to do it. It just keeps billing me even when I want to stop using it.
I am quite pissed off by this.

**Comment by edzkite** [comment]
1. Open the Kite Copilot
2. Hit the settings icon in the bottom right
3. Select the Manage button under Account
4. A web page should open with an option to cancel your subscription. If you don't see it, please let us know.

**Comment by bkaufman** [comment]
even this takes forever to load.  how do i cancel?

![image](https://user-images.githubusercontent.com/4714060/109215958-e3b97200-7781-11eb-8411-381acfc1fd7d.png)

**Comment by edzkite** [comment]
@bkaufman Apologies for the inconvenience. Could you try going to https://www.kite.com/settings/account? It may ask you to login. If you run into issues, please let us know and we can continue to assist you from there.
