### ISSUE TITLE
How to disable kite hint snippet setting in VSCode?

### ISSUE THREAD

**Issue by aidenhsy** [kiteco/issue-tracker#581]
The most recent update of Kite added a hint feature on the right of every line my cursor is on, which gets super annoying. I want to continue using Kite but I don't want this "Find related code in " to follow the cursor around.
<img width="1069" alt="Screen Shot 2021-02-17 at 9 03 16 AM" src="https://user-images.githubusercontent.com/66299882/108141978-d0623300-70ff-11eb-9840-1baf3404135a.png">
<img width="688" alt="Screen Shot 2021-02-17 at 9 03 20 AM" src="https://user-images.githubusercontent.com/66299882/108141983-d3f5ba00-70ff-11eb-8882-41b44dbdba8b.png">

**Comment by kDweuV** [comment]
Search in the settings for "Kite > Copdefinder > Enable Line Decoration" and disable it. That helped me.

**Comment by cidgi359** [comment]
For Atom, Settings > Packages > Kite > Enable codefinder decoration, disable this.

**Comment by its-dhung** [comment]
@kDweuV's settings fix works.

**Comment by rveruna** [comment]
I have no such thing in settings, where do you disable this? it's extremely annoying!

**Comment by cidgi359** [comment]
I was talking about Atom. Not VSCode. I'm sorry for the misunderstanding. 
Because I had the same problem on Atom. I was thinking to help all the persons using Atom also on this post.

**Comment by Yunoon** [comment]
![image](https://user-images.githubusercontent.com/48115765/114297911-11663a80-9ae6-11eb-84a8-a07ff0250d66.png)
You can disable this funciton in this pic
