### ISSUE TITLE
Kite stopped working

### ISSUE THREAD

**Issue by tomkessler** [kiteco/issue-tracker#582]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [X] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [X] Include your Kite application logs, _taken while you are experiencing your issue_.
- [X] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [X] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
Kite was working great in both Jupyter Lab and PyCharm but is no longer providing autocomplete, or co-pilot contextual help.  I'm on Mac OS Catalina.  I did just apply the update to 10.15.7.  I also did just apply the update to PyCharm to 2020.3.3.

Kite v0.20210212.0
Jupyter Lab  v2.2.6
PyCharm 2020.3.3

Jupyter Lab:
It seems to be loading now and I have "Kite: ready" in the status bar at the bottom, but the copilot updates and autocompletes come _painfully_ slowly.

PyCharm:
Red kite icon at the bottom right in the status bar.  Kite plugin is installed.
[idea.log](https://github.com/kiteco/issue-tracker/files/5998756/idea.log)

In order to try and troubleshoot all this, i have uninstalled Kite via the documentation and reinstalled it, including the plugins.  One thing to note is that I did kill the launctl item noted in the uninstall docs and it has not come back.  The Kite helper.

Within the copilot, "Fetching Account info" takes 60+s to come up.  And on the plugins page, 3 dots are pulsing for a long time.

Logs:
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/477198/kite_local/client.log.2021-02-17_02-44-53-PM.bak.gz
https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/477198/kite_local/1613597500994507000/capture.gz
https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/477198/kite_local/1613621177904725000/capture.gz

**Screenshots**

Kite is no longer working in PyCharm:
![image](https://user-images.githubusercontent.com/20233788/108270817-93b12e80-7135-11eb-9ec4-b41c40600459.png)
but plugin is installed.  i reinstalled it.
![image](https://user-images.githubusercontent.com/20233788/108271150-fefb0080-7135-11eb-8ba4-4df4fba64e84.png)

This took 30-60s to come up:
![image](https://user-images.githubusercontent.com/20233788/108271068-e25ec880-7135-11eb-9088-b3b38de106b9.png)

Kite Engine is really hammering my system!  Highest CPU time of any process, by a long shot.
![image](https://user-images.githubusercontent.com/20233788/108382968-fb678800-71ce-11eb-9062-bfe2f2a8ddc8.png)

**Comment by canersnli** [comment]
Having same issue on JupyterLab

**Comment by paclonanalytics** [comment]
Greetings! Same problem. Moreover, if I turn off the Internet, then kite works fine.

**Comment by edzkite** [comment]
Hey everyone, apologies for dropping the ball here and not responding to this in a timely fashion. 

We've increased our capacity in the backend, and are in the process of shipping an update to the Copilot that should hopefully resolve this.   If you’re continuing to experience issues with completions or the Copilot, please let us know. 
 
Again, we’re truly sorry for the inconvenience, and we appreciate your support as we work to improve our product and processes.
