### ISSUE TITLE
Extensive initialization time and no autocompletes

### ISSUE THREAD

**Issue by JudoWill** [kiteco/issue-tracker#584]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [x] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
I've been successfully using Kite for months now without a problem but I've started to run into issues today.

Ubuntu 20.04
Jupyterlab plugin & PyCharm plugin.

The "Kite: initializing" note runs for excessive amounts of time (upwards of 15-20 minutes) even when running an empty environment and only opening the tutorial notebook.

If it ever says "Kite: ready" as-you-type completions don't load, tab-complete takes a few minutes, and the Co-Pilot never brings up the relevant docs.

Looking in the Local Settings of the app, the Account section has been "Fetching account info" for at least 20 minutes. It did eventually bring up my Pro account. But after switching to the logs tab to generate the links below and then coming back, back to "Fetching account info ..."

At first I thought it was issues with newly built conda environments and version mismatches between jupyterlab, nodejs, or Kite engine. But even previously working environments have the same issue.

Things I've tried so far:
  - Restarting
  - Creating new environments with jupyterlab 2.* and nodejs14 (pip install jupyterlab-kite)
  - Creating new environments with jupyterlab 3.0.3 (using jupyterlab-kite>2.0.2)
  - Creating new environments with jupyterlab 3.0.3 and nodejs14 (using jupyterlab-kite>2.0.2)
  - Routing through the jupyterlab extensions directories to make sure things were properly uninstalled and reinstalled. As per https://github.com/kiteco/issue-tracker/issues/532#issuecomment-757461681
  - Deleting the Kite app completely from my computer and reinstalling. 
 
So, I'm at a bit of a loss.

Logs were created in a previously working environment while pressing tab to autocomplete after one notebook was "Kite: ready".

App Logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/131856/kite_local/client.log.2021-02-18_03-46-56-PM.bak.gz
Resource Logs: https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/131856/kite_local/1613681328458350513/capture.gz

**Comment by tomkessler** [comment]
This sounds like an eerily similar situation to what I am experiencing:  https://github.com/kiteco/issue-tracker/issues/582

**Comment by JudoWill** [comment]
> This sounds like an eerily similar situation to what I am experiencing: #582
@tomkessler 
As I was poking around yesterday it looks like there are a few similar bug-reports to ours. At least I don't feel silly anymore thinking I broke something on my end.

**Comment by canersnli** [comment]
Having same issue, downgraded from Jupyter Lab 3.0.6 to 2.2.8 and reinstalled kite but it didnt work.

**Comment by datafitEU** [comment]
Just filed a similar issue before reading yours. The surprising thing is that I have a second machine in which it works like a charm...

**Comment by paclonanalytics** [comment]
This error is terribly annoying. Kite only works with disconnected internet.

**Comment by JudoWill** [comment]
@paclonanalytics, I haven't tried disconnecting the internet. I'll give that a try. But, that would be massively annoying since many of the things I'm coding query the internet. I'd have to make some sort of weird firewall rules to blacklist Kite while allowing other traffic through. 

I assumed someone from @kiteco would drop into these issue chats and provide support. Especially when there are several similar issues in the tracker. Was that an incorrect assumption?

**Comment by paclonanalytics** [comment]
@JudoWill I agree with you. The fix of the problem is clearly lacking. Taking into account the fact that the subscription is paid for, and the service simply cannot be used for as long as 2 weeks. @kiteco

**Comment by edzkite** [comment]
Hi everyone, please see our response [here](https://github.com/kiteco/issue-tracker/issues/582#issuecomment-786951619). If this issue still persists, please follow up in that issue.

**Comment by ArrowRaider** [comment]
I just installed Kite for the first time and Kite is stuck on initializing in JupyterLab.
