### ISSUE TITLE
No completion anymore in Atom when the copilot is open

### ISSUE THREAD

**Issue by alexnanchen** [kiteco/issue-tracker#585]
Hello,

I am using Atom as a code editor on Macosx 11.2.1 (Big sur). 

Suddenly code completion has stopped working when I open tho copilot. When it is closed, completion is fine. I am logged in as a pro user. When looking at the copilot settings, everything is very slow even for setting an option and it takes ages to fetch the account information. The copilot also do not follow the code as usual and do not display help.

Could you please help.

Many thanks.

Best regards.

Alexandre

**Comment by alexnanchen** [comment]
Very similar to bug #582. It is a bit frustrating.

**Comment by edzkite** [comment]
Hi everyone, please see our response [here](https://github.com/kiteco/issue-tracker/issues/582#issuecomment-786951619). If this issue still persists, please follow up in that issue.
