### ISSUE TITLE
Kite fails to initialize

### ISSUE THREAD

**Issue by datafitEU** [kiteco/issue-tracker#592]
I'm using Kite Pro (recently upgraded) in 2 computers (Mac) with identical OS version (11.2.1). One one machine Kite works like a charm, on the other (slightly higher spec) the VS Code plugin is stuck on initializing. Occasionally it initializes but even when the status shows as Ready, it doesn't autocomplete. The Copilot is set to follow the code but it never finds anything and it remains stuck in searching. When opening the settings windows it remains Fetching account info for a very long time.

I restarted the machine, VS Code and Kite several times, including reinstalling the plugin and Kite itself with no change
<img width="396" alt="Screenshot 2021-02-23 at 20 13 09" src="https://user-images.githubusercontent.com/65308285/108895209-97e8ba80-7613-11eb-92d2-de98ee64916d.png">
<img width="557" alt="Screenshot 2021-02-23 at 20 05 42" src="https://user-images.githubusercontent.com/65308285/108895213-9919e780-7613-11eb-91b8-be12f13753ef.png">
<img width="399" alt="Screenshot 2021-02-23 at 20 04 11" src="https://user-images.githubusercontent.com/65308285/108895214-99b27e00-7613-11eb-9249-edf5d6abe629.png">
<img width="401" alt="Screenshot 2021-02-23 at 20 03 44" src="https://user-images.githubusercontent.com/65308285/108895217-9a4b1480-7613-11eb-8159-73a41f3f68fe.png">

Application Logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/353667/kite_local/client.log.2021-02-23_08-12-54-PM.bak.gz

Performance Log: https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/353667/kite_local/1614108568042517000/capture.gz

**Comment by datafitEU** [comment]
I now started to get the following

<img width="399" alt="Screenshot 2021-02-24 at 13 50 06" src="https://user-images.githubusercontent.com/65308285/109003106-51dd3680-76a7-11eb-95bc-0925627ee71f.png">

**Comment by datafitEU** [comment]
I discovered that keeping copilot closed, Kite initializes properly and autocomplete works fine. As soon as copilot is opened, autocomplete stops working. Closing copilot and restarting Kite (Quit + Reopen) fixes autocomplete

**Comment by venman123** [comment]
> I discovered that keeping copilot closed, Kite initializes properly and autocomplete works fine. As soon as copilot is opened, autocomplete stops working. Closing copilot and restarting Kite (Quit + Reopen) fixes autocomplete

I noticed the same thing.  I'm still not sure what the copilot is good for yet.

**Comment by edzkite** [comment]
Hi everyone, please see our response [here](https://github.com/kiteco/issue-tracker/issues/582#issuecomment-786951619). If this issue still persists, please follow up in that issue.
