### ISSUE TITLE
request install old version

### ISSUE THREAD

**Issue by TechComet** [kiteco/issue-tracker#596]
Hi,

how install kite old version ?

**Comment by edzkite** [comment]
Hi,

Unfortunately, this is not supported or possible at this time. Is there a particular reason why you're interested in an older client?

**Comment by TechComet** [comment]
yes

`Sorry! Kite only runs on processor architectures with AVX support. Exiting now.`

**Comment by edzkite** [comment]
Unfortunately, we made the decision to drop support for non-AVX processors. Please see https://help.kite.com/article/101-kite-requires-avx-support for more details.
