### ISSUE TITLE
how to close this function，“find related code in File”?

### ISSUE THREAD

**Issue by KikyoLover** [kiteco/issue-tracker#597]
As the title indicates, I don’t like to use the function called "Find relevant code in a file" in the VS Code editor, I hope you can give me the option to turn it off. This is of no use to me and will give hints to interfere with my writing code.

**Comment by tonycheang** [comment]
There's a setting "Enable Line Decoration" that you can turn off to disable the decoration https://github.com/kiteco/issue-tracker/issues/581#issuecomment-780373721
