### ISSUE TITLE
Server Extension Unreachable Jupyter ab 3.0.5

### ISSUE THREAD

**Issue by ThamuMnyulwa** [kiteco/issue-tracker#601]
I am trying to install kite on jupyter-lab 3.0.5 but the server extension is not working. Instead, I am getting this error message:

    Server Extension Unreachable
    
   The jupyterlab-kite extension will not work because the jupyter-kite server extension could not be reached.
    
    To fix this, please ensure the jupyter-kite server extension is installed and active (`jupyter serverextension list`), then restart the JupyterLab process.

I have tried uninstalling it and reinstalling it using:

    pip install "jupyterlab-kite>=2.0.2"

but I cannot get the server extension to work:

    $ jupyter serverextension list
    
    config dir: /home/thecomp/.jupyter
        jupyterlab_code_formatter  enabled 
        - Validating...
          jupyterlab_code_formatter  OK
        jupyter_nbextensions_configurator  enabled 
        - Validating...
          jupyter_nbextensions_configurator 0.4.1 OK

**Comment by edzkite** [comment]
@ThamuMnyulwa What's the output of `jupyter server extension list`? In JupyterLab 3.0+ they modified the command with a space.

You should see something like:
```
    jupyter_kite enabled
    - Validating jupyter_kite...
      jupyter_kite 2.0.2 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.9 OK
```

**Comment by ThamuMnyulwa** [comment]
> @ThamuMnyulwa What's the output of `jupyter server extension list`? In JupyterLab 3.0+ they modified the command with a space.
> 
> You should see something like:
> 
> ```
>     jupyter_kite enabled
>     - Validating jupyter_kite...
>       jupyter_kite 2.0.2 OK
>     jupyterlab enabled
>     - Validating jupyterlab...
>       jupyterlab 3.0.9 OK
> ```

@edzkite the output looks like this: 

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ jupyter server extension list
Config dir: /home/thamu/.jupyter

Config dir: /usr/etc/jupyter

Config dir: /usr/local/etc/jupyter
</pre>

**Comment by edzkite** [comment]
Can you try running
```
jupyter server extension enable jupyter_kite
```
Also, ensure you have the Kite Engine process active.

**Comment by ThamuMnyulwa** [comment]
> Can you try running
> 
> ```
> jupyter server extension enable jupyter_kite
> ```
> 
> Also, ensure you have the Kite Engine process active.

Hi @edzkite ,

This is giving me an error as shown below.

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ jupyter server extension enable jupyter_kite
Enabling: jupyter_kite
- Writing config: /usr/etc/jupyter
    - Validating jupyter_kite...
      jupyter_kite 2.0.2 <font color="#4E9A06">OK</font>
     <font color="#CC0000"> X</font> Validation failed: [Errno 13] Permission denied: &apos;/usr/etc&apos;
</pre>

**Comment by edzkite** [comment]
Closing as discussion has moved to https://github.com/kiteco/issue-tracker/issues/608
