### ISSUE TITLE
Kite causes tccd, entire Mac to hang

### ISSUE THREAD

**Issue by rosstex** [kiteco/issue-tracker#607]
- [X] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
(I am unable to reinstall Kite to log this.)

I am running Mac OS X 11.3 Beta.

I noticed that soon after updating my computer, tccd was constantly hogging my CPU at around 80%. Separately, I noticed that applications were taking a long time to open (and while opening, the rest of the computer would hang). I eventually put these together, and also found that when I changed any permissions setting in Preferences > Security and Privacy, the computer would hang. This persisted across restarts and First Aid (in recovery mode).

I determined the issue was Kite by looking at the "Open Files and Ports" tab of tccd. Tccd had opened the Kite application 10 times at the bottom of the list. After quitting Kite, all issues went away.

**Comment by tonycheang** [comment]
Thanks for the report! We can track this issue here https://github.com/kiteco/issue-tracker/issues/587
