### ISSUE TITLE
Kite + VS Code failed to installed on Offline machine

### ISSUE THREAD

**Issue by Eldadc** [kiteco/issue-tracker#610]
Hi,

Offline environment without internet , without sign in operation.
Kite + VS Code failed to installed on Offline machine.
Each Press on Install Button for VS Code , Completes without doing anything. The status always stays on "Install".

Thanks

**Comment by edzkite** [comment]
Kite uses the VS Code CLI to programmatically install the Kite extension. Without an internet connection, this will not work.

**Comment by Eldadc** [comment]
Hi,

Thanks for the quick response.
So KIte support offline environment without internet ?

Thanks

**Comment by edzkite** [comment]
The Kite plugin requires the installation of a separate desktop application, which cannot be downloaded in an offline environment. However, once the application is installed, Kite can provide completions and other features offline.

**Comment by Eldadc** [comment]
Hi,

Is it possible to release a version that can be installed in offline network without internet

Thanks
