### ISSUE TITLE
Free University Licenses for Kite Pro

### ISSUE THREAD

**Issue by fbarez** [kiteco/issue-tracker#611]
Hi, after following the instructions on https://help.kite.com/article/135-free-university-licenses-for-kite-pro, I can still not redeem kite pro for students. Please could you advise? Thank you.

**Comment by tonycheang** [comment]
Thanks for reaching out. A few questions to help us debug:
- What steps did you go through, and which step did you get stuck at?
  - Were you prompted to log in with your university address?
  - Did you reach the page with "Finish activating your trial", i.e. `https://www.kite.com/pro/trial/?email={your-email}`?
- What's the domain of your university email address, and/or can you find the domain within here https://github.com/kiteco/swot/tree/master/lib/domains?

**Comment by fbarez** [comment]
So I had the university pro version last year and now when the page shows the following:
"
We are happy to offer free Kite Pro to students with a university email address.

To **redeem**, start a trial using a university email address, and the free Kite Pro licence will activate automatically."
Once I click on the redeem hyperlink I get : "Your free trial for Kite Pro has expired. Please upgrade to access Kite Pro" and there is no student free option available. 

Thanks.

**Comment by tonycheang** [comment]
Hm that's surprising. Can you send an email over to support@kite.com from your university address, linking to this issue? We'll need your email to track these bugs down.

**Comment by fbarez** [comment]
Thank you. I have sent an email. Could you please advise?

**Comment by fbarez** [comment]
Hi, Please can you get back to me?

**Comment by tonycheang** [comment]
Please check your spam filters. Below's the copy of the response I sent last week, and I resent the email just now as well for your convenience.
> I could not find this particular email in our system to check the expiry of your previous license. Have you tried creating an account for or logging into {the-email-from-which-you-emailed-us-from} first? If you haven't please do (log out from any existing account on our site first from the cog icon on the top right of https://www.kite.com/settings/account) and retry the link from the help page for obtaining a university license.

**Comment by fbarez** [comment]
Thank you.
