### ISSUE TITLE
Stuck on "initializing" - JupyterLab

### ISSUE THREAD

**Issue by KareemAlSaudi-RUG** [kiteco/issue-tracker#612]
- My OS: Windows 10 (64 bit)
- Kite application logs: [here](https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/723751/kite_local/client.log.2021-03-09_10-29-23-PM.bak.gz)
- Terminal console output: [here](https://i.imgur.com/kCbuUqs.png)
- Labextension list and server extension list: [here](https://i.imgur.com/pYcFz7U.png)
- Conda list: [here](https://justpaste.it/1p1ck)
- Environment.yml: [here](https://filebin.net/816hhtqc6slnz32j/environment.yml?t=yt5y5d82)

I'm just stuck on initializing but no matter what Kite won't seem to start up properly. Anybody have any idea why?

**Comment by edzkite** [comment]
Hi @KareemAlSaudi-RUG thanks for bringing this to our attention. Does the status change at all once you start typing?

The reason being, is that I just did a fresh install of Kite on Windows, and while I did see similar error messages in the terminal window, it eventually went away as Kite completed indexing.

**Comment by KareemAlSaudi-RUG** [comment]
Hi @edzkite! Pressing tab once to autocomplete a single line of code seems to have fixed it. Not sure why, but it's working now. Thanks for the help!
