### ISSUE TITLE
Kite no funciona en mi Nvim en WSL

### ISSUE THREAD

**Issue by Johan-Palacios** [kiteco/issue-tracker#698]
Hola, tengo un problema con kite al usarlo con nvim con WSL, resulta que pese a tener el ejecutable no inicia la herramienta de auto completado. 

Si alguien sabe la solución a este problema me ayudaría mucho

**Comment by ryantberg** [comment]
Kite installed on Windows doesn't work with vim/nvim in the WSL container. Kite and the editor either need to both be on Windows or both be in the WSL container.

You can find instructions for installing Kite on Linux at https://www.kite.com/linux/

If you already have Kite installed in the WSL container and there are still issues, please respond here.

=====================

Kite instalado en Windows no funciona con vim / nvim en el contenedor WSL. Kite y el editor deben estar ambos en Windows o ambos en el contenedor WSL.

Puede encontrar instrucciones para instalar Kite en Linux en https://www.kite.com/linux/

Si tiene Kite instalado en el contenedor WSL y todavía hay problemas, responda aquí.

**Comment by Johan-Palacios** [comment]
![image](https://user-images.githubusercontent.com/77251405/111242358-a0a23000-85c4-11eb-9e4f-050e3483a713.png)

Ese fue el mensaje que me dejo despues de instalarlo en WLS, pero no ha surtido efecto para VIM, sigue sin poderse usar Kite, si me pudieras indicar que paso prosigue después de esto

**Comment by ryantberg** [comment]
You will need to also install the vim plugin in WSL with the instructions listed here:
https://github.com/kiteco/vim-plugin/blob/master/DEVELOPMENT.md

Then, you will need to start Kite. You can manually run Kite with the command `nohup ~/.local/share/kite/kited &`, which will run Kite in the background and prevent it from terminating.

If you want to login to a Kite account on WSL, you can run the following command:
`~/.local/share/kite/login-user`

Note that WSL support is currently limited. Auto-start and auto-update do not work, and there is no Copilot. To update manually, you can run: `~/.local/share/kite/update`

==========================

También deberá instalar el complemento vim en WSL con las instrucciones que se enumeran aquí: https://github.com/kiteco/vim-plugin/blob/master/DEVELOPMENT.md

Entonces, deberás iniciar Kite. Puede ejecutar Kite manualmente con el comando `nohup ~/.local/share/kite/kited &`, que ejecutará Kite en segundo plano y evitará que finalice.

Si desea iniciar sesión en una cuenta de Kite en WSL, puede ejecutar el siguiente comando:
`~/.local/share/kite/login-user`

Tenga en cuenta que la compatibilidad con WSL es actualmente limitada. El inicio automático y la actualización automática no funcionan y no hay Copiloto. Para actualizar manualmente, puede ejecutar: `~/.local/share/kite/update`
