### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by oguh43** [kiteco/issue-tracker#707]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ x] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.
Toggle word wrap, 'Find related code in' does not respect it, goes out of bounds
**Screenshots**
![image](https://user-images.githubusercontent.com/13382592/112039640-8af0b580-8b44-11eb-8c44-7b893dba0603.png)
![image](https://user-images.githubusercontent.com/13382592/112039672-93e18700-8b44-11eb-96f5-a730f2024aa0.png)

**Comment by tonycheang** [comment]
Thanks for writing in. This looks like VSCode. We directly use the VSCode API to render the decoration, so this is the behavior of VSCode's decorations API. This looks like the corresponding issue: https://github.com/microsoft/vscode/issues/32856. Closing because we won't be able to fix this from our side.
