### ISSUE TITLE
JetBrains's Code With Me plugin conflicts with Kite

### ISSUE THREAD

**Issue by SamuelNLP** [kiteco/issue-tracker#716]
Cannot use it with the new Pycharm, even with version 1.8.25.

https://imgur.com/a/5uYnVnK

**Comment by matquant14** [comment]
I have same issue

**Comment by sanxiHsu** [comment]
![image](https://user-images.githubusercontent.com/56463570/114010032-49773e80-9896-11eb-8cd6-24eddca42fc3.png)
yes, me too ! look at this image

**Comment by nmweizi** [comment]
I have same issue

**Comment by Mehechiger** [comment]
Same issue here.

**Comment by matquant14** [comment]
only current workaround is to disable the Code with Me plugin

**Comment by ramannanda9** [comment]
same issue! kite pro and pycharm ultimate user!.

**Comment by iceman01** [comment]
Same for me. Kite plugin version 1.8.25 and Code With Me bundled 211.6693.115 under Pycharm Pro 2021.1. 
Issues for the two plugins have been reported earlier under issue #459, also see JetBrain's issue tracker, for example [CWM-1307](https://youtrack.jetbrains.com/issue/CWM-1307)

**Comment by jansorg** [comment]
Thanks, this be fixed soon with an update of the Kite plugin.

**Comment by iceman01** [comment]
Thanks @jansorg for letting us know!

**Comment by tonycheang** [comment]
Version `1.9.2` of the plugin should allow using Kite with Code With Me. Please update the Kite plugin, and let us know if you're running into any issues.
