### ISSUE TITLE
Kite site seems to be down

### ISSUE THREAD

**Issue by s1072489** [kiteco/issue-tracker#717]
Tried to access https://www.kite.com showed this:
![image](https://user-images.githubusercontent.com/79786672/113877200-d4572b00-97fb-11eb-9c99-87c376b088c8.png)

**Comment by bstncartwright** [comment]
Also experiencing this.

**Comment by mileyvirus** [comment]
Works now.

**Comment by tonycheang** [comment]
Thanks for the report! The site should be back up now.
