### ISSUE TITLE
When I close a IDE kited keeps running

### ISSUE THREAD

**Issue by arthurmelton** [kiteco/issue-tracker#718]
OS: arch linux
Version: 2.20210310.0
IDE: all

If it ever is opened and the ide is close it keeps running in the background. It will keep using resources and I would like to not have it running in the background. I think it also has some memory leak too but that is ok if you are in an ide but when it is running all the time it is not nice.

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/768961/kite_local/client.log.2021-04-07_11-00-08-PM.bak.gz

**Comment by tonycheang** [comment]
We can track this here: https://github.com/kiteco/issue-tracker/issues/580
