### ISSUE TITLE
Kite conflicts Code With Me in PyCharm

### ISSUE THREAD

**Issue by 1rens1** [kiteco/issue-tracker#721]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.
Before PyCharm 2021.1 was added, Kite was smooth sailing, but when the new update comes out, PyCharm says that Kite plugin _Conflicts_ with "Code With Me".

**Screenshots**
![Capture](https://user-images.githubusercontent.com/78131273/114110383-95ab9880-9901-11eb-8cf1-809056befb3a.PNG)

**Comment by tonycheang** [comment]
Thanks for the report. We can track this issue here: https://github.com/kiteco/issue-tracker/issues/716
