### ISSUE TITLE
Kite not working on Jupyterlab 3.0.12

### ISSUE THREAD

**Issue by Esther-99** [kiteco/issue-tracker#722]
OS: Ubuntu 20.04
**Browser console logs:**
![image](https://user-images.githubusercontent.com/56192986/114125686-88a29f80-9929-11eb-8fd3-f34d91f9fdbf.png)
**Terminal Console output:**
![image](https://user-images.githubusercontent.com/56192986/114125820-c99ab400-9929-11eb-8ccb-2b2e0e6a6216.png)
**Kite Application Logs:** https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/649221/kite_local/client.log.2021-04-09_11-51-32-AM.bak.gz
**Conda environment:**
[environment.zip](https://github.com/kiteco/issue-tracker/files/6283073/environment.zip)
**Extension List:**
![image](https://user-images.githubusercontent.com/56192986/114126388-eb486b00-992a-11eb-81ac-03fea3f5051a.png)

**Comment by edzkite** [comment]
Under lab extensions, it looks like the version number for @kiteco/jupyterlab-kite is wrong (v1.2.0). The correct values should be as such:

```
.../share/jupyter/labextensions
        @kiteco/jupyterlab-kite v2.0.2 enabled OK (python, jupyterlab_kite)
```

Please try uninstalling and reinstalling the extension again https://github.com/kiteco/jupyterlab-kite#installing-the-kite-extension-for-jupyterlab

**Comment by Esther-99** [comment]
Thank you. It works now. I should install it using pip instead of Extension Manager.
