### ISSUE TITLE
Kite not compatible with PyCharm

### ISSUE THREAD

**Issue by railgadi** [kiteco/issue-tracker#724]
Hello,
I am getting error (per the screenshot) with PyCharm Ultimate 2021.1 on Mac OS 11.2.3. Can you provide a solution please?
![Kite](https://user-images.githubusercontent.com/9346197/114304962-df33e900-9aa3-11eb-93df-73f7175b059d.png)

**Comment by DaveKaretnyk** [comment]
Same problem for me running 2020.1 on Windows 10.X. Blocking issue for me.

**Comment by ruslaniv** [comment]
Yes, same problem with PyCharm 2021.1 (Professional Edition) Build #PY-211.6693.115, built on April 6, 2021 on macOS 10.15.7

**Comment by railgadi** [comment]
Closing as already covered in issue [716](https://github.com/kiteco/issue-tracker/issues/716)
