### ISSUE TITLE
Kite not working/showing up in jupyterlab v3.0.14

### ISSUE THREAD

**Issue by shreeratn** [kiteco/issue-tracker#730]
OS - Windows 10
Browser console logs - 
![msedge_J5aFtf2cuK](https://user-images.githubusercontent.com/35227731/115137756-96e96d80-a045-11eb-9b77-df8f636e8711.jpg)

Terminal console output -
![pwsh_CbOaqtXmhc](https://user-images.githubusercontent.com/35227731/115137774-b54f6900-a045-11eb-8ae2-2c0af96d2633.jpg)

Generate Kite Application Logs (https://help.kite.com/article/96-contact-us-with-logs)

The output of jupyter labextension list, jupyter serverextension list - 
![pwsh_VEKWCLmX7M](https://user-images.githubusercontent.com/35227731/115137815-e760cb00-a045-11eb-927f-be13a78cddd5.jpg)

and jupyter server extension list - 
![pwsh_SwQygCK2bR](https://user-images.githubusercontent.com/35227731/115137855-18410000-a046-11eb-9448-d2d7b3a0195f.jpg)

The output of pip list - 
| Package             Version   |
|-------------------------------|
| ------------------- --------- |
| anyio               2.2.0     |
| appdirs             1.4.4     |
| argon2-cffi         20.1.0    |
| async-generator     1.10      |
| attrs               20.3.0    |
| Babel               2.9.0     |
| backcall            0.2.0     |
| bleach              3.3.0     |
| certifi             2020.12.5 |
| cffi                1.14.5    |
| chardet             4.0.0     |
| colorama            0.4.4     |
| decorator           5.0.7     |
| defusedxml          0.7.1     |
| deprecation         2.1.0     |
| distlib             0.3.1     |
| entrypoints         0.3       |
| filelock            3.0.12    |
| idna                2.10      |
| importlib-metadata  3.10.1    |
| ipykernel           5.5.3     |
| ipython             7.22.0    |
| ipython-genutils    0.2.0     |
| jedi                0.18.0    |
| Jinja2              2.11.3    |
| json5               0.9.5     |
| jsonschema          3.2.0     |
| jupyter-client      6.1.12    |
| jupyter-core        4.7.1     |
| jupyter-kite        2.0.2     |
| jupyter-packaging   0.9.1     |
| jupyter-server      1.6.2     |
| jupyterlab          3.0.14    |
| jupyterlab-kite     2.0.2     |
| jupyterlab-pygments 0.1.2     |
| jupyterlab-server   2.4.0     |
| MarkupSafe          1.1.1     |
| mistune             0.8.4     |
| nbclassic           0.2.7     |
| nbclient            0.5.3     |
| nbconvert           6.0.7     |
| nbformat            5.1.3     |
| nest-asyncio        1.5.1     |
| notebook            6.3.0     |
| packaging           20.9      |
| pandocfilters       1.4.3     |
| parso               0.8.2     |
| pickleshare         0.7.5     |
| pip                 21.0.1    |
| prometheus-client   0.10.1    |
| prompt-toolkit      3.0.18    |
| pycparser           2.20      |
| Pygments            2.8.1     |
| pyparsing           2.4.7     |
| pyrsistent          0.17.3    |
| python-dateutil     2.8.1     |
| pytz                2021.1    |
| pywin32             300       |
| pywinpty            0.5.7     |
| pyzmq               22.0.3    |
| requests            2.25.1    |
| Send2Trash          1.5.0     |
| setuptools          56.0.0    |
| six                 1.15.0    |
| sniffio             1.2.0     |
| terminado           0.9.4     |
| testpath            0.4.4     |
| tomlkit             0.7.0     |
| tornado             6.1       |
| traitlets           5.0.5     |
| typing-extensions   3.7.4.3   |
| urllib3             1.26.4    |
| virtualenv          20.4.3    |
| wcwidth             0.2.5     |
| webencodings        0.5.1     |
| wheel               0.36.2    |
| zipp                3.4.1     |

**Comment by shreeratn** [comment]
Works fine in VS Code, and I now regret having kite pro

**Comment by edzkite** [comment]
What command(s) did you use to install Kite for JupyterLab?

The output of `jupyter serverextension list` should be:
```
config dir: ...
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.0.10
```
whereas the output of `jupyter server extension list` should be:
```
Config dir: ...
    jupyter_kite enabled
    - Validating jupyter_kite...
      jupyter_kite 2.0.2 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.10 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK

Config dir: /usr/local/etc/jupyter
```

Note that the Kite extension only shows up for the latter command.

**Comment by shreeratn** [comment]
I used the one shown on your GitHub page for lab>3.0.0

**Comment by shreeratn** [comment]
I think I should make a venv and try out as new... can you guide me through it?

**Comment by shreeratn** [comment]
**The only solution worked for me for labs >3.0**

- have kite engine up and running
- use `jupyter --paths` and **delete** everything from all locations in output.
- **uninstall all pip packages** (you can use `pip freeze > re.txt` then `pip uninstall -r re.txt -y`
- **delete** all pip cache and any remains of Jupyter (trust me there will be remains- you need to hunt them down)
- reinstall python (I recommend **v3.7.9** as it's the most stable one till date)

Now do a `pip list` - it should show only 3 packages:
- setuptools
- wheels
- pip

We are good to do the closing ceremonies:
- install jupyter-lab using `pip install jupyterlab`
- launch it using `jupyter-lab`
- shutdown the jupter-lab
- now install kite using `pip install "jupyterlab-kite>=2.0.2"`
- Check `jupyter serverextension` list:(ignore the version)
                 - **It SHOULD and MUST BE Like this**

```
config dir: ...
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.0.10
```


- now check `jupyter server extension list`:(ignore the version)

```
Config dir: ...
    jupyter_kite enabled
    - Validating jupyter_kite...
      jupyter_kite 2.0.2 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.10 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK

Config dir: /usr/local/etc/jupyter
```

- If the `jupyter serverextension` and `jupyter server extension` are not in the format given above it will not work.
- I was trying this for last 4 months
Finally did it

**Comment by ArrowRaider** [comment]
It says Kite initializing and never does anything else.  How do I fix this?

**Comment by shreeratn** [comment]
> It says Kite initializing and never does anything else. How do I fix this? Kite is the hardest program I've ever tried to get working. This is absolutely ridiculous and unacceptable.

try writing code and see if it auto completes... just to check that engine is fine use kite with vs code or pycharm for a test run

**Comment by ArrowRaider** [comment]
This was it.  It does work, the UI just gets stuck at initializing until I start typing code.  I had been waiting last time before even trying it.
