### ISSUE TITLE
No autocomplete shown in pycharm after kite plugin updated today!

### ISSUE THREAD

**Issue by IliyaBrook** [kiteco/issue-tracker#732]
after today's update Kite autocomplete not shown, code with me disabled,
I have tried to reinstall kite and Pycharm,it didn't help...
kite plug in status: Kite is ready!
![image](https://user-images.githubusercontent.com/60712617/115596547-e5feff00-a2e0-11eb-94d7-8c1ec8a90237.png)

Kite logs:
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/765493/kite_local/client.log.2021-04-21_08-38-18-PM.bak.gz

no autocomplete =((

![image](https://user-images.githubusercontent.com/60712617/115596745-252d5000-a2e1-11eb-8c73-9ee1e79ce231.png)

Best regards

**Comment by tonycheang** [comment]
Thanks for including logs. Can you open the Kite Copilot and check whether the `Disable all completions from Kite` checkbox is checked?

**Comment by IliyaBrook** [comment]
> Thanks for including logs. Can you open the Kite Copilot and check whether the `Disable all completions from Kite` checkbox is checked?

sorry,missed this thing, strange,because i'm didn't be able this flag by myself =/

**Comment by tonycheang** [comment]
No worries. Glad we could figure it out!
