### ISSUE TITLE
Kite not show Documentation in WSL

### ISSUE THREAD

**Issue by Johan-Palacios** [kiteco/issue-tracker#765]
### Kite not show Documentation in WSL

When I press `gK` or `K` in normal mode Kite not shows the documentation

![image](https://user-images.githubusercontent.com/77251405/120051686-d315d380-bfde-11eb-9a70-11ec28e9f852.png)

And I have this configuration in my `init.vim`

![image](https://user-images.githubusercontent.com/77251405/120051859-af06c200-bfdf-11eb-8cca-908f749ee4dc.png)

Can you give me a solution for this issue, I want to work with the documentation when I'm programming in Python and JS

**Comment by airblade** [comment]
The plugin only maps `K` to open documentation if you [don't already have a map](https://github.com/kiteco/vim-plugin/blob/c80323d49447ecc34f3bc23d3f14e2a114916c8e/autoload/kite.vim#L171-L173) for `K` and haven't already mapped `<Plug>(kite-docs)`.

What does `:verbose nmap K` produce?

**Comment by airblade** [comment]
Oh, I just noticed the last line of your second screenshot where you have mapped `gK` to `<Plug>(kite-docs)`.

In that case `gK` should invoke the documentation.  And in fact your first screenshot shows `No documentation available` at the bottom, so the documentation function is being called by your `gK` map.

So the plugin is behaving correctly.  The question is why doesn't Kite itself produce documentation for `json.dumps`?

One thing that would cause this is Kite not running.  Please can you tell me whether it's running?  It looks a bit like this:

<img width="404" alt="Screenshot 2021-06-01 at 12 29 43 pm" src="https://user-images.githubusercontent.com/7265/120316217-1620c100-c2d5-11eb-89ea-5ef52544d746.png">

**Comment by Johan-Palacios** [comment]
Kite works because that show me the autocomplete, but I have the problem that kite works slow too

PD: I change my colorscheme to one dark 

![image](https://user-images.githubusercontent.com/77251405/120585765-976c7680-c3ef-11eb-95da-ceb1abdf7dc2.png)
