### ISSUE TITLE
Signing Up

### ISSUE THREAD

**Issue by Jimmygjr10** [kiteco/issue-tracker#770]
![Kit1_bug1](https://user-images.githubusercontent.com/83085800/120356700-3d25c580-c2ca-11eb-9253-372a75412b92.PNG)

![Kite](https://user-images.githubusercontent.com/83085800/120356538-1071ae00-c2ca-11eb-829d-e4a2ddb849e0.PNG)

I am having issues signing up, I tried uninstalling and downloading again but I get the same error message. I even confirmed my Git config email. I notice it doesn't give me the option to "continue without email" per Quick start.  Please Help

Thank you

**Comment by tonycheang** [comment]
Thanks for the bug report! We made a change that should have fixed this. Can you confirm that you can sign up? We can reopen the issue if this persists.
