### ISSUE TITLE
Kite dosn't works at the pair to LSP native in NVIM

### ISSUE THREAD

**Issue by Johan-Palacios** [kiteco/issue-tracker#784]
OS: WSL Ubuntu
Editor: NVIM 0.5

Hi, recently I want to work kite at the same time with LSP native of nvim, but when I tried this https://github.com/kiteco/vim-plugin/blob/master/LSP.md, kite doesn't work, and I tried to enable this into [compe](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi8upP2rPrxAhW5RTABHRqsAAYQFjAAegQIBhAD&url=https%3A%2F%2Fgithub.com%2Fhrsh7th%2Fnvim-compe&usg=AOvVaw0F3olYJ67xxpIK2MOL51R1) config, but it doesn't work, can you give me a solution for this?

**Comment by airblade** [comment]
Please can you switch on logging and upload the log file here?

https://github.com/kiteco/vim-plugin#debugging

**Comment by Johan-Palacios** [comment]
I put this in my init.vim, but it not show the logs :/

![image](https://user-images.githubusercontent.com/77251405/126917328-bcc50293-7a11-46a9-9dcd-18a0d8419390.png)

**Comment by Johan-Palacios** [comment]
> Please can you switch on logging and upload the log file here?
> 
> https://github.com/kiteco/vim-plugin#debugging
> 
> > On 24 Jul 2021, at 02:19, Johan Emanuel Palacios Rivera ***@***.***> wrote:
> > 
> > ﻿
> > OS: WSL Ubuntu
> > Editor: NVIM 0.5
> > 
> > Hi, recently I want to work kite at the same time with LSP native of nvim, but when I tried this https://github.com/kiteco/vim-plugin/blob/master/LSP.md, kite doesn't work, and I tried to enable this into compe config, but it doesn't work, can you give me a solution for this?
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Hey, can you help me to solve the problem?

**Comment by airblade** [comment]
Sorry for the delay, I've been away.

I presume you looked for the log file in nvim's working directory (not where nvim or the plugin is installed)?

Assuming you did, perhaps Kite isn't even starting.  Do you know if Kite ever launches?  You can look at your processes or within nvim do this: `:echo kite#utils#kite_running()`.  `0` means not running, `1` means running.

**Comment by Johan-Palacios** [comment]
I tried the command
![image](https://user-images.githubusercontent.com/77251405/127889206-62c28a29-887f-4a0c-bbc8-e2f5acd63bf0.png)
I think that is probably that kite is not working in my machine
![image](https://user-images.githubusercontent.com/77251405/127889251-a040f5cc-0d9c-4aed-b516-ba4782f1ab39.png)

**Comment by airblade** [comment]
That indicates the plugin isn't installed at all.

How did you install the plugin?

**Comment by Johan-Palacios** [comment]
I uninstalled and installed the plugin again, and now it show the 0 value

![image](https://user-images.githubusercontent.com/77251405/127898499-dc806155-1c1b-4720-93ae-8a5411131dec.png)

![image](https://user-images.githubusercontent.com/77251405/127898509-d50c0f68-1fbb-4155-aaa8-32a32bb00696.png)

**Comment by airblade** [comment]
That's progress :)

The plugin relies on a separate Kite process which evidently is not running.  I would expect it to start itself but clearly it hasn't.  You can launch it with `:KiteEnableAutoStart` inside nvim and then it will always start itself.

**Comment by Johan-Palacios** [comment]
OK, now kite it works
![image](https://user-images.githubusercontent.com/77251405/128054570-61d55878-d220-4cb6-aa72-66dcd3055735.png)
but, I want to use LSP and kite at the same time, you know how I can do that?
![image](https://user-images.githubusercontent.com/77251405/128054800-381612f7-08b5-40fb-b682-67b006ddcfba.png)

**Comment by airblade** [comment]
Do the [instructions here](https://github.com/kiteco/vim-plugin/blob/master/LSP.md#neovim-lsp) work for you now?

**Comment by Johan-Palacios** [comment]
Yes, I write this code for LSP, but it not works,
![image](https://user-images.githubusercontent.com/77251405/128223842-4e390953-be8f-4dbe-b35a-3c2e44f00ecb.png)
 probably I need to change this in a Lua file, like this, but I don't know how I can to implement kite
![image](https://user-images.githubusercontent.com/77251405/128226927-12cbaeda-02d1-4cf8-881b-ce6e46c586c3.png)

**Comment by airblade** [comment]
@metalogical Before I spend too much time on this, have you got Kite's LSP working with Neovim's built-in LSP?

I can't get our instructions to work.  For example, `lsp#register_server()` doesn't seem to exist.  I'm guessing it's from [prabirshrestha/vim-lsp](https://github.com/prabirshrestha/vim-lsp)?

**Comment by Johan-Palacios** [comment]
Yes, I have Neovim's built-in LSP 
and I use this plugins

- neovim/nvim-lspconfig 
- hrsh7th/nvim-compe

My configs for LSP is [here](https://github.com/Johan-Palacios/Nvim-config/blob/master/lua/lsp/init.lua)
