### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by paulmunyao** [kiteco/issue-tracker#820]
It appears that kite isn't installing in my VSCode because the message that i'm getting is that it's temporallily down.
KIndly advise.
Regards
Paul Munyao Mutiso

**Comment by SpaceTesla** [comment]
kite.com says
>Kite is temporarily unavailable
>Sorry, Kite is temporarily unavailable. Please leave your email below and we'll notify you when we're back up!

It's been quite long. When are they bring kite back

**Comment by Khounborinn** [comment]
Kite.com has been down since about June/July 2021, and not contact has been made from them. Has anyone been able to get into contact with the development/support team?

**Comment by Alan-Py** [comment]
I was also unable to download kite through the official website

**Comment by RavyarSarbast** [comment]
I get error 502 as bad gate way I

**Comment by adamsmith** [comment]
https://github.com/kiteco/kiteco-public/releases/tag/2021-06-10
