### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by gonoff2411** [kiteco/issue-tracker#822]
Hello people,

So i have problem when i install one extension, and that is Kite.

When i install kite in the bottom right of my VS it says kite: not installed, i tried reinstalling it but it didn't change anything?

Anyone knowing some solutions?

**Comment by AleYepes823** [comment]
happens the same to me

**Comment by heteloo** [comment]
I tried to download kite, but the site couldn't download it.
I see text like "Kite is temporarily unavailable".

**Comment by alhassaneplea4** [comment]
Comment est-ce possible de pouvoir activer kite et aussi le github copilot s'il vous plaît

**Comment by adamsmith** [comment]
https://github.com/kiteco/kiteco-public/releases/tag/2021-06-10
