### ISSUE TITLE
Download page unavailable

### ISSUE THREAD

**Issue by kyri-petrou** [kiteco/issue-tracker#823]
**Describe the bug**

Been trying for a few days now to download Kite, and I'm being greeted with a "Kite is temporarily unavailable" message. Based on some comments in other issues, it seems that this might be happening for the past 2 weeks now. Do you know when will the service be available again?

Platform: MacOS 12.2 / ARM64

In the meantime, is there any other link that I could use to download Kite?

**Screenshots**
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/67301607/158044810-f9a73e76-83c8-4995-82a5-b62fb18046fc.png">

**Comment by Abdelmonimsamadi** [comment]
No idea.

**Comment by adamsmith** [comment]
https://github.com/kiteco/kiteco-public/releases/tag/2021-06-10
